### ISSUE TITLE
subject auto-number doesn't increment properly when the most recent subject has had its name changed

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#100]
I.e. I make a subject that gets autoname C57_5. I change that subjects name to "dummy". Now I make a new subject, it gets autoname C57_5, but should be C57_6 to avoid confusion. 

Perhaps a different way to implement this would be to have a hidden read-only field of the Line that is "subject_autoname_index" (probably also "cage_autoname_index" and "litter_autoname_index") that tells what the new subject's index should be and gets incremented when used?

**Comment by rossant** [comment]
Yes that could work.

**Comment by rossant** [comment]
done
