### ISSUE TITLE
expose water_requirement_remaining

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#101]
I'm not sure exactly what way you'd like to do this, but I need to be able to access this number from matlab. It looks like it isn't accessible from SQL queries (am I wrong about that?) so one approach here would be to make Subject have a new read-only field water_requirement_remaining and fill it any time a weighing happens on that subject and/or a water_administration happens on that subject. 

The other way I can think of to do it is to make a rest API endpoint specifically for it, which seems like a reasonable idea. It should return a record for every subject, and the record includes:
subjects_subject.nickname
water_requirement_total
water_requirement_remaining

It should be filterable by subject nickname and/or alive. So something like:

http://alyx.cortexlab.net/water_requirements
http://alyx.cortexlab.net/water_requirements?nickname=Herodotus
http://alyx.cortexlab.net/water_requirements?alive=y

Sound good?

**Comment by rossant** [comment]
Don't you have already a subject end-point? Wouldn't it just be a matter of adding this new field in the returned struct?

**Comment by nsteinme** [comment]
Yes we do have a subjects endpoint. But we were realizing that the subjects endpoint is already slow to return (like 4 sec) thanks to lots of table joins. Possible solutions to this are:
1) Try to figure out a more efficient back-end implementation of the endpoint, like with caching the "mostly static" tables like auth_user, strains, species. I don't know whether there's anything to do along these lines. 
2) Add plenty of filtering options so you are never asking for all the subjects. 
3) Add separate endpoints for different kinds of uses so you never or rarely access that full list of lots of fields. 

The suggestions I made were a bit of 2 and a bit of 3, which is why I started the post with "I'm not sure exactly what way you'd like to do this" :)

**Comment by rossant** [comment]
4 seconds seems like a lot!! I'm quite surprised, even when there are many joins, because I guess the tables are quite small. I suppose you already investigated https://wiki.postgresql.org/wiki/Slow_Query_Questions. I agree that it is important that we try to improve the performance sooner rather than later. Delays are only getting longer and longer as users start to fill in more and more data.

**Comment by nsteinme** [comment]
Well there are about 1000 subject records, added automatically, as you can see, after 4 seconds, here: http://alyx.cortexlab.net/subjects

I haven't investigated that stuff about slow queries but I'm sure @nippoo will get to it when he has time.

**Comment by rossant** [comment]
What about pagination? That's what facebook twitter etc are using with their REST APIs. Any reason why you would need to charge that many details about that many subjects at once?

**Comment by nsteinme** [comment]
I'm not sure how pagination works with a programmatic request, like from
matlab?

I guess the point is that I had originally imagined that if I wanted to,
for instance, get a list of all the subject nicknames that belong to me and
are strain B6;129, in matlab, then I need to issue a rest api request for
subjects, and sort/select the result myself. Instead looks like I should be
doing an SQL query from matlab, or the rest api should allow filtering
directly - the only problem with the latter result is trying to guess all
the things you'd want to filter on, and build them all in. Maybe there's a
way to do that automatically?

Another way of filtering that you'd want to do is to just get a subset of
fields, e.g. maybe I just want a list of all subject nicknames - again easy
to do with the SQL query, not easy to do with the rest api so far as I
know?

If I really want to get all of this information for all subjects (and I
don't need to do any sub-selecting) then probably 4 seconds is ok, because
that would be a rare kind of query.

**Comment by rossant** [comment]
I think it is better to filter on the server side. It should be easy to allow for many filtering options via the REST API. That might not be a best practice when it comes to security, but in our case I think that's fine. Example:

`/subjects/?raw_filter='responsible_user=nick&strain="B6;129"&birth_date>=2016_01_01'`

To get a subset of the fields I guess you could have something like:

`/end_point/?fields=responsible_user,strain,birth_date`

**Comment by nsteinme** [comment]
Yeah that sounds great to me! Let's discuss further with Max when he's
back, since I guess I am probably misunderstanding something about this
comparison between this and the current system, or else I'm not realizing
part of what has gone into Max's strategy so far.

**Comment by rossant** [comment]
I admit I haven't looked at all at the current implementation at the moment...

**Comment by nsteinme** [comment]
Ok by the way, when I do the SQL version of the query on the full subjects table with all seven joins (query below) it takes <0.1 seconds from matlab, and seems like similar from psql command line (not sure how to time it). So there must be some inefficiency in the back-end. 

```
SELECT subjects_subject.id,
subjects_subject.nickname,
subjects_subject.sex,
subjects_subject.birth_date,
subjects_subject.death_date,
subjects_subject.implant_weight,
subjects_subject.notes,
subjects_subject.ear_mark,
subjects_cage.cage_label AS cage,
subjects_line.name AS line,
subjects_litter.descriptive_name AS litter,
auth_user.username AS responsible_user,
subjects_source.name AS source,
subjects_species.display_name AS species,
subjects_strain.descriptive_name AS strain,
subjects_subject.wean_date,
subjects_subject.actual_severity,
subjects_subject.adverse_effects,
subjects_subject.cull_method,
subjects_subject.json,
subjects_subject.request_id
FROM subjects_subject
LEFT JOIN subjects_line on subjects_subject.line_id=subjects_line.id
LEFT JOIN subjects_cage on subjects_subject.cage_id=subjects_cage.id
LEFT JOIN auth_user on subjects_subject.responsible_user_id=auth_user.id
LEFT JOIN subjects_litter on subjects_subject.litter_id=subjects_litter.id
LEFT JOIN subjects_source on subjects_subject.source_id=subjects_source.id
LEFT JOIN subjects_species on subjects_subject.species_id=subjects_species.id
LEFT JOIN subjects_strain on subjects_subject.strain_id=subjects_strain.id
ORDER BY subjects_subject.birth_date DESC
```
