### ISSUE TITLE
new fields for subject: cull method, actual severity, adverse effects

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#105]
Cull method is a short text field (1024 characters ok)
Adverse effects is a longer text field (like a "narrative" or whatever)
Actual severity must be {'Sub-threshold', 'Mild', 'Moderate', 'Severe', 'Non-recovery'} (as per [home office regulations](https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/276014/NotesActualSeverityReporting.pdf))

In the individual subject view, they could be grouped under subheading "Outcomes", maybe.

**Comment by rossant** [comment]
done
