### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#106]
Two places:
![image](https://cloud.githubusercontent.com/assets/7590975/23333515/aab1e65e-fb84-11e6-852f-7e8b62150ed5.png)
(I think Pharmacology can be singular, or if plural Pharmacologies)

![image](https://cloud.githubusercontent.com/assets/7590975/23333524/cf8ccc82-fb84-11e6-9270-040316a5520d.png)
(if those L's need to be there for some reason, it's ok, not the end of the world - just noticed it)

**Comment by rossant** [comment]
Done. django tends to guess the plural of the models just by appending an S at the end... sometimes it just doesn't work :)
