### ISSUE TITLE
fourth option for zygosity: "present"

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#11]
@kdharris101 

Currently there are three options for zygosity: absent, heterozygous, and homozygous. We need a fourth option "present" for tests that you do which don't reveal whether it is het or homo. Or, even if they do, for clarity in what was actually measured. E.g. in AI95, we genotype for GFP (which indicates whether gcamp is present, i.e. whether the AI95 gene is present at least once) and for the ROSA-WT gene, which indicates whether AI95 is missing from at least one of the rosa loci. From this we _infer_ the het/homo/absent status of the AI95 - but I think we should record all three things. So we would record this as:

GFP: absent; ROSA-WT: present; AI95: absent
or
GFP: present; ROSA-WT: present; AI95: heterozygous
or
GFP: present; ROSA-WT: absent; AI95: homozygous

This is both unambiguous, convenient (because you could sort by the AI95 zygosity directly), and preserves the "raw data" that was actually collected.

**Comment by rossant** [comment]
Done.
