### ISSUE TITLE
another subjectrequest thing

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#110]
When someone makes a request, could it send an email to Charu? Just "UU requested: RR" where UU is the responsible username and RR is the request string. 

And when a subject is added to a request, could it send an email to the responsible_user if the responsible_user has an email address? Just "Subject SS was assigned to you for request RR" where SS is the subject nickname.

**Comment by rossant** [comment]
Should be done, but I guess it's not going to work until the SMTP server is properly configured (unless it already is?). I'm going to open a new issue for Max.
