### ISSUE TITLE
adverse effects view

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#114]
Charu requests a way to see all the mice with adverse effects at a glance, i.e. to do the query below. I think it may be worth figuring out how to do custom views like this, either within the admin page or not, and being able to set them up readily. Do you (@rossant, @nippoo ) know how to do this or want to give me some pointers for how to learn? I might be able to respond to desired views more easily. Need to not only make the view, but also link to it from somewhere, I guess. 

```
select subjects_subject.nickname, 
auth_user.username AS responsible_user,
subjects_subject.sex,
subjects_subject.birth_date,
subjects_subject.death_date,
subjects_subject.ear_mark,
subjects_line.name AS line,
subjects_subject.actual_severity,
subjects_subject.adverse_effects,
subjects_subject.cull_method
FROM subjects_subject
LEFT JOIN subjects_line on subjects_subject.line_id=subjects_line.id
LEFT JOIN auth_user on subjects_subject.responsible_user_id=auth_user.id
WHERE subjects_subject.adverse_effects NOT IN ('')
ORDER BY subjects_subject.birth_date DESC
```

which in matlab shows me 

```
    nickname     responsible_user    sex     birth_date     death_date    ear_mark             line             actual_severity                  adverse_effects                  cull_method
    _________    ________________    ___    ____________    __________    ________    ______________________    _______________    ___________________________________________    ___________

    'AI148_6'    'charu'             'F'    '2017-02-22'    'null'        ''          'AI148(TITL2-GCaMP6F)'    'null'             'so many bad things happened to this mouse'    ''         

```

which is all we need to see, just pretty much exactly that but somewhere charu can click a link to see it.

**Comment by rossant** [comment]
I'll look into how to make custom views. Read-only is enough? You want to make "list model" views (with tables) and not "add/change model" (with forms)?

**Comment by rossant** [comment]
@nsteinme for this particular exemple, is it conceivable to just consider the existing subjects page which lists all subjects, and add the column and filtering options that you'd want?

**Comment by nsteinme** [comment]
Since Adverse Effects is an open text field, it wouldn't be ideal to add it
to the already-crowded table at the Subjects page. If there's a way to
select (with check-boxes or something) which columns are displayed, though,
then that would totally do it. If you want we can try adding it there and
see how it looks.

But bigger picture, that page is already serving as the "Line spreadsheet"
substitute, and here we're trying to accommodate one of the functions of
the "Procedure log" spreadsheet. So it makes sense to have two different
"views" for these things, logically speaking.

Anyway yes read-only is enough for this, and yes a table not add/change
form. It would be great if it were possible also to make the _id fields
into links too like you did on the Subjects page but that's not totally
critical. The mere text table is enough.

**Comment by rossant** [comment]
Note for self:

```python
class MyAdmin(admin.AdminSite):
    def get_urls(self):
        urls = super(MyAdmin, self).get_urls()
        urls += patterns('',
                         url(r'^orders/$',
                             self.admin_view(my_view),
                             kwargs={'current_app': self.name},
                             name="my-view"),
                         )
        return urls
```

**Comment by nippoo** [comment]
OK. Custom views. There are several ways of skinning this cat...

1. Hack the admin interface - adding a custom view possibly subclassing some existing admin ListView.
You can try it, but you'll probably realise it's a waste of time. Trying to do this kind of thing will take ages.

2. Use regular Django templates and views.
This is probably the most obvious way of doing it. The big problem with this is that you end up having to write various bits of logic in three places - API, admin, and the views. And you can't easily access these views from MATLAB etc without having to copy-paste this kind of code.

3. Implement it as an API endpoint (in this case you probably just need to have a filter on an existing view...), then write a view using angular.js / some similar JS framework.
This is probably the way I'd do it. This way, you can access these kind of things from MATLAB / web with one set of back-end logic.

**Comment by nippoo** [comment]
That said, in this case (as opposed to more complex things like Nick's dashboard) you might just be able to get away with creating a filter on the AdminSite (like my dead/alive ones https://github.com/cortex-lab/alyx/blob/master/alyx/subjects/admin.py#L44)? If you want a different set of columns to the regular Subjects view (ie you specifically don't want to display adverse effects in the normal ListView) then you can use a proxy model to create a separate view. http://stackoverflow.com/questions/2223375/multiple-modeladmins-views-for-same-model-in-django-admin

Doing this regularly will make the codebase pretty clunky though...

**Comment by rossant** [comment]
I very much like that last solution. I find it pretty clean when all you want is just a secondary "list view" with a different set of columns and filters...

@nsteinme do you have an idea of how many custom views you'd like to do?

**Comment by nsteinme** [comment]
It's a bit hard to predict - basically what is happening is that I go to
Charu and show her what we have and she says "but in my current
spreadsheet, I can see/do *this* thing easily". Given that there are just a
few current spreadsheets I don't think there will be too many of those
things. But it's hard to say for sure. In any case I agree, the proxy model
solution sounds great because it will additionally allow us to take
advantage of the admin interface's filtering and linking and sorting
abilities, i.e. we can add a filter by responsible_user (not just "me" and
"all" here but each individually) and by whether the subject has anything
in adverse effects (default only show those that do) and make the subject
nickname be a link to the full subject page. So a proxy model called
"Subjects: Adverse Effects View" for instance, something like that.

That said, Max if you want to try your endpoint+js thing and document it so
that I could make more of them in the future, then don't let me stop you!
Here it isn't 100% critical to access this from matlab (as noted above, I
already have the SQL query that produces exactly what we want, so I am
already done accessing it from matlab). I tried to tell Charu, oh, you know
I can show you the adverse effects stuff easily, it's just one line in
matlab, and you can imagine what was her level of excitement about that
compared to mine :)

**Comment by rossant** [comment]
@nsteinme I'll try to do one such custom view and I'll show you how it works. I suspect it's going to be really simple. Then you can do pull requests and add custom views yourself when you need them.

**Comment by nsteinme** [comment]
For what it's worth, @kdharris101 enlightened me about what exactly the word "view" means in SQL, i.e. [here](https://www.w3schools.com/sql/sql_view.asp). So we should be able to take the SQL statement I gave above, prepend `CREATE VIEW adverse_effects_view AS`,  and put it into the database definition, thus creating a View that can be accessed like a real table, including making its own admin interface link. Of course I don't know how django treats such views, like whether they would be exposed for admin interfacing in the same way (I think that they would for sure, though) - or perhaps it is the case that this proxy model is an alias of the exact same thing. 

I think, also, that in principle you could make one of these, using SQL commands, that completes the subjectrequests table with Open/Closed, remaining, etc - but this does seem to get quite complicated quickly. Then that one could be the one that's backed up, and the one that gets shown on the admin page. If implementing the logic in python then exposing the results via rest api is easier then it's probably the way to go, though. 

I still can't believe django doesn't have a way to allow you to make views expose-able to SQL queries. [Here's](https://blog.rescale.com/using-database-views-in-django-orm/) a way to interact in django with views that you created in SQL. But we want the reverse: interact in SQL with views you created in django. Must be a way?

**Comment by rossant** [comment]
The last link you gave looks great, that's actually what we want and not the other way around. There is simply no way to interact in SQL with views created in django/python. What we might want to do is to put as much logic as possible in SQL, and have the Python/django layer just be a nice web interface on top of that. The REST API is another one, the tsv backups too, etc.

**Comment by nsteinme** [comment]
I think we're going to find it to be a huge headache to write that kind of
logic in SQL though, don't you think? Anyway, if you want to give it a try,
that sounds great!

**Comment by rossant** [comment]
I don't know, I'll try and see...

**Comment by rossant** [comment]
See https://github.com/cortex-lab/alyx/commit/98fd60ee912eaca207ce1d538885ad6699ecb3bd#diff-a62bd3af6c786754e9a2f642ca7d1cd5R695
Now you should be able to add your own custom views. The idea is to derive an existing ModelAdmin class, customize it, and register it.

**Comment by kdharris101** [comment]
Cyrille, to clarify:

Does this mean that you can create an arbitrary SQL view, and Django will treat it like a real table?

And does that also allow updating as well as reading?

Even adding new rows? (don’t see how this could be possible actually)

**Comment by rossant** [comment]
No, it's really just a way to create different list/add/change views for a given model. The default list view, named "Subjects" shows columns A, B, C. We can create another list view, named "Subjects bis", which shows columns A, C, D, for example. We can have different filtering options, ordering, etc. The query is not written in SQL directly. You just specify the list of columns, and you can add custom columns using Python. The SQL query is automatically generated under the hood.

**Comment by kdharris101** [comment]
Thanks, I see. So I guess it won’t work with table joins?

**Comment by rossant** [comment]
yes it works with table joins, in the subjects list you can do something like `line__name` to display the name of each subject's line. It works with arbitrarily complex queries, but they are typically expressed in python/django, not SQL (although I suppose it would be possible to write raw SQL but it's not a common scenario)

**Comment by kdharris101** [comment]
Great!

**Comment by nsteinme** [comment]
Looks excellent! Could you add two more things to this example
implementation (both because they would be good to have here, and so I can
do it in the future for others myself using the example):
1) a filter - in this case a good example would be to filter by
responsible_user
2) a link - make the line link to the line page

Also I didn't understand something - you said you should do `line__name` to
display the name of the subject's line - but actually in the code you just
have `line`, and yet it does display the name not the uuid, anyway. Why did
that happen?

**Comment by rossant** [comment]
> Also I didn't understand something - you said you should do `line__name` to
> display the name of the subject's line - but actually in the code you just
> have `line`, and yet it does display the name not the uuid, anyway. Why did
> that happen?

When you specify an *object* (like `line`) instead of a *string*, it will call the `__str__()` method of the object, here https://github.com/cortex-lab/alyx/blob/master/alyx/subjects/models.py#L349

**Comment by rossant** [comment]
[done](https://github.com/cortex-lab/alyx/commit/20f8b06c5febcbcbb79cfa05309da3ba6c04fd8e)
