### ISSUE TITLE
new field for subject: Protocol number

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#115]
We had talked about having it as a json element, but instead let's please add it as a true field - just to grease adoption here, which is going to need all the greasing it can get. It can only take four values: {'1', '2', '3', or '4'}. Sorry @rossant, the home office doesn't do zero-indexing ;) 

On the subject page it should go under Ear Mark and before Notes.

**Comment by nsteinme** [comment]
And it should auto-fill to 3 for every mouse (amusingly, I don't think anyone does protocols 1,2, and 4 anymore)

**Comment by rossant** [comment]
done
