### ISSUE TITLE
Reimplement Python properties in SQL views 

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#117]
https://blog.rescale.com/using-database-views-in-django-orm/

**Comment by rossant** [comment]
@nsteinme continuing the discussion here. I see that we can write PL/pgSQL procedures but it's obviously more limited than Python. Actually I'm wondering: why do you want to see these virtual fields in the tsv backup? If it's a backup, it doesn't need information that can be directly computed from the data..? If you want an alternative interface that shows you this information, maybe what you want is to use Python or the REST API so we wouldn't need to have the logic in SQL?

**Comment by nsteinme** [comment]
Well I thought we should see it in the backup for the purpose of convincing
Matteo that everything's there. That is not a strong reason, so once I
found out it's hard to do we could have just dropped it. However what
I *do* need
is to be able to access water_requirement_total/remaining from matlab, and
we need to have the "adverse effects view". So this approach would
hypothetically solve both of these problems I think. They are the main
motivation. If we want to go back to working on other ideas for those (rest
api for the former, proxy model for the latter) then that is fine!

**Comment by rossant** [comment]
Apparently one can write Python procedures in postgresql... https://www.postgresql.org/docs/9.6/static/plpython.html

**Comment by rossant** [comment]
> Apparently one can write Python procedures in postgresql...

but no in MySQL as far as I can tell

**Comment by rossant** [comment]
@kdharris101 @nsteinme was there a reason to choose postgresql over mysql originally?

**Comment by kdharris101** [comment]
I think it was the JSON support – but MySQL also has json now

https://dev.mysql.com/doc/refman/5.7/en/json.html

@nippoo, were there any other reasons?

**Comment by nsteinme** [comment]
I don't know others - it's a question for max.

**Comment by rossant** [comment]
I think that may end up being unnecessary, and probably even harder with MySQL than with postgresql. Closing for now.
