### ISSUE TITLE
Add some fields in the subjects tsv backup?

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#121]
We could try to add some columns to the subject tsv backup, using pure SQL:

* reference_weighing
* current_weighing
* water_restriction_date

If we can get that to work, then we can add water requirements to the backup, notably the Google Sheets backup.

**Comment by nsteinme** [comment]
To clarify, you would then put the water requirements in the backup by
putting the formula into the google sheet? So that with SQL we just need to
be doing these searches for the three fields you list, but not doing the
actual computation of the mouse's weight Z score and all that?

**Comment by rossant** [comment]
Yes, the TSV backup would just contain those three fields. Then, in a subsequent step, a Python script loads the backup, add new columns using the same Python functions that are used in the admin interface to compute the water requirements, and adds these new values to the Google Sheets backup. In addition we can also overwrite the TSV backups to add these new fields, but if the Python script fails for some reason, the TSV backups might end up being corrupted...

**Comment by nsteinme** [comment]
No I think it's a good idea for the tsv ones to be a bit more "raw". Ok,
I'll try to work on this.

**Comment by rossant** [comment]
not sure we need this, please feel free to reopen if you'd like
