### ISSUE TITLE
Give examples of complex queries

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#126]
@kdharris101 @nsteinme Could you give specific examples of complex queries that you would like to run on the database eventually? We could compare how one would write these queries with (1) SQL, (2) DataJoint, (3) possibly the REST API.

**Comment by nsteinme** [comment]
- Return all deriving from BaseExperimentModel for a given subject on a given date with a given "expNum" value (that's a JSON field)

- Return all ExtracellularRecordings that happened in subjects from a certain Line for which: 1) The associated Experiment also has an EventSeries of a certain type (let's say a certain json tag) associated with it; and, 2) There is a PupilTracking model in that Experiment; and 3) there were recording sites in a certain brain region (somehow this is a query on the ExtracellularRecording's probe_location_id field, not sure how it works yet). This query is what Laura Busse described using to pick out the data from her lab that she sent to Aman recently as part of a collaboration. It's probably worth asking her exactly what that query ended up looking like in datajoint. In the rest API and/or SQL I imagine I'd do it in pieces: first get all the subjects from the line, then get all experiments from just those subjects, then see which experiments have the required BaseExperimentModels (Ext.Rec., Pup.Track., etc), then check the probe_locations of those...
