### ISSUE TITLE
Read from LAMIS, especially cages

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#128]
Since BSU already keeps track of cages/cage movements, it would be ideal to take advantage of this automatically.

**Comment by rossant** [comment]
Who should this issue be assigned to? I'm not sure I understand what this is about. :)

**Comment by nsteinme** [comment]
Max. But it's a longer-term objective. LAMIS is the database system that
UCL uses for mouse colonies, but unfortunately it's not clear we can have
any read-access to it in any direct way (we can go to a website and see
stuff).
