### ISSUE TITLE
Forms for common workflows

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#129]
In the medium-term, it would be great to have forms for common workflows. E.g.:

- [ ] "Take mouse from stock" - user chooses a line, then picks a mouse from that line, types in a new name for the mouse. Alyx automatically creates a new cage with that subject's name and assigns its location to BSU 4.09. 
- [x] "Cull mice" - user chooses a line then clicks on each mouse to cull. All get death dates of today.

**Comment by rossant** [comment]
For the "Cull mice" workflow, would something like this work? This is a new "Cull subjects" item in the Common category on the index page. You filter by the line, then click on "today" on every subject, then "Save".

![image](https://cloud.githubusercontent.com/assets/1942359/23663060/c4c5d3b4-0351-11e7-8358-c76243a83c26.png)

**Comment by nsteinme** [comment]
Great! Also filter by user.

**Comment by rossant** [comment]
@nsteinme closing this. I haven't done the first proposition yet, however I think it may have to be a bit different now that we no longer have cages? Feel free to open a new issue for that one.

**Comment by nsteinme** [comment]
Yeah, agreed, will open a new issue for any other specific "forms" that
Charu needs.
