### ISSUE TITLE
Session page automatically fills with inline for each exp-metadata

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#130]
This is for any exp-data associated with that experiment. The inline should show the type of the exp-metadata, the start and end time, and a notes field. Only the notes field is editable.

**Comment by rossant** [comment]
What are exp-data and exp-metadata exactly?

**Comment by nsteinme** [comment]
I meant exp-metadata in both cases. It's the base class for all datasets, see http://alyx.cortexlab.net/, there is an "exp-metadata" endpoint. E.g. extracellular recording is an exp-metadata instance, a movie of the eye is, etc.

**Comment by rossant** [comment]
So if I understand correctly, you're talking about `/admin/actions/experiment/change/`, you would like to see as inlines a list of all models deriving from `BaseExperimentalData` related to the current experiment?

**Comment by nsteinme** [comment]
Yes! That's it. To be clear, it's /admin/actions/experiment/[UUID]/change

**Comment by rossant** [comment]
Models deriving from BaseExperimentalData have no start_time, end_time, or notes fields, right?
To display all related models deriving from this abstract class, we have to generate one category of inline per type of exp-metadata (15 at the moment).

**Comment by nsteinme** [comment]
Actually it would be better if they did! @nippoo what do you think, are
there types of BaseExperimentalData that *should not* have start, end,
notes?
