### ISSUE TITLE
Subject history

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#131]
One row for each thing: 
- Surgery
- Sessions, with summary of exp-metadatas
- Culling

Probably want to make each of these into a string and display just all the strings, but as links to the relevant objects.

**Comment by rossant** [comment]
The list of surgeries is already displayed as an inline form, should it stay or should it be replaced by this?

**Comment by nsteinme** [comment]
Well the inlines are useful but more for editing than for viewing - as you
can see it's hard to read information easily from them. If you can have
both, that would be cool! The other option is to drop the edit-able inlines
from the subject page altogether and just have a link to make a new one of
each of those things, plus a list of the existing ones. What do you think?

**Comment by rossant** [comment]
I think both are possible so it is really up to you and other end-users... I agree that having everything editable is kind of heavy. On the other hand, just having links is yet one more click. I don't know which is more desirable for people who will interact with this everyday.

**Comment by rossant** [comment]
new page with, in chronological order, everything that happened to a subject (session, surgery, actions, weighings, etc)

from @oliche :

```
from django.urls import reverse
from django.db.models.deletion import Collector


from actions.models import BaseAction, Session, Weighing, WaterRestriction
from subjects.models import Subject
subject_name = 'ZM_346'


sub = Subject.objects.get(nickname=subject_name)


collector = Collector(using="default")
collector.collect([sub])

for model, instance in collector.instances_with_model():
    more_stuff = {}
    dnames = []
    if model._meta.app_label == 'data':
        continue
    if not isinstance(instance, BaseAction):
        continue
    ginstance = instance
    url = reverse('admin:%s_%s_change' % (instance._meta.app_label,
                                          instance._meta.model_name), args=[instance.id])
    if isinstance(instance, Session):
        dnames = ['n_correct_trials', 'n_trials']
    if isinstance(instance, Weighing):
        dnames = ['weight']
    if isinstance(instance, WaterRestriction):
        dnames = ['water_type__name']
    for n in dnames:
        more_stuff[n] = model.objects.filter(pk=instance.pk).values_list(n, flat=True)[0]

    print(instance, instance.start_time, url, more_stuff)
```

**Comment by oliche** [comment]
Need to add this to the REST API through a new endpoint or through the /subject endpoint
