### ISSUE TITLE
subjects sort oddly

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#133]
I see this: 

![image](https://cloud.githubusercontent.com/assets/7590975/23656269/e4ca449a-0330-11e7-992f-9530ffe9b05c.png)

Is there a way to get them to sort properly? It doesn't work to sort by Nickname because it goes: xx_1, xx_10, xx_11, ... xx_19, xx_2, xx_20, etc. I'm not sure what the best solution is here. If birth date had a time of day, you could create them with different times of day in order, as a hacky solution.

**Comment by rossant** [comment]
Among all subjects with the same birth date, you want to sort by increasing (or decreasing?) postfix number (46, 47, etc.), right?

**Comment by nsteinme** [comment]
Yep

**Comment by rossant** [comment]
I can't find a good solution for this :/ @nippoo ?
@nsteinme you're sure you don't want to have _001-like postfixes?

**Comment by nippoo** [comment]
https://en.wikipedia.org/wiki/Natural_sort_order

https://pypi.python.org/pypi/django-naturalsortfield/0.7

**Comment by nippoo** [comment]
but yes I'd much prefer @rossant's solution of 049, 050 rather than 49, 50 etc

**Comment by nsteinme** [comment]
I vote strongly against the 0001-type thing because these are numbers that
have to get written on cages. No one wants to go around writing zeros all
the time. Plus this retains consistency with existing names; Charu will be
annoyed if we don't.

Here's another solution, which is that each Subject could actually have a
field within it called "line_index" which stores its number, and the
nickname is created from the line and line_index. Then you sort by
line_index.

Can you just define a custom sort function on a column, that makes a number
from everything after an underscore then sorts?

**Comment by rossant** [comment]
> Can you just define a custom sort function on a column, that makes a number
> from everything after an underscore then sorts?

I tried that, but the function cannot be written in Python, it has to be written in SQL and I don't know if that's possible.

**Comment by nsteinme** [comment]
So what about making the birth date include precision out to milliseconds
or something and offsetting them? This seems a bit silly, it must be a
solved problem! The padding zeros aren't good because A) they aren't nearly
as readable; B) you have to guess how many zeros to pad with, and if you
guess wrong you get this same problem all over again once you exceed it....
if we can do a custom sort in SQL we could define a totally hidden "sort
order" field and sort by that.

**Comment by nsteinme** [comment]
I wish I could just say let's ignore it but it's the kind of stupid thing
that will really frustrate Charu, and to be honest it is quite confusing.

**Comment by nsteinme** [comment]
Hey Cyrille, I think I have an SQL query that'll do it. Can you implement this as the sort function for the nickname column? 

```
select nickname from subjects_subject 
left join subjects_line on subjects_subject.line_id=subjects_line.id 
where subjects_line.auto_name in ('TetO.CtTa')
order by substring(nickname from '#_#"%#"')

```
If you already have nicknames selected I guess you can skip the line autoname part. The main thing is the last bit, the order by. The substring function is doing a kind of regular expressions thing. # is the escape character and _ is a special character so #_ says to look for the underscore in the nickname. Then #" is the marker of what you want to return, and % is any number of characters, so #"%#" says return anything after the underscore. It seems to work for me, I got the below for this query on alyx.cortexlab.net, which is correct. Could you try it? See [here](https://www.postgresql.org/docs/9.2/static/functions-matching.html) for more about this function. 


```
    'FriendlyFriend' 
    'LittleFriend'   
    'TetO.CtTa_IoO39'
    'TetO.CtTa_IoO40'
    'TetO.CtTa_IoO41'
    'TetO.CtTa_IoO42'
    'TetO.CtTa_IoO43'
    'TetO.CtTa_IoO44'
    'TetO.CtTa_IoO45'
    'TetO.CtTa_IoO46'
    'TetO.CtTa_IoO47'
    'TetO.CtTa_IoO48'
    'TetO.CtTa_IoO49'
    'TetO.CtTa_IoO50'
    'TetO.CtTa_IoO51'
    'TetO.CtTa_IoO52'
    'TetO.CtTa_IoO53'
    'TetO.CtTa_IoO54'
    'TetO.CtTa_IoO55'
    'TetO.CtTa_IoO56'
    'TetO.CtTa_IoO64'
    'TetO.CtTa_IoO65'
    'TetO.CtTa_IoO66'
    'TetO.CtTa_IoO67'
    'TetO.CtTa_IoO68'
    'TetO.CtTa_IoO69'
    'TetO.CtTa_IoO70'
    'TetO.CtTa_IoO71'
    'TetO.CtTa_IoO72'
    'TetO.CtTa_IoO73'
    'TetO.CtTa_IoO74'
    'TetO.CtTa_IoO75'
    'TetO.CtTa_1'    
    'TetO.CtTa_2'    
    'TetO.CtTa_3'    
    'TetO.CtTa_4'    
    'TetO.CtTa_5'    
    'TetO.CtTa_6'    
    'TetO.CtTa_7'    
    'TetO.CtTa_8'    
    'TetO.CtTa_9'    
    'TetO.CtTa_10'   
    'TetO.CtTa_11'   
    'TetO.CtTa_12'   
    'TetO.CtTa_13'   
    'TetO.CtTa_14'   
    'TetO.CtTa_15'   
    'TetO.CtTa_16'   
    'TetO.CtTa_17'   
    'TetO.CtTa_18'   
    'TetO.CtTa_19'   
    'TetO.CtTa_20'   
    'TetO.CtTa_21'   
    'TetO.CtTa_22'   
    'TetO.CtTa_23'   
    'TetO.CtTa_24'   
    'TetO.CtTa_25'   
    'TetO.CtTa_26'   
    'TetO.CtTa_27'   
    'TetO.CtTa_28'   
    'TetO.CtTa_30'   
    'TetO.CtTa_31'   
    'TetO.CtTa_32'   
    'TetO.CtTa_33'   
    'TetO.CtTa_34'   
    'TetO.CtTa_36'   
    'TetO.CtTa_37'   
    'TetO.CtTa_38'   
    'TetO.CtTa_39'   
    'TetO.CtTa_40'   
    'TetO.CtTa_41'   
    'TetO.CtTa_42'   
    'TetO.CtTa_43'   
    'TetO.CtTa_44'   
    'TetO.CtTa_45'   
    'TetO.CtTa_46'   
    'TetO.CtTa_47'   
    'TetO.CtTa_48'   
    'TetO.CtTa_49'   
    'TetO.CtTa_50'   
    'TetO.CtTa_51'   
    'TetO.CtTa_52'   
    'TetO.CtTa_53'   
    'TetO.CtTa_54'   
    'TetO.CtTa_55'   
    'TetO.CtTa_56'   
    'TetO.CtTa_57'   
    'TetO.CtTa_58'   
    'TetO.CtTa_59'   

```

**Comment by nsteinme** [comment]
Hm, it is possible that this is failing to match anything (because, who knows why), returning null for every nickname, and thus returning the default sort order. Default sort order is something like sorting by modified time, I guess? Maybe that is just what we want? Or maybe there is some way to get this regular expression correct? I'm not experienced at these. :/

**Comment by nsteinme** [comment]
Actually I think I am maybe right. See here:  http://sqlfiddle.com/#!15/eb0e2/2/0

**Comment by nsteinme** [comment]
Ok, possibly I have figured out the correct way to do it: 

`to_number(substring(summary from '%#_#"%#"' for '#'),'9999')`

http://sqlfiddle.com/#!15/de822/20

**Comment by rossant** [comment]
It's tricky. :/ I manage to do it in SQL but it's not easy to integrate it in django. I found basically two solutions.

1. Use 0-padded numbers internally the database, and make it such that, when you use the software, you always see the natural version without zeros. The only drawback is that you'll see the zeros when you'll interact with SQL directly. Confusing...

2. Customize the ordering manually in every situation where you see a list of subjects (subject page, dropdown menus, etc). I didn't manage to make is such that the default ordering is always the natural ordering. We have to find every situation in the software where you want natural ordering, and overwrite the appropriate methods. And we have to do this for all models for which you want natural ordering.

**Comment by nsteinme** [comment]
All right :( Let's switch to zero-padding then and see how it goes. Three
digits, so subjects are like Ai32_081 etc.

**Comment by rossant** [comment]
There might be another option. We remove the "nickname" field and we create two new fields:

* nickname_base: str
* nickname_suffix: int or null

The displayed nickname is the concatenation of both with a `_` between. The default ordering is `['nickname_base', 'nickname_suffix']`. The autonaming will work as before: the nickname will be the autoname, and the suffix will increase. If you want to rename a subject, you rename the `nickname_base` and you get rid of the suffix.

I think this is the cleanest solution, but there might be drawbacks I didn't think about...

**Comment by nsteinme** [comment]
Sounds nice but isn't there a problem in that many mice would have
identical nicknames? All the Camk2a-tTa mice would have the nickname_base
of "CtTa" with different suffixes, and so it wouldn't work as a slug field
anymore. Or you could keep the existing nickname slugfield but make it
read-only and always reflect this concatenation?

**Comment by rossant** [comment]
The nickname_base won't be unique anymore, but the combination of the two fields will. We'll keep the existing nickname slugfield read-only as you say.

**Comment by nsteinme** [comment]
@nippoo what do you think about this?

Here's a variation. Each subject has a read-only nickname and a
"user_nickname" field, and also a "line_index" (or something) field. When
user_nickname is empty, nickname is the Line Autoname concatenated with
line_index. When user_nickname isn't empty, the nickname is user_nickname.
This way you more explicitly keep the line_index around (a small bonus) but
more importantly clarify what a user should do when he/she wants to assign
a nickname (i.e. they don't have to delete this number anymore, or worry
about what "base" means).

There is a problem with this version that's possibly fatal: if a subject
switches lines, which can happen, then its nickname would switch and it
would possibly conflict with another subject.

**Comment by nippoo** [comment]
So as I suggested to @nsteinme - the way I'd approach this might be:

- create a function within the `Subject` class along the lines of

```
def trailing_integer(self):
'''Returns the last integer delimited by an underscore, i.e. foobar_1033-294_10 will return 10'''
    trailing_num = re.findall('^.*_([0-9]+)$', self.nickname)[0]
    if trailing_num:
        return int(trailing_num)
    else
       return None
```

Then you can just display this as a column and 'sort by'?

**Comment by nippoo** [comment]
Storing three parts to a nickname in the database seems like a violation of good Separation of Concerns...

**Comment by rossant** [comment]
* I don't know if django can sort by custom read-only fields?
* If there is A_1, A_2, B_1, won't this sort as A1, B_1, A_2?

**Comment by nippoo** [comment]
- Yup, it's possible: http://stackoverflow.com/questions/15760082/django-admin-how-to-sort-column-by-custom-method

- Good point - but you could still do this by having two custom methods to split into base_name and trailing_integer, since the admin interface supports multiple ordering (i.e. order first by base_name, second by trailing_integer). 

- Or just write a function that pads it with a fixed number of zeros and use this as the `ordering_padded_nickname`.

Either way I'm somewhat opposed to making this into a database issue - this is a visualisation problem and shouldn't be dragged down into the SQL level!

(I still think we should just go with zero-padded names and deal with it... standardise to four digits? Automatically pad when you enter them?)

**Comment by rossant** [comment]
> I still think we should just go with zero-padded names and deal with it... standardise to four digits? Automatically pad when you enter them?

We can easily make it such that writing the 0s in alyx or on the cages is always optional... There is a 1-to-1 correspondance between padded and non-padded...

**Comment by rossant** [comment]
OK I've changed the autonaming thing to pad with zeros. Are there other things to do?

* Automatically zero-pad when user manually enters "subj_1"?
* Zero-pad the items that are already autonamed in the google sheets, and which are not zero-padded at the moment?

**Comment by nsteinme** [comment]
It would definitely be great if you can zero-pad the imported ones, so I
don't have to go back through those.

But I think the idea is that people won't be manually writing names that
follow this numbering scheme - those will all be auto-generated based on
the Line Indices. We don't really want them generating those names, right?

**Comment by rossant** [comment]
OK, done! I just enabled padding everywhere... So I guess users may handwrite autonames but they will never write them in the database or in any text document that will be read by a software? In that case, they can just drop the zeros...

And it's one line of Python to pad a non-padded name anyway.
