### ISSUE TITLE
trial zygosities rule

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#135]
What we'd like to have is a way to convert the genotype tests into zygosities in a rule-based way. The rule depends on the line. E.g. for Camk2a-tTa, it is simple:
if Genotype tTA=+ then zygosity Camk2a is Present (+/)
if Genotype tTA=- then zygosity Camk2a is Absent (-/-)

For others it's more complicated, because there are two tests done and together they determine whether it is het or homo. 

First question is, can the database automatically fill in the zygosities based on the genotype tests like this, in some useful way? Like, every time a genotype test is added or updated, you re-run the "calculation" to determine what the zygosity should be? But zygosity shouldn't become read-only because there are other ways than genotype tests to determine the zygosity.  

Second question is, how shall I record all these conversions? I can literally just write them all in a reply to this issue. Or I could put them in the google sheets in some way, e.g. I can make a new sheet that lists them all in a standardized way.

**Comment by nippoo** [comment]
Yep, these can go in the `save()` method. Maybe just write them here?

We should make sure this isn't dealt with in the admin interface though, this needs to go on the model so any hits to the API also generate it the right zygosities.

**Comment by nippoo** [comment]
Should the genotype be read-only? Or should the user be able to change it? If so, will/should it be overwritten every time somebody changes the genotype tests, or only if it's blank?

**Comment by rossant** [comment]
Yes we can implement this logic in `Model.save()`.

@nsteinme maybe write a Python function that takes a list of `GenotypeTest` instances and returns a `Zygosity` instance? and post it here if you want.

**Comment by nsteinme** [comment]
Can you give me a template of such a function? I'm not sure for instance
what fields a genotypetest instance would have or how to make a zygosity
instance. Can you make the one for camk2a that I described above?

Max I think you mean should zygosity be read-only. It should not, because
there are other ways you can figure out the zygosities. Good question about
overwriting - I think if it's not blank you shouldn't overwrite.

**Comment by rossant** [comment]
You can use this template:

```python
if self.get_genotype_test('tTa'):  # returns 0 or 1
    # the symbol is one of '-/-', '+/-', '+/+', '+'
    self.add_zygosity('Camk2a', '+')
else:
    self.add_zygosity('Camk2a', '-/-')
```

**Comment by nsteinme** [comment]
Ok, here are some of them, below. Btw first I give the list of all alleles
in the lab (I think!). Maybe we could add those, change all users to Staff,
and make a new static_dumped? How should we think about making updates to
static_dumped?

Also, totally sorry about my probably-busted python.

allelesToAdd = ['Ai32-ChR2', 'DAT-Cre', 'Drd1a-Cre', 'Emx1-Cre', 'Gad-Cre',
'KHA1-KO', 'Ai95-G6f', 'Ntsr1-Cre', 'Pv-Cre', 'Sst-Cre', 'Snap26-G6s',
'TetO-G6s', 'TdTom-Cre', 'Thy18', 'Vip-Cre', 'Vglut1-Cre', 'Ai78-VSFP',
'Ai93-G6f', 'Ai94-G6s', 'Ai148-G6f', 'Rasgrf-Cre', 'Camk2a-tTa'];

if self.line.autoname == 'CtTa': # I'm not sure how you're handling the
different rules for different lines, but here's a stab at it
    if self.get_genotype_test('tTA'):  # returns 0 or 1
        # the symbol is one of '-/-', '+/-', '+/+', '+'
        self.add_zygosity('Camk2a-tTa', '+')
    else:
        self.add_zygosity('Camk2a-tTa', '-/-')

elif self.line.autoname == 'Pv':
    if self.get_genotype_test('Cre') && self.get_genotype_test('WT'):

        self.add_zygosity('Pv-Cre', '+/-')
    elif self.get_genotype_test('Cre') && ~self.get_genotype_test('WT'):
        self.add_zygosity('Pv-Cre', '+/+')
    else:
        self.add_zygosity('Pv-Cre', '-/-')
        #what about the case when one or both tests is null, i.e. test
hasn't been entered yet?

elif self.line.autoname == 'TetO':
    if self.get_genotype_test('TRE') && self.get_genotype_test('WT'):

        self.add_zygosity('TetO-G6s', '+/-')
    elif self.get_genotype_test('TRE') && ~self.get_genotype_test('WT'):
        self.add_zygosity('TetO-G6s', '+/+')
    else:
        self.add_zygosity('TetO-G6s', '-/-')

elif self.line.autoname == 'TetO.CtTa':
    if self.get_genotype_test('TRE'):
        self.add_zygosity('TetO-G6s', '+/-')
    else:
        self.add_zygosity('TetO-G6s', '-/-')

    if self.get_genotype_test('tTA'):
        self.add_zygosity('Camk2a-tTa', '+/-')
    else:
        self.add_zygosity('Camk2a-tTa', '-/-')

**Comment by rossant** [comment]
Thanks! I'll have a look tomorrow.
For the static JSON feel free to edit it by hand if there aren't too many things to add, it should be pretty straightforward. Don't add/change permissions in there though, we'll take care of that separately.

**Comment by nsteinme** [comment]
Can I instead edit the static tables on the admin interface, then create a new static_dumped? Were there lots of manual changes you had to make to get a working static_dumped? Unfortunately I didn't have the final version of all the static tables when we made that one, and it'd be a lot easier to edit most of it with the admin interface.

**Comment by rossant** [comment]
Sure

**Comment by rossant** [comment]
Your code works but there may be a problem when tests are absent... In this case nothing should be done, right?

Here's an alternative syntax to express the rules. I don't know if it will always be sufficient, or if there are rules that are more complex than what can be expressed with this syntax?

```python

[
('CtTa', 'Camk2a-tTa', [('tTA', '+'), 
                        ('-tTA', '-/-')]),

('Pv', 'Pv-Cre', [('Cre,WT', '+/-'), 
                  ('Cre,-WT', '+/+'), 
                  ('-Cre', '-/-')]),

('TetO', 'TetO-G6s', [('TRE,WT', '+/-'), 
                      ('TRE,-WT', '+/+'), 
                      ('-TRE', '-/-')]),

('TetO.CtTa', 'TetO-G6s', [('TRE', '+/-'), 
                           ('-TRE', '-/-')]),

('TetO.CtTa', 'Camk2a-tTa', [('tTA', '+/-'), 
                             ('-tTA', '-/-')]),
]
```

Each item has three elements: the line, the allele, a list of rules.

Each rule is a pair: the test(s) as a string of comma-separated test names, with a minus when the test is negative, and the outcome. If no rule is satisfied, nothing is done.

**Comment by nsteinme** [comment]
Yes if not all tests are present then nothing should be done. I'll ask
Charu/Laura to explain to me the rules for the different lines and figure
out whether there is anything more complicated than that (but I doubt there
is). If there isn't, is it working with these examples, or we have good
faith that it will work? If so I'll go ahead and write all the rules in
this format. Thanks!

**Comment by rossant** [comment]
Let me just implement the lines you've already done to check that it works, and I'll let you know if you can go ahead with the other rules.

**Comment by rossant** [comment]
The format of the rules is ok so you can go ahead.

However it's a bit tricky to make this happen automatically, especially if you want to be able "manually override" the genotype. In what conditions should the program fill the genotype, in what conditions should it do nothing and let the user specify the genotype? There is no easy way to find out whether the user just specified a genotype manually. I can see many silent bugs arising from trying to being too smart...

An alternative is to just display a read-only field called "expected genotype" or whatever, with the genotype expected from the genotype tests. Then, you're free to set the genotype yourself.

**Comment by nsteinme** [comment]
Ok, let me discuss with Kenneth. I do see that this is tricky :/

**Comment by nsteinme** [comment]
Ok, discussed with Max, here's what we want. Zygosities are read only. They update when you change a genotype test for a subject, as discussed above, but also when the subject is given a litter. When given a litter, the zygosities are calculated according to the rules below. When given a litter OR a genotype test, the new calculation overrides any existing ones (but calculations are on a per-allele basis - would only override the affected allele, not all alleles). If both happen simultaneously, certainly hope they don't disagree but in any case genotype test rules take precedence. 

For each allele that at least one parent has:
- if parents both have allele, and both are +/+ then subject gets +/+ for that allele
- parents both have allele, one is +/+ => +
- parents both have allele, both -/- => -/-
- one parent has allele, is +/+ => +/-
- one parent has allele, is -/- => -/-
Other situations (i.e. when one or both parents is +/-) do not make any changes to the subject's zygosities.

**Comment by nsteinme** [comment]
I think this is all of them. @nippoo want to look over this? Probably I just need to go over it with Charu. 

```python
( # note that some of the sequence names have spaces and even hyphens, sorry

('N.KHA', 'Ntsr1-Cre', (('Cre', '+/-'), # need to check on this one too. 
                             ('-Cre', '-/-'))),

('Thy18.Pv', 'Thy18-ChR2', (('YFP', '+'), 
                        ('-YFP', '-/-'))),

('RCL.Vg', 'Ai95-G6f', (('GFP', '+/-'), 
                           ('-GFP', '-/-'))),

('RCL.Vg', 'Vglut1-Cre', (('Cre', '+/-'), 
                             ('-Cre', '-/-'))),

('Ai78.CtTa', 'Camk2a-tTa', (('tTA', '+/-'), 
                             ('-tTA', '-/-'))),

('Ai78.CtTa', 'Ai78-VSFP', (('VSFP', '+/-'), # I think I need to ask about this one...
                           ('-VSFP', '-/-'))),

('Vip', 'Vip-Cre', (('Cre,Vip WT', '+/-'), 
                  ('Cre,-Vip WT', '+/+'), 
                  ('-Cre', '-/-'))),

('Vg', 'Vglut1-Cre', (('Cre,WT', '+/-'), 
                  ('Cre,-WT', '+/+'), 
                  ('-Cre', '-/-'))),

('Thy18', 'Thy18-ChR2', (('YFP', '+'), 
                        ('-YFP', '-/-'))),

('TdTom', 'TdTom-RFP', (('tdRFP,ROSA WT', '+/-'), 
                  ('tdRFP,-ROSA WT', '+/+'), 
                  ('-tdRFP', '-/-'))),

('Sst', 'Sst-Cre', (('Cre,Sst WT', '+/-'),  
                  ('Cre,-Sst WT', '+/+'), 
                  ('-Cre', '-/-'))),

('Snap', 'Snap25-G6s', (('GFP,WT', '+/-'), # note I think spreadsheet has a typo here, currently has Cre and Sst WT, but I think it should be these
                  ('GFP,-WT', '+/+'), 
                  ('-GFP', '-/-'))),

('RCL', 'Ai95-G6f', (('eGFP,WT', '+/-'), 
                  ('eGFP,-WT', '+/+'), 
                  ('-eGFP', '-/-'))),

('Rasgrf', 'Rasgrf-Cre', (('Rasgrf Cre,Rasgrf WT', '+/-'), 
                  ('Rasgrf Cre,-Rasgrf WT', '+/+'), 
                  ('-Rasgrf Cre', '-/-'))),

('KHA', 'KHA1-KO', (('Vglut1 MD,Vglut1 WT', '+/-'), #  fwiw it is intentional that the logic is inverted here relative to usual
                  ('Vglut1 MD,-Vglut1 WT', '-/-'), 
                  ('-Vglut1 MD', '+/+'))),

('Gad', 'Gad-Cre', (('Cre,WT', '+/-'), 
                  ('Cre,-WT', '+/+'), 
                  ('-Cre', '-/-'))),

('CtTa', 'Camk2a-tTa', (('tTA', '+'), 
                        ('-tTA', '-/-'))),

('Pv', 'Pv-Cre', (('Cre,WT', '+/-'), 
                  ('Cre,-WT', '+/+'), 
                  ('-Cre', '-/-'))),

('TetO', 'TetO-G6s', (('TRE,WT', '+/-'), 
                      ('TRE,-WT', '+/+'), 
                      ('-TRE', '-/-'))),

('TetO.CtTa', 'TetO-G6s', (('TRE', '+/-'), 
                           ('-TRE', '-/-'))),

('TetO.CtTa', 'Camk2a-tTa', (('tTA', '+/-'), 
                             ('-tTA', '-/-'))),
							 
('Ai32', 'Ai32-ChR2', (('ChR2-YFP,WT', '+/-'), # this sequence has a hyphen in it, beware, sorry
                      ('ChR2-YFP,-WT', '+/+'), 
                      ('-ChR2-YFP', '-/-'))),	

('DA', 'DAT-Cre', (('Cre,WT', '+/-'), 
                  ('Cre,-WT', '+/+'), 
                  ('-Cre', '-/-'))),					  

('Drd', 'Drd1a-Cre', (('Cre,WT', '+/-'), 
                  ('Cre,-WT', '+/+'), 
                  ('-Cre', '-/-'))),	

('Emx', 'Emx1-Cre', (('Cre,WT', '+/-'), 
                  ('Cre,-WT', '+/+'), 
                  ('-Cre', '-/-'))),	
				  
)
```

**Comment by rossant** [comment]
done
