### ISSUE TITLE
subjects API view doesn't work

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/alyx#136]
currently it's 

`/subjects/[NICKNAME]`

so `[NICKNAME]` should be a SlugField

Now it's not a SlugField then this breaks whenever there's a mouse with a special character... 

So either we change it to `/subjects/[UUID]`, or we change `[NICKNAME]` back to a SlugField, or we have a separate SlugName which we generate from the nickname.

**Comment by nsteinme** [comment]
Are you sure that a mouse with a weird name is the problem? I don't think
that's actually true - if it's true, which mouse is it? Right now even
though it's not a slugfield, they actually are all compatible since we went
with dot rather than semicolon.

**Comment by nsteinme** [comment]
Just noting that this is still broken, error message below. I looked through all the subjects' nicknames and indeed a couple had open/close parens. However, manually updating them didn't resolve anything. Is the Line Name also supposed to be a slug field maybe? Is there a way to "cast" to a slug field, or sanitize our slug fields, or maybe just report on import which things are not good for slugs?

![image](https://cloud.githubusercontent.com/assets/7590975/23824604/6759a8ea-0671-11e7-8307-5d9d25f768a1.png)
