### ISSUE TITLE
permissions groups

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/alyx#138]
we should figure out for both API and admin interface: who can add what, who can edit which things, add/delete/edit things, creating user groups.

**Comment by rossant** [comment]
Or do we just put everyone as superuser?

**Comment by nippoo** [comment]
if we can get django-reversion working then yes, very possibly.

that said, we should hide things that 1) aren't used yet or 2) probably don't need to change and might break spectacularly if they do (i.e. people shouldn't be able to edit the list of species, probably...) just to clean up the admin interface

**Comment by nsteinme** [comment]
Maybe let's not hide them just yet since there still needs to be some
manual entry of these (e.g. strain).
