### ISSUE TITLE
litters should be associated with cages (they need a cage field like subjects have)

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#14]
The purpose of this is that you should be able to add a litter to a cage, so that the litter can auto-fill mother, father, and line. If you can have a button at the cage page that is like "create litter" but doesn't need the litter to be _in_ that cage, then that would be fine too. But the mice you add to the litter will need to be in the cage also (and this information should also auto-fill) so I think it makes most sense to just make the litter have a cage.

**Comment by rossant** [comment]
Done.
