### ISSUE TITLE
When creating a new cage from subject page, auto-fill the Line of the cage to match the subject's line

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#140]

**Comment by rossant** [comment]
how do you create a new cage from subject page? by clicking on the green plus button here?
![image](https://cloud.githubusercontent.com/assets/1942359/23668187/9f6dba1e-0360-11e7-9997-b6fe8e7898d2.png)

**Comment by nsteinme** [comment]
Yep. Is it possible to autofill in that case?

**Comment by rossant** [comment]
I don't think so but I'll double-check...

**Comment by rossant** [comment]
It doesn't look like this is possible, closing for now...

**Comment by nsteinme** [comment]
Well also we don't have the cage anymore! So no worries in any case.
