### ISSUE TITLE
adverse effects filter broken?

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#145]
For some reason I see only Chain even when opening the filters:

![image](https://cloud.githubusercontent.com/assets/7590975/23677675/003a0a4c-0379-11e7-88c5-1459ce5c1b66.png)

But mouse DA_205 (aka ALK042 in the procedure log) also has text in Adverse effects.

**Comment by nsteinme** [comment]
(I confirmed that this text did successfully make it into alyx, too)

**Comment by rossant** [comment]
Should be fixed
