### ISSUE TITLE
surgeries table should show:

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#146]
subject nickname - date of surgery - users* - procedures** - notes

That's this page - /admin/actions/surgery/ - currently it shows subject, start time, brain location, outcome type. All fields not read-only, but one of them should link to the surgery entry - maybe the date?

* users as a string, like "armin, charu"
** procedures also as a string like "implant headplate, anesthetize >1hr, craniotomy"

**Comment by rossant** [comment]
wdym by "All fields not read-only"?

**Comment by nsteinme** [comment]
Whoops, sorry, I actually meant all fields _are_ read-only. This is just for looking at the list, then you click the link on the date to edit it (in general people won't be editing this after it's created anyway.

**Comment by nsteinme** [comment]
Yes, standard ones: line, responsible user, alive/dead, thanks!

**Comment by rossant** [comment]
The responsible user and not the users who performed the surgery, right?

**Comment by rossant** [comment]
Done

**Comment by nsteinme** [comment]
Right!
