### ISSUE TITLE
Remove null=True in string fields

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#148]
I just realized that [django strongly advises against allowing null values in string fields](https://docs.djangoproject.com/en/dev/ref/models/fields/#null). Otherwise, we have two different values for "no value": null, and the empty string. @nippoo should we remove all `null=True` in TextFields and CharFields?

**Comment by nippoo** [comment]
Yeah let's remove them all. I'm not sure why I did this in the first place. I think there might have been an 'excellent reason' that's no longer relevant...

**Comment by rossant** [comment]
done in PR
