### ISSUE TITLE
Standardize informal/display name?

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#150]
@nippoo @nsteinme should we use always the same field name for the "short name"? Idem for lines with auto_name? Subject nickname?? etc.

**Comment by nsteinme** [comment]
Yes sounds good for me. Maybe "nickname" is the most direct and memorable
version? Or maybe that's just me ;) Could just make it "name" and have the
other fields be called "long_name" or something.

**Comment by rossant** [comment]
@nippoo wdyt?

**Comment by rossant** [comment]
@nippoo what do you think of making the following change: every model has a `name` which is always short and which is what's used everywhere, and `long_name` which is the long name no one ever uses?

**Comment by nippoo** [comment]
Every model? I'm confused. What are the implications of this? Which models are you proposing to change?

**Comment by rossant** [comment]
Sorry, not all models. Here's a tentative list of fields that could be renamed to "name":

* Appliance.descriptive_name
* Subject.nickname
* Litter.descriptive_name
* Line.auto_name (there's also a name field, which is confusing!)
* Strain.descriptive_name
* Species.display_name
* Allele.informal_name

**Comment by rossant** [comment]
do we go ahead with this @nippoo ?

**Comment by nippoo** [comment]
OK. Sure, these look good, except Allele (we should distinguish informal_name from standard_name). And Species to distinguish binomial name from display/informal name (this could be changed to "informal name" though).

What were you proposing to do with Line.auto_name vs Line.name?

**Comment by rossant** [comment]
I think the idea was that, when there are two different fields, we call "name" the shorter one and "long_name" the longer one. So Allele.name and Allele.long_name? Same for Species. 

For Line: auto_name => name, and name => long_name.

@nsteinme

**Comment by nsteinme** [comment]
Yes agree this is a good idea, I was also just recently being frustrated
writing an sql query and having to figure out what version of "name" or
"description" to use for each table.

**Comment by rossant** [comment]
I had started to do it but it was so complicated to make the migrations that I gave up... I could try again but it would take a long time and there would be a risk of data loss.

**Comment by rossant** [comment]
done
