### ISSUE TITLE
Decrease the number of items per page in list page

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#151]
@nsteinme @nippoo Currently, 100 lines are displayed by default (with pagination). It's a lot, so loading times are significant. We can reduce this to 50 or something if seeing that many lines at once is unnecessary.

**Comment by nsteinme** [comment]
50 should be ok. Why does it take a long time though? Maybe this is the same problem Max's rest api is having with speed.

**Comment by rossant** [comment]
No I think it has more to do with the fact that the HTML page is heavy for the browser, especially when there are editable forms. It's not that slow on my machine to be honest, but I fear that once on the server, when there will be a lot of data and many users, it might end up taking several seconds to load.

**Comment by rossant** [comment]
Done
