### ISSUE TITLE
breeding pairs table

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#152]
(but don't do this yet, see email)

- [x] new table, "Breeding Pair" with fields Line, name, start date, end date, father, mother1, mother2, litters. I recommend that F, M1, M2 be foreign keys to subjects table since a particular mouse could be in multiple breeding pairs. 
- [x] Litters should instead have a foreign key to a breeding pair, rather than a mother and father
- [x] Breeding pairs get auto-named "xx_BP_1" when a line is specified. 
- [x] If you are on the "change" page for an existing BP that has a Line, ideally the drop-downs to select F, M1, M2 would only show subjects of the correct gender and correct Line

- [x] Cage table goes away. Cage fields replaced by integers and renamed "LAMIS cage" (@nippoo - you said this should already have been implemented but it wasn't - was there a reason you were holding off?)

- [x] Import script for breeding pairs. I will have to sanitize the "September 2016" table first.

**Comment by nsteinme** [comment]
We do want to go ahead on this! :/

**Comment by nsteinme** [comment]
BP table is ready for import, it's the sheet called September 2016. Rules:
- ignore all columns up to K
- each row is one new breeding pair
- name is constructed as autoname from Line and Index (first one should be Ai32_BP_1, etc)
- Line is the line autoname
- notes => notes
- father, mother1, mother2 are subject nicknames. In most cases you will have to create a new subject because these won't be in the database from the other sheets. If you do, assign the nickname, line, and birth date as given. If you import the breeding pairs before importing the other sheets, just check when you are making those other subjects whether they were already created from this sheet. 

- When importing sheets for each line, in at least one case I have a "BP index" column now, so any litters should get the corresponding BP parent.

**Comment by rossant** [comment]
done
