### ISSUE TITLE
tab order on inlines? 

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#154]
Is there a way to set the tab order? Laura observes that when She's entering ear marks into the google spreadsheet, she can just type one, <enter>, type one, <enter>, etc. Right now you have to type, click, type, click, which as you know is significantly slower and more importantly, obnoxious. Any solution we can think of?

**Comment by rossant** [comment]
` she can just type one, , type one, , etc`

a character seems to be missing? Do you mean "down arrow"?

**Comment by nippoo** [comment]
he means "tab"

**Comment by rossant** [comment]
On the spreadsheet, tab lets you go from one ear mark to the next?

Anyway I'm not sure there's an easy way to change the tab order in inlines? Another possibility is to try to write a small javascript function that binds up/down keys to "previous/next" inline? So you could "write an ear mark", "down", "write an ear mark", etc.

**Comment by nsteinme** [comment]
I meant the enter key, not tab (sorry, I put it in angle brackets which I
guess are escape characters). Yes down arrow would work!

**Comment by rossant** [comment]
It looks like this is going to work... We can also use Enter instead of/in addition to up/down if you prefer. The problem is that Enter is already bound to "validate form" which may be useful when you want to quickly save the page.

**Comment by nsteinme** [comment]
Yes I think Enter is quite nice in that way currently. Actually if you can
do tab and shift-tab it would probably be most natural, but I think up/down
is just fine!

**Comment by rossant** [comment]
Tab is also nice, but it's already used by default to select the next input on a given *row* (which is the default behavior in all programs) instead of a given *column*. That being said, if you think users will never user tab as it is available currently, then we can use it.

**Comment by rossant** [comment]
done with up/down for now, we can easily change.

**Comment by nsteinme** [comment]
Sounds great, thanks -

**Comment by nsteinme** [comment]
Hey Cyrille I realized a problem with this which is the autocomplete function of the browser - if you type "ML" and you have previously typed "ML" into one of these boxes then your browser (or at least chrome on windows) "helpfully" pops up an autocomplete dropdown that has the option of choosing "ML" (even though you already typed all of that!). Then if you try to press down arrow, you just select the ML in this dropdown autocomplete, and can't get to the actually next earmark box unless you press escape to clear the autocomplete and then down arrow. It's super annoying. What about ctrl+down or something, could it then skip the autocomplete box, do you know?

**Comment by nsteinme** [comment]
Or better, either down _or_ ctrl+down, maybe.

**Comment by rossant** [comment]
Sure we can add ctrl+down. But is autocomplete always useless so that we can just disable it in the application? Or do you want it for some fields?

**Comment by rossant** [comment]
Note to self: to disable autocomplete use

```javascript
$(document).ready(function() {
    $(":input").attr("autocomplete", "off");
});
```

**Comment by nsteinme** [comment]
Yes I think disabling it here makes a lot of sense!
