### ISSUE TITLE
Subjects need three boolean fields: "to be genotyped", "to be culled", "reduced"

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#156]
"Reduced" means whether the paperwork about it has been submitted, which sometimes happens much later but you need to remember which mice haven't had it done yet. 

* [x] Add three boolean fields
* [x] "Cull Subjects" should show this as an editable checkbox.
* [x] "Cull subjects" should get a new filter option under "Alive": yes/no/not-reduced where the last shows mice with a death date but haven't been reduced.

**Comment by rossant** [comment]
Should it be a Boolean (True/False) or NullBoolean (Null/True/False) ?

**Comment by nsteinme** [comment]
True/False, default false.

**Comment by rossant** [comment]
You want these 3 checkboxes editable for each subject in the cull subjects view?

**Comment by rossant** [comment]
done

**Comment by nsteinme** [comment]
yep
