### ISSUE TITLE
"daily reports"

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#160]
This was @nippoo 's idea from our conversation today. Not something to rush on but a good idea so worth writing down. The point is to send people emails summarizing what the database knows about what needs to happen for their mice. For lab members this means reminding them about mice they have on water restriction, and mice they've reserved but haven't done surgery on yet. For Charu/Laura, this means reminders about mice that are "to be genotyped" and "to be culled" and whatever else we think of.

**Comment by rossant** [comment]
* [ ] Mice on water restriction
* [ ] Mice assigned to user but no surgery yet
* [ ] Mice to be genotyped and culled (Charu/Laura)

**Comment by nsteinme** [comment]
Yes, great, and add "to be reduced" to the last one, i.e. mice that have a death date but aren't "reduced".

**Comment by rossant** [comment]
Might be wise to wait for #228 so that I can use the same manage.py stuff for these scripts.
