### ISSUE TITLE
zygosities filter

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#161]
In the spreadsheets Charu colors "positive" mice green, here we'll just filter for them. So on the subjects page, add another filter that has these options: 
- All (no filter)
- All positive - for any alleles that the mouse has, its zygosity is +, +/-, or +/+
- All homo - for any alleles that the mouse has, its zygosity is +/+

I think those are the only things you'd want to filter for but I suppose we can add others later. Btw is it possible to make the filters be a dropdown box? Really just the "line" filter - there are a lot of options, so it might be more convenient this way. Not the end of the world if not.

**Comment by rossant** [comment]
done
