### ISSUE TITLE
crash when assigning litter

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#162]
I was trying to test the zygosities from parents, so I made two fake parents, made them both homozygous for an allele, and set them as the mother and father of a litter. Then I wanted to trigger the automatic calculation of the child's zygosities, so I took one of the children of that litter and assigned it to have null litter, saved, then assigned it to have the litter again. I got the error below trying to save this last assignment. This subject still has a null litter now, and I can't get it to become part of the litter it used to be in (i.e. this exact crash is repeatable). I also cannot create a new subject to be part of the litter on the litter page. 

![image](https://cloud.githubusercontent.com/assets/7590975/23796541/5f5cfa04-0593-11e7-8823-16e0449ad8bc.png)

**Comment by rossant** [comment]
Thanks for the detailed bug report. Should be fixed.
