### ISSUE TITLE
new column to import in "current lines in the unit" sheet: strain

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#164]
Create the strain if it doesn't exist. 

Then, when creating new mice, give them the strain of the Line where specified.

**Comment by rossant** [comment]
I see that both subjects and lines have a foreign key to strain, isn't this redundant?

**Comment by nsteinme** [comment]
No - the line may eventually change strain as it becomes more and more
inbred - in that case the line's strain will be manually updated to the new
version, but all the previous subjects will of course still have their old
(and still correct) strain identifier. The strain of the subject should
autofill from the line if the subject is created with a line specified,
however.

**Comment by rossant** [comment]
done
