### ISSUE TITLE
remove add/delete/edit buttons for resp. user in subjects view?

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#173]
But leave it as a dropdown to choose a new one, is it possible? Trying to think about how to save space, see next issue. (Plus we don't want people deleting users from here...)

**Comment by rossant** [comment]
Done. At the moment I did a quick hack that hides these buttons with CSS. However it hides them everywhere, in all list pages. If that's not desirable (ie you want to see these buttons in another list page) let me know!

**Comment by nsteinme** [comment]
Do you mean hides them for all models everywhere, or just for the
responsible_user everywhere? It might work to hide them for everything
everywhere actually, now that I think about it.

**Comment by rossant** [comment]
Hide for all fields, all models, but just on the list view, not the "details" view.

**Comment by nsteinme** [comment]
Yep I think this is good!
