### ISSUE TITLE
More compact subject list view

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#174]
Can we make it just one line rather than multi-line-sized box, even though it is the kind of field that's allowed to hold lots of text? It would be great if it didn't make the subject rows take up any more vertical space than they already do. 

Is there also a way to change the default font size on either the particular view or on the whole admin site? I think we'd better go for a smaller font size. 

The problem is, when you have too small of a window, what happens is that things start to get clipped and you have to scroll way way down to the bottom to get a horizontal scroll bar. I wonder if there's any way this behavior could be different? Even having the horizontal scroll bar at the top would be a huge improvement. It may well be the case that people use alyx on the small laptops in the surgery room and the animal facility so this is unfortunately something we have to think about. On my computer shift+scroll makes the mouse's scroll wheel do horizontal, so if that works on most computers then we might be all right. In that case it would really be ideal to keep "nickname" visible, analogous to "freezing" that column in a spreadsheet.

Another great option here would be the ability to hide/unhide columns with a click, like if there were a list on the right side just like "filter" with column names listed and checkboxes on them. I tried searching around for this but I can't find anything obvious. If you were already getting into js stuff then maybe [this one](http://stackoverflow.com/questions/26139206/django-admin-hide-field-on-change-select-field) is related? 

Another thing that could help here is if the Filter box can go above the table, e.g. with different filter options horizontally arranged across the top rather than taking up space on the right. If this can't be done in the default admin interface then it looks like a different skin might be able to do it, e.g. [this screenshot](https://matijakolaric.com/wp-content/uploads/2014/10/djangoadmin-suit-skin.png) of "suit" appears to show this behavior.

**Comment by rossant** [comment]
More complete answer to come but just checking: do you know the ctrl+wheel shortcut to change the scale of the page? not exactly what you want but it comes in handy sometimes

**Comment by nsteinme** [comment]
Yep I do know that, that's what I've been doing in practice. I'm still a
bit worried about a small screen. But if there's no other obvious solutions
along the lines I proposed, or whatever else you can think of, then we'll
add the notes anyway and just see how it goes. It'll be the kind of thing
we just need to test I guess, see what works for people.

**Comment by rossant** [comment]
A few random ideas:

* Remove Alive and Sex columns, and use some color code for text or background to reflect the possible values
* More concise representation of birth date
* Putting the filter box at the top is possible but a bit painful (need to redesign it)
* I would prefer to avoid suing customized "skins" unless we really have to (I suspect they are less well supported, that's yet another dependency, etc.)
* I think we can do something where you can click on checkboxes to make columns hide or reappear. We can do it on an individual level (you can toggle every single column) or more globally (switch between different sets of columns, depending on what you want to see; set A shows columns X, Y, Z; set B shows columns X, U, V; etc.)

**Comment by nsteinme** [comment]
First two ideas are definitely fine - so long as removing alive column
still allows to filter by alive/dead? Something where you make all the text
of the row a lighter color (like greyed-out, sort of thing) to indicate a
dead mouse would be fine. For M/F, I'm not sure what's most intuitive to
color-code, but maybe the litter name for instance could be blue/pink or
whatever politically-incorrect colors we would want to go with :) If it's
possible to color-code the background of the row, I would reserve this for
the genotype: mice that fit the "all positive" zygosity filter would have a
green background, the rest grey/default (that's the current spreadsheet
scheme). But I still think you want to keep the zygosity text.

If any of that stuff is painful let's leave it for now and see how it goes.
Better to focus on backups and whatever else.

**Comment by nsteinme** [comment]
Let me elaborate on compact birth date representation: probably an even more useful representation here, anyway, would be age in days. If the column is just called "Age" or maybe "Age (d)" or something, then this would be quite compact.
