### ISSUE TITLE
putting everything in / personal schemas

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#176]
@kdharris101 @nippoo I spoke with Kevin about Brody lab's databasing and they also have an sql database that, to my surprise a second time (first was our conversation with Laura), literally all of the data goes into, down to spike times (but not raw electrophysiology traces: once those are processed they are backed up elsewhere and the database doesn't know about them). They have a "rats" table and a "sessions" table - it would be good to see if they'll share the definitions/models/whatever for us to learn from. They interact with their database exclusively with literal sql queries (!). So the two points here are:

1) We may want to think more about the option of putting everything into the database, or at least for planning on that possibility, e.g. perhaps the models like TimeSeries could have a field for the actual data and a field for the link to the file and either or both could be present. This would also mean we'd want to think about the possibility of having a database that's very large (in data size), which has implications for backups and for hosting. 

2) They (or at least some of them) put also all the results of their analyses into the database. Kevin said that if he finds he's doing an analysis more than a couple times, he'll make a table for the results and put it in there. He makes the table within his own schema (if I have the terminology right) which is part of the same database (so can query/key across it and the public schema) but has separate permissions. E.g. each user can have their own scheme on which everyone has read access but only they have write access. 

@nippoo it may be worth trying to catch Kevin for a discussion about this, he's in the lab today until 2, and is in London through the end of the week.

**Comment by kdharris101** [comment]
I think we had a consensus:


1.       Use Alyx for “fixed” stuff, like animal husbandry.

2.       Use datajoint for personal analyses, that can be ad-hoc, flexible, and deleted at will. This is probably better than writing SQL queries.

The question of where spike times go is a good one – right now I would vote for dj rather than Alyx but it is a close call.

A key question is what backend do they use. If you see Kevin again today, ask him?

**Comment by nsteinme** [comment]
He said MySQL but didn't seem confident about it (I guess in practice this
did not come up for him).

**Comment by nippoo** [comment]
Are we all happy with the consensus on this, or do we need to leave this issue open?

**Comment by nsteinme** [comment]
Sure, just something to keep in mind mostly... still could imagine wanting
personal schemas though, even if not putting lots of data in directly.
