### ISSUE TITLE
add tables to google sheets backup: lines, litters, breeding pairs

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#177]
As separate sheets. For now just those are sufficient, we could think about doing more in the future.

**Comment by rossant** [comment]
Could you write the corresponding SQL requests? to save them as TSV? Once I have the TSV files I upload them to google sheets.

**Comment by nsteinme** [comment]
Ah, got it, yes will do.

**Comment by nsteinme** [comment]
Ok I wrote and tested four new sql queries then pushed them - they are in
/backups/queries now.

**Comment by rossant** [comment]
thanks, done!

**Comment by nsteinme** [comment]
Looks great!

**Comment by rossant** [comment]
To backup a new table or view:

* Add a new .sql file
* Open the Google Spreadsheet document and create a new sheet with the name of the sql file (without the extension)
* Commit or create a pull request!
