### ISSUE TITLE
LAMIS cage field

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#182]
* [x] This can just be called Cage, and is now an integer. 
* [x] It should be somewhere on the Subject page itself, like maybe under Profile. 
* [x] In the Litter page, it should be in the subject inline, editable. 
* [x] In the Cull Subjects view, it should be a column but not editable. 
* [x] When importing, the "LAMIS cage number" column of the Line sheets goes in this value.

**Comment by rossant** [comment]
done
