### ISSUE TITLE
water requirements broken?

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#183]
I haven't tested this in a while but just tried to do it now. It doesn't seem to succeed in computing the requirements. It does find the correct reference and current weighing though. Perhaps the csv that has the reference data was moved or deleted? You can check out this particular test case right now at: http://alyx.cortexlab.net/admin/subjects/subject/3a8e2de4-0e46-4f3d-af6d-c56e72584b87/change/

![image](https://cloud.githubusercontent.com/assets/7590975/23943958/116981d0-0969-11e7-9571-72a14995dfab.png)

**Comment by nippoo** [comment]
Why are we storing anything in a CSV? Seems like a really backwards way when we've got a database...!

**Comment by nsteinme** [comment]
What's stored in CSV is the "reference" data about normal mouse weights
(means and stds) over age (by week) for male and female. The "Water
Control" google spreadsheet should be shared with you, see the last sheets.
There aren't that many numbers - in principle you could literally write
them in a vector into your code. Of course we could make a
"reference_weights" table or something in the database, it just seemed
unnecessary at the time, I think. In any case, I have no evidence that
anything related to the CSV is what went wrong! Just a guess.

**Comment by nippoo** [comment]
Yep, for sure. It just seems cleaner to make this a reference_weights table so you can update it for different strains / species as appropriate and so you don't have to worry about more static tabular files lying around. Anyway, whatever works.

**Comment by nsteinme** [comment]
sure, that's a great point that you might want different ones for different
strains or species. Perhaps just putting the data in the json of the
species, and given the species of the subject in question then looking it
up from there, would make sense?

Btw so I understand more about best practices with database tables - how
would you do it as a table? You want each row of the table to have a field
for the species and/or strain, and then a different field for each week's
mean and sd weights? E.g. in that case if you had 10 weeks' of data you'd
have 20 fields (40 to count each gender). Or just four fields (M_mean,
M_std, F_mean, F_std) that each have an array of values in them? Does that
mean specifically that they should be array fields? Ignoring all of my
hypotheses, how would you approach putting these data into the database?
Thanks!

**Comment by nsteinme** [comment]
Ok no wait, I've got it. The table has six fields: species, strain, age (in
weeks perhaps), gender, mean, std. Then you just query the rows that
correspond to your specified species, strain, age, and gender.

Yes, let's make this table. Note that if the species is mouse and strain is
either unspecified or the mouse's strain does not exist in this table, then
you should default to using C57BL/6J strain (which is the only dataset we
have right now for reference weights, anyway).

**Comment by rossant** [comment]
This bug had nothing to do with the CSV file. :) It should be fixed in the upcoming PR.

Yes doing a table instead of using CSV is cleaner but it's more work to write the appropriate fixtures/migrations, especially if you want to support species-dependent tables. Let's do it later. Feel free to open a new issue.
