### ISSUE TITLE
import water control data

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#186]
You should have access to the Water Control google doc. 

Each sheet in the document corresponds to a mouse - the title of the sheet should be the name of the mouse, and you should have already imported all of the mice (if one or more is not an existing mouse name, don't import it but maybe let me know). 

If the mouse doesn't yet have a gender or DOB, add these according to the info at the top of the sheet, along with implant weight. 

Create a new water restriction with start date as in 9A, and create a new weighing on that date with the value in 9D. 

Then each row of the main section should produce three database entries: 
1) A weighing, with the date as given and the value as in column D
2) A water administration (hydrogel=false) with the value in column F (except when this value is zero)
3) A water administration (hydrogel=true) with the value in column G (except when this value is zero)

If the formula in alyx is the same as the one in the sheets - it is supposed to be - then hopefully we get the same numbers: column I == water_requirement_total. 

@k1o0

**Comment by rossant** [comment]
FYI here are the mouses in Water control that don't exist in the already-imported mice:

AS151028, BH150928III, BH150928IV, Diesel, JF150617a, JF150617b, JF151104B, M140701-5 BH, M160114A, M160114B, M160114C, M160302A, M160302B, M160302C, M160302D, M160427A, PC005, PC006, PC009, PC010, Vin

**Comment by rossant** [comment]
Also ALK045 has a different birth date in the water control sheet and the other sheets

**Comment by rossant** [comment]
what should I do when there are several water control lines? Everything is shifted so the line of headers is not on line 12 etc. Should I add several WaterRestriction etc?

**Comment by nsteinme** [comment]
Ah, I didn't realize people had done this. Let me discuss with Miles.

**Comment by nsteinme** [comment]
Ok the answer is, yes do add a second water restriction, and Miles has put
an End Date for all the older ones so that you can "close" those. Sound ok?

**Comment by rossant** [comment]
OK. What is the max number of water restrictions? 2? Would it be possible to normalize all sheets so that the weighings list always starts at the same row? (header on line 13 or something) It would make things much easier for me...

**Comment by nsteinme** [comment]
Hm no there's no max number of restrictions in principle. I'll make them
all start on 14 though.

**Comment by nsteinme** [comment]
done -
