### ISSUE TITLE
Enforce URL-safe characters only in nickname field

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/alyx#188]
To avoid calling a subject `/hello?/my&name=ismouse`

**Comment by nippoo** [comment]
@nsteinme can we restrict to `[-._~\w]+` please?

ie uppercase + lowercase + number + full stop + dot + underscore + tilde?

I'd rather not include brackets and space if poss because they could cause problems for some API clients (ideally would just do just the RFC 3986 unreserved characters). You currently have a subject called `M170201_ICNK (ML)` (and a couple of others) which break the endpoint if I apply this validation.

I've included brackets and space for the moment to let this mouse live but kinda want to remove them.

> 2.3.  Unreserved Characters
> 
>    Characters that are allowed in a URI but do not have a reserved
>    purpose are called unreserved.  These include uppercase and lowercase
>    letters, decimal digits, hyphen, period, underscore, and tilde.
> 
>       unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"

**Comment by nsteinme** [comment]
To be clear, I-Chun typed that mouse name in, and she did not (I assume)
intend for that to be the "name" - the parenthetical part is just
specifying the ear mark, for her reference. I can update the procedure log
to be M170201_ICNK_ML or something. I've sanitized a million things getting
these import scripts to work, I can sanitize one more.
