### ISSUE TITLE
three new fields for Subject

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#19]
@kdharris101 

There are three fields in our current spreadsheet for each subject that aren't in the database, and they pertain to UK home office data - how should we incorporate these into alyx? As JSON fields so that another implementation of Alyx could ignore them? Or as true fields? 

They are: Protocol number (a number, in our case 1-4), adverse effects (an open text field), and actual severity (the options are: sub-threshold, mild, moderate, severe, or non-recovery, as per https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/276014/NotesActualSeverityReporting.pdf)

**Comment by kdharris101** [comment]
I would suggest we have them in the JSON – provided it is just as easy to access them from the admin interface?

If not, let’s have them as main fields.

**Comment by rossant** [comment]
> I would suggest we have them in the JSON – provided it is just as easy to access them from the admin interface?

It will be once https://github.com/cortex-lab/alyx/issues/5 is done.
