### ISSUE TITLE
updated rule for KHA zygosities

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#193]
```
('KHA', 'Vglut1-MD', (('Vglut1 MD,Vglut1 WT', '+/-'),
                  ('Vglut1 MD,-Vglut1 WT', '+/+'), 
                  ('-Vglut1 MD', '-/-'))),
```

**Comment by rossant** [comment]
it's a brand new one? The "'KHA', 'KHA1-KO'" one should not be removed right?

**Comment by nsteinme** [comment]
Good question, no I meant to replace that old one (I had the wrong name for
the allele, in addition to the wrong rule!). So do remove the rule for
KHA1-KO.
