### ISSUE TITLE
add filter to Subjects view: "todo"

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#198]
- [x] The options for this filter are "to be genotyped", "to be culled", and "to be reduced". The first two just return any mice with those boolean flags true. The last returns mice that are not alive but for which the boolean reduced flag is false. 

I was thinking we might need an extra proxy model for how to view these "tasks", but I think this solution is probably the easiest and most straightforward. 

- [x] Btw once a mouse is genotyped we don't want it to appear here anymore - so if a mouse is assigned a genotype date, then its "to be genotyped" flag should be set to false.

**Comment by rossant** [comment]
Item (2) should already be implemented, it is not working?

**Comment by nsteinme** [comment]
Ah yes, so it is, sorry!

**Comment by rossant** [comment]
done
