### ISSUE TITLE
rewrite reset_all and merge most functions into into manage.py

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/alyx#201]
- [x] exec SQL using psycopg rather than os calls to psql (using settings_secret.py username/pass, to avoid having to run as same user)
- [x] `drop schema public cascade;` rather than `drop database`;
- [ ] move most other things to manage.py as custom functions rather than (so you can be assured you're running the right python - on rod `python` uses anaconda but `python3` is the system/WSGI python which we want to use.

**Comment by nsteinme** [comment]
Please also document how to do migrations and/or reimportations (on rod and/or elsewhere) here: http://wiki.cortexlab.net/index.php/Alyx
