### ISSUE TITLE
need a way to rest api query for a list of subjects on water restriction

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#207]
Currently my best way to do this is query each subject individually (at /subjects/subjectName) and see whether water_requirement_remaining is zero or not. Could we have a water_restrictions endpoint? Or return a boolean about whether the subject is on water restriction with the main subjects query? What do you think is the best way? Could add a specific query type, like /subjects?alive=True&on_water_restriction=True ?

**Comment by nippoo** [comment]
What about /water_restricted_subjects and then I'd just have a SummaryView with the water requirements directly exposed so you'd get the whole shabang in one go? What other info do you need? Name, URL, water_requirement_total, water_requirement_remaining?

**Comment by nsteinme** [comment]
I think that would do it - let me show you what I've got in matlab tomorrow if you're around.
