### ISSUE TITLE
Start testing the REST API

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#21]
Just the water administration and weighings for now

**Comment by nsteinme** [comment]
Actually, I have just tested and it looks like both of these do work! See my test script over in alyx-matlab for some important details about how to get it going from matlab: https://github.com/cortex-lab/alyx-matlab/blob/master/exampleScript.m

I will get started incorporating these two into lab code, then.

**Comment by nsteinme** [comment]
But let's keep the issue open, because I don't know how to do these things yet:

A) Create experiment
B) Create model
C) Add model to experiment
D) Add details about the model
E) Create dataset
F) Add dataset to model
G) Add details to dataset

I think these are the next step.
