### ISSUE TITLE
backup documentation

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#210]
I started a section on Alyx's wiki page about the backups - http://wiki.cortexlab.net/index.php/Alyx

Once each backup is in place, we should describe: how often it happens; whether every version is stored or just the most recent; how to access the backed up data; how to restore alyx from the data (if possible for that method). 

See also #127. I don't think any backups are in place/working yet, right? TSV didn't work last time I tried it, and google sheets works but isn't happening regularly. Other more correct/recoverable solutions aren't implemented yet, is that right?

**Comment by rossant** [comment]
Nothing is run automatically at the moment (to do in #127).

`./backup-tsv-local.sh` works for me at the moment:

```
COPY 27
COPY 24
COPY 732
COPY 25
COPY 95
COPY 0
COPY 609
Backup done in ./alyx-backups/2017-03-22/
27 items uploaded to `auth_user` sheet of Google Sheet backup document.
24 items uploaded to `breeding_pairs` sheet of Google Sheet backup document.
732 items uploaded to `genotype_tests` sheet of Google Sheet backup document.
25 items uploaded to `lines` sheet of Google Sheet backup document.
95 items uploaded to `litters` sheet of Google Sheet backup document.
609 items uploaded to `subject` sheet of Google Sheet backup document.
0 items uploaded to `subjectrequest` sheet of Google Sheet backup document.
```

This file is the same as the non-local one, except with the database connection info for my machine.

**Comment by nsteinme** [comment]
Still not working for me on Rod, error below, I think this is waiting on the better way to do the migration/importation/restart. @nippoo can you confirm that? 

```
nick@rod:/data/www/alyx/backups$ sudo ./backup-tsv.sh /mnt/zserver/Data/
[sudo] password for nick:
./backup-tsv.sh: line 3: realpath: command not found
dirname: missing operand
Try 'dirname --help' for more information.
mkdir: cannot create directory '/mnt/zserver/Data': File exists
cat: /queries/*.sql: No such file or directory
psql: FATAL:  no pg_hba.conf entry for host "128.40.89.151", user "alyx_ro", database "alyx", SSL on
FATAL:  no pg_hba.conf entry for host "128.40.89.151", user "alyx_ro", database "alyx", SSL off
Backup done in /mnt/zserver/Data//alyx-backups/2017-03-22/
./backup-tsv.sh: line 23: /upload-gsheets.py: No such file or directory
```

**Comment by rossant** [comment]
No it's something else, I'm having a look

**Comment by rossant** [comment]
I've fixed various bugs. The last remaining one is this @nippoo 

```
psql: FATAL:  no pg_hba.conf entry for host "128.40.89.151", user "alyx_ro", database "alyx", SSL on
```

**Comment by rossant** [comment]
@nippoo is there a way to make it such that `git pull` works instead of `sudo git pull`? Currently it's configured for write access on GitHub using root's ssh key...

**Comment by nippoo** [comment]
It should not be configured for write access! And if it is it definitely shouldn't be using SSH keys (HTTPS auth only...)...

Yeah I'd need to create a usergroup called "alyx-admin" and make the files owned by that group. But now we're moving away from central LDAP... :/ I'll work on it

**Comment by rossant** [comment]
Thanks!
I'm curious, why it shouldn't be configured for write access? It may happen that we want to push changes from rod to GitHub, no? And why not SSH keys?
