### ISSUE TITLE
admin home page tweaks

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#211]
Matteo suggests the following changes, are these things possible? 

- [x] remove orange "change" links from the home page view (they do the same thing as clicking the title of the table, don't they?)

- [x] change "site administration" text at the top to say "Welcome to Alyx."
- [x] remove "documentation" and "view site" links from the top. I agree with Matteo that these are rarely if ever used by 99% of people and are confusing to have there (someone might want some documentation, click it, and get even more confused since it is not what they are looking for). But it would be good to link to this information somewhere, perhaps we can add the documentation link to the rest api browser at alyx.cortexlab.net? 

- [x] move "Lines" and "Other Actions" from Common to Static

- [x] Rename "Static" to "Data that changes rarely"

 
- [x] Possible to make Static, Other, and IT Admin groupings collapsible like we did on the Subject page, with a show/hide button on each?

**Comment by rossant** [comment]
Show/hide was not possible on the admin index but I managed to do it with quite a bit of Javascript...!
Everything should be done.

**Comment by nsteinme** [comment]
Heroic! Matteo will be happy :)
