### ISSUE TITLE
link for surgeries is broken

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#212]
In the Surgeries table, when you click the date to see further details about the surgery, the change page comes up but with the Subject not shown. I think this happens because it defaults to showing you only the subjects for which you are the responsible user, so if you clicked a surgery that's for someone else's mouse, then that mouse isn't even an option. One solution is probably: if you are editing rather than adding a surgery, the current subject is always in the available subjects and is selected by default. Another solution would be, change from showing only the current user's mice, to showing all mice but sorted such that the current user's are at the top of the list.

**Comment by rossant** [comment]
Fixed. I just added the current subject to the list of the logged user's subjects.
