### ISSUE TITLE
keep history of lamis cage numbers, like history of nicknames

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#215]
When a mouse has a new LAMIS cage number assigned, add the old one to a json field called something like "past_lamis_cage_numbers" or something.

**Comment by nsteinme** [comment]
Ok, so @k1o0 just suggested it would also be good to keep history of responsible_user. Sounds like we may need a general solution for this. Existing issue #137 would allow us to roll back but wouldn't allow us to search or easily view the history. I wonder if there is a sensible or easy way to keep and view history that also keeps the values, not just the fact that something changed? Maybe something that we could enable for certain fields (only those that are changeable and aren't a large amount of data)? Any thoughts @nippoo @rossant @kdharris101 ?

**Comment by rossant** [comment]
Why not just a JSON field? Something like

```
"history": [
  "lamis_cage": [0, 1, 2, 3],
  "responsible_user": ["charu", "nick", "max"]
]
```

Not for all fields but a subset. Would you need the dates of the changes as well?

**Comment by nsteinme** [comment]
Ideally the date_time as well. I agree this seems like a very sensible solution. I feel like we must be reinventing some wheel, though.

**Comment by rossant** [comment]
OK that should work, feel free to try it.
