### ISSUE TITLE
way to assign lamis cage number to parents of a breeding pair?

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#216]
When a breeding pair is put together, all two or three mice get a new cage number, the same one. It's important to record this information and would be laborious to go to each mouse's page and enter it separately. Any thoughts about how to do this? One idea could be to use the "actions" dropdown? When looking at the breeding pairs table, checkbox one of the BPs, then do an "assign cage number" action which just asks for one number, the new cage number, and gives it to all the parents in that BP? I'm not sure what the best strategy is.

**Comment by rossant** [comment]
Would it work to have a new "lamis_cage" dropdown in the "change breeding pair" page which, when you click "save", is assigned to the parents of the breeding pair?

**Comment by nsteinme** [comment]
Sure! Except not a dropdown, just a textbox since the cage is just a
number. That would be perfect! I didn't realize you can just have arbitrary
boxes/fields that aren't related to any table columns. Thanks -

**Comment by rossant** [comment]
done!
