### ISSUE TITLE
parameters and parameter_sets

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#218]
idea for two new tables: parameters and parameter_sets. Each parameter has a name, a description, and units; e.g. "orientation", "Orientation of the grating", "degrees". Each parameter set has a list of parameters that apply to that set, and certain experimental datasets can point to a parameter set. We'd have to think more about the best way to do this (e.g. are the particular values for the parameter stored in the parameter table or the parameter set? I think the set), but the advantages are: 1) Need a good way to make the parameters for experiments searchable; 2) would help to standardize the names and meaning of parameters across people's experiments.

@kdharris101 @k1o0 we should discuss at some point. Not high priority though I guess.

**Comment by nsteinme** [comment]
I'd like to try adding these tables and associated rest api endpoints. We have some documentation about the rest api endpoints now at http://wiki.cortexlab.net/index.php/Alyx. @rossant would you mind adding some documentation there about how to add a table and any things one needs to think about when doing this? Then I could try it and make a PR. Let me know what you think about that idea.

**Comment by rossant** [comment]
@nsteinme ok. In the meantime I strongly recommend you to read the [django tutorial](https://docs.djangoproject.com/en/1.10/intro/) (not necessarily actually do it on your computer but at least read it). It is well written and it will give you the relevant definitions and abstractions.

Here you want a new `Parameter` model, which corresponds to an SQL table where each row is a parameter name. I think you also want a `ManyToMany` relationship between `Dataset` and `Parameter`. That is, every dataset has a list of parameters. You want additional information: the actual parameter value. So you want a `through` table in this many-to-many relationship, where each dataset-experiment link is one row in that table, and there is an associated value which is that parameter's value (a bit like `Zygosity`).

**Comment by rossant** [comment]
use json field of session instead
