### ISSUE TITLE
figure out how to properly deal with strains

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#22]

**Comment by kdharris101** [comment]
Here is the full document describing the naming conventions:
http://www.informatics.jax.org/mgihome/nomen/strains.shtml

Quick start guide (under nomenclature for congenic strains):
https://www.jax.org/jax-mice-and-services/customer-support/technical-support/genetics-and-nomenclature

**Comment by nsteinme** [comment]
To write down our half-resolution, for further consideration later:
The strain will be B6.XXX where XXX is the shorthand for the other strain of origin, in the case that it is already congenic. It will be B6;XXX in the case where it is not already congenic. The information from Jax about generation (e.g. N2F5) will be recorded in the notes for the Line. We will consider making some automatically-updating version of this notation. We may manually switch over the strain from semicolon to dot around N5 or N6 where applicable.
