### ISSUE TITLE
updated import

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#221]
Both import of sheets for individual lines and the breeding pairs sheet need to have slightly altered importing, because I've "refactored" the organization of information on these pages (with Charu's approval). The reorganization was necessary so that 1) Charu's and Laura's updates to these spreadsheets can hopefully be immediately importable without further sanitization by me; and 2) so that some information already becomes recorded in an importable way (e.g. genotype date, which was otherwise buried in the notes). 

Here's a summary of the changes for the Line sheets, but note that I haven't yet changed all of them to the new format (I will post again here when they are all changed, but you can look at Camk2a-tTa if you want to go ahead). 
* [x] "autoname" now called "Animal name" (you can still use "n" column to construct the name as before, if you were doing it that way)
* [x] new column "G.type date" -> Genotype Date
* [x] new columns "to be g.typed", "to be culled", "reduced" -> if these cells are not empty (e.g. have 'x', 'y', whatever) then the corresponding boolean fields are true. Note, apply death date AFTER "to be culled" and genotype tests after "to be g.typed" so that they will get cleared as necessary.
* [x] new column "BP #" -> should correspond to one of the breeding pairs in the "September 2016" sheet - more on that sheet in a further update to this issue.

Might be a good idea to take a quick look at the sheets to make sure you are clear on what's there now, and see if it looks like I forgot anything in this list. Thanks!

**Comment by rossant** [comment]
Looks good! let me know when all sheets have been updated

**Comment by nsteinme** [comment]
Ok they are all updated. I will make a separate issue for the September 2016/breeding pairs sheet import.
