### ISSUE TITLE
small usability tweaks

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#226]
Some small things, only necessary if they're easy:

- [x] on "create" pages, default the "user" to the currently logged in user, e.g. for weighings, water admin, subject, session

- [x] on "create" pages, default the subject to be the last one that was modified/used in this browser/login session. So if I make a water admin for Hench, and then I go to make a weighing, Hench is automatically selected as the subject (I can change it if I want of course, but that's the default). 

- [x] on weighings/water admin create pages, default focus to be on the "amount" field, so that when you get to this page you just type a number and press enter and you're done (the user and subject were already usefully filled by default as above)

**Comment by rossant** [comment]
Should be done.

**Comment by rossant** [comment]
Should be done.
