### ISSUE TITLE
Water Restriction and Water Administration panels

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx#229]
Ideally these would be ordered alphabetically and by recency, respectively.  Also they should show more useful information such as the amount of water administered along with a more human-readable timestamp.  Perhaps both lists should be filterable too, particularly the water administrations which is currently 26 pages long.

**Comment by nsteinme** [comment]
Agreed, water administrations should ideally look like weighings with the amount and also the hydrogel flag. Both of these would be nice to have a dropdown filter on subject name. I vote default ordering is first by recency though so all of today's at the top. 

Water restrictions should ideally show subject name, start date, ref weighing, current weighing, water_req_total and water_req_remaining. Should have a filter for "active" meaning has a start date but no end date, default to only show these.

**Comment by nsteinme** [comment]
btw @k1o0 you can already type a subject name into the search box at the top

**Comment by rossant** [comment]
done
