### ISSUE TITLE
Import data from Google spreadsheets

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#23]
If spreadsheets (specifically Procedure Log) are manually cleaned up for consistency, can they be imported automatically?

**Comment by rossant** [comment]
Semi-automatically, yes.

There are two methods:

1. Slightly simpler: In google sheets, export your sheet as a CSV or TSV file. Then I'll have to write a script that parses the CSV and populates the appropriate tables.
2. Like 1 but the script automatically connects to google sheets and does the CSV export.

(2) is only useful if you expect to do this several times.

**Comment by nsteinme** [comment]
Ok, exporting from google sheets works fine manually. I'll email you the current sheet (to avoid posting publicly - sensitive data). It needs some cleaning but the idea is that from this you could make a new subject and a new surgery for that subject. The subject name is the "log file" column. The "Cage/Animal No" would have to go in as Notes on the Subject. "Procedures" would go in as Notes on the Surgery. Part of the cleaning up would be to separate out the "Name" field into who did the surgery and who the responsible user for the subject is. Another part would be separating out the cull date (i.e. death date) and culling method. "Strain" is not actually strain - it should instead go into Notes on the Subject.

But other than those bits of cleaning, do you think it can be done?

**Comment by rossant** [comment]
Sure, no problem. The import script is non trivial and will require some trial and error but it'll work. Once it works the same script can be reused later with an updated CSV file.

**Comment by nsteinme** [comment]
@rossant Probably time to prioritize this. I will send you (and @nippoo) some more sheets including an updated "procedure log" as well as some revisions on the thoughts about how to import, above (so please disregard those in favor of newer).

**Comment by rossant** [comment]
* should #36 be done first? If so where is the data?
* in mice procedure log, some lines are ~~striked~~, should they be discarded?

**Comment by nsteinme** [comment]
Do not discard the striked lines (it just means the mouse is dead, I
think).

Actually I am confused about the logic of #36 now - why do we need CSV
tables of it? Presumably what's produced by our backup scheme will be this?
But it is true that those are primarily "one time only" tables. I don't
think they're required for this, though.

**Comment by nsteinme** [comment]
Also, the Strains and Alleles etc that I have entered into the database
already should be kept if possible - some of this is already in there -
that's why I suggested wiping only Subjects and Surgeries when importing
new data.

**Comment by rossant** [comment]
OK could you dump these tables using django and send them to me? with `./manage.py dumpdata` I think

**Comment by rossant** [comment]
when there are multiple responsible users for one subject in the google sheet, should I just take the first one? (there can only be 1 responsible user per subject)

**Comment by nsteinme** [comment]
There are not any instances of multiple responsible users! Where do you see
it? There are multiple people under "surgery performed by" but that becomes
the "users" entry in the Surgery.

**Comment by rossant** [comment]
Oh right, you said in your email "responsible user needs to be translated from initials to database username, translation below, can be multiple users separated by comma" but actually there aren't any instances of multiple responsible users!

**Comment by rossant** [comment]
Also I don't understand how to find the `species`?

**Comment by rossant** [comment]
Is the list of all users already created in the django table? If not could you create it and send me the dumped file? I'll need it to assign responsible users to subjects. Thanks

**Comment by nsteinme** [comment]
Species is always mouse :)

**Comment by rossant** [comment]
![](https://68.media.tumblr.com/4ee2f6019871c8270126da2868ab8fff/tumblr_nynv7as6U01qjgyvoo1_400.gif)

**Comment by rossant** [comment]
First version done: static tables, subjects, lines, surgeries are imported.
