### ISSUE TITLE
Update to django 1.11

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#231]
[Django 1.11 has just been released](https://docs.djangoproject.com/en/1.11/releases/1.11/). It is a Long Term Support release, contrary to 1.10 which we are currently using. Should we update before alyx starts being used in production? I don't think there will be many changes. @nippoo @nsteinme

**Comment by nsteinme** [comment]
Sounds reasonable to me, will leave the decision to you and @nippoo.

**Comment by nippoo** [comment]
Sure. You want to take care of this one? I remember updating from 1.9 to 1.10 and it was a faff with all these random extensions we've added. But I agree we should be using an LTS version...

**Comment by rossant** [comment]
Ah, the extensions... Yes I will take care of it, at least if it's doable without too much complications.
