### ISSUE TITLE
alphabetise subject list in "weighings"

### ISSUE THREAD

**Issue by northerlywind** [cortex-lab/alyx#238]
in weighings the subject list is not alphabetised but seems ordered by category

**Comment by nsteinme** [comment]
To clarify, you mean when you "add weighing" in the admin interface, in the
subject dropdown? Cyrille could this default to showing only the user's
subjects? Or better, show them all, alphabetized, but show the current
user's subjects at the top of the list?

**Comment by northerlywind** [comment]
yes, the subjects drop-down when you add weighings (I presume this also applies to other actions I haven't visited yet)

**Comment by nsteinme** [comment]
Actually many of them don't have this problem - could you try adding a
surgery and seeing if this has the behavior you mean?

**Comment by northerlywind** [comment]
Yeah it seems the only one with this issue is the "weighings" category

**Comment by rossant** [comment]
This is a bug that only appears in weighings. It's going to be fixed. The normal behavior (like other actions) is to just show the user's subjects. Is it okay?

**Comment by northerlywind** [comment]
Fine with me!

**Comment by rossant** [comment]
This is done then! Closing.
