### ISSUE TITLE
add "favorites" sidebar above "recent" to have shortcuts to common actions for individuals

### ISSUE THREAD

**Issue by northerlywind** [cortex-lab/alyx#239]
as some actions would be used frequently for some users e.g. "add weighing for subject YYXXX" it would be useful to have a favorites sidebar to navigate to these actions straight from the homepage

**Comment by nsteinme** [comment]
I think any really common actions should be happening automatically for you
- especially weighings. Is there a reason you want to enter weighings
commonly?

**Comment by northerlywind** [comment]
I don't currently use a scale which automatically logs this so it would have to be a manual procedure.

**Comment by rossant** [comment]
I'm not sure how to implement this. Would it work for you to just add in your browser favorites to pages you use regularly? For example, go [to this page](http://alyx.cortexlab.net/admin/actions/weighing/d60ed44f-7cea-4478-b0de-480800fbce3d/change/) and save it as a favorite in your browser. Then you just have to click and you can add a new weighing for the given subject.

**Comment by rossant** [comment]
@nsteinme @northerlywind does the proposed solution above would work?

**Comment by northerlywind** [comment]
It's fine, it's not a necessary feature. I am fine with closing this issue
if it's not going to be a feature that is used by many.

Julie

**Comment by rossant** [comment]
OK, feel free to reopen if needed
