### ISSUE TITLE
Adding weighing and water restrictions for other people's mice

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx#240]
It would be very useful to be able to add water restrictions, etc. for other people's mice.  At the moment on some panels one can only see one's own mice.  Perhaps we could have a 'show all' check-box next to the subject drop-down, or maybe just show all mice but with the user's mice at the top of the list?

**Comment by nsteinme** [comment]
Agreed, Cyrille are either of these options feasible?

**Comment by rossant** [comment]
The second option should be doable.

**Comment by rossant** [comment]
Done
