### ISSUE TITLE
allow water restriction/water administration/weighing to display only mice for given user (default ourselves, like in subjects?)

### ISSUE THREAD

**Issue by petersaj** [cortex-lab/alyx#241]

**Comment by nsteinme** [comment]
To clarify, you mean in the list view (like here http://alyx.cortexlab.net/admin/actions/weighing/) not in the "add new" page, right?

**Comment by petersaj** [comment]
yeah - so for example to end date on the water restriction, it would be nice to default showing just your own mice. The water administration I guess doesn't matter since one would never have to go into an entry there, you'd only create a new one... but speaking of that - if it's possible it might be nice to be able to administer water from the mouses subjects page, like there's a way to add a surgery via the subjects page?

**Comment by petersaj** [comment]
secondary request: it might be nice to link the water restriction and administration pages somehow - so that you see the list of all your animals on water restriction and how much water they need and quickly give water to them without having to flip pages

**Comment by rossant** [comment]
Closing this -- the first suggestion is done. Could you use only 1 suggestion per issue, and open new issues if needed? Thanks!
