### ISSUE TITLE
Make subjects non-editable in subject request view

### ISSUE THREAD

**Issue by petersaj** [cortex-lab/alyx#245]
at the bottom of adding a subject request, there's a 'subjects' section, is that supposed to be used by the person fulfilling the subject request or something? if it's there by mistake then good to remove

**Comment by nsteinme** [comment]
It shows the subjects that fill the request when they are added to it. But
you shouldn't be able to create new subjects here, and it shouldn't be
editable for existing subjects. Cyrille could it just be a string with the
subject name, click-able to go to the edit page for that subject? Or
perhaps show all the same things as currently, but none of the fields
editable?

**Comment by rossant** [comment]
Done.
