### ISSUE TITLE
'adverse effects' section doesn't give a dropdown list of subjects

### ISSUE THREAD

**Issue by petersaj** [cortex-lab/alyx#246]
and actually the whole thing of 'add adverse effects' is a little weird - it looks like a subjects page... but shouldn't it just be the name of the animal, and what the adverse effect is? and actually I'm unable to successfully add an adverse effect

**Comment by nsteinme** [comment]
This section is just a view of the subjects with adverse effects - if you want to write in adverse effects, go to the subject's page and look under "outcomes". I will close this but re-open if I misunderstood?

**Comment by petersaj** [comment]
ah - so there probably shouldn't be an 'add adverse effect' button on that page then?

**Comment by nsteinme** [comment]
True, open new issue to remove it?
