### ISSUE TITLE
water req calculation not matching spreadsheet

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#248]
@laurax452 and @k1o0 report that the water req numbers don't match, though the age, gender, reference weight, implant weight, and zscore all match. 

The code for the calculation that alyx does is here: https://github.com/cortex-lab/alyx/blob/master/alyx/subjects/models.py#L245

Could someone compare with what the spreadsheet is doing to track down the discrepancy?

**Comment by nippoo** [comment]
Are we using the same reference weights? I feel like we're using updated ones
