### ISSUE TITLE
See/plan mouse stock

### ISSUE THREAD

**Issue by petersaj** [cortex-lab/alyx#249]
it might be nice to see numbers of mice which are available to be used right now to pick one for today / plan the next couple weeks / talk to Charu about future needs (in just a 'mouse line = number of mice available to do surgery on right now' format). It might also be nice to have a report to charu that estimates how many mice in a given timeframe you'd want so she can set up breeding (i.e. "I'll need 1 mouse per month starting in June")

**Comment by nsteinme** [comment]
If we can get really specific about what numbers you want computed for each mouse line, it should be simple enough to write something that computes them and exports to a google sheet, for instance. 

You know that you can sort by "stock" in the subjects view, right? That's where I would go to pick one for today. 

P.S. Alyx will replace many things but hopefully will not replace talking to Charu ;)

**Comment by petersaj** [comment]
not talking about replacing talking to charu? just having some quick way of seeing stock vs. demand - but if not useful then no problem

**Comment by nsteinme** [comment]
just joking, your message said this would be "used to... talk to charu" but it was a very complex sentence you wrote so perhaps I just didn't follow :) 

I think you have to specify what things to compute and display if this is going to happen?

**Comment by petersaj** [comment]
just for example the number of unclaimed positive mice over 6 weeks old for a given line, possibly in addition to some number representing the demand (e.g. how many of those are expected to be claimed by people). for example, Charu is often saying that we have a ton of extra mice of a given line, and people aren't aware at a glance of what's in over/underproduction

**Comment by nsteinme** [comment]
Ok, good, so this would be a proxy view for "Lines" called something like
"Transgenic availability" and each row would have one Line with the
following columns:
- name of the line (autoname/short name ok)
- number of mice
- number of mice in stock
- number of mice in stock that fit the "all positive" zygosities criteria
and have age>6weeks
- number of active breeding pairs
- number of open subject request mice (i.e. if two subject requests exist
for this like and one is 2/4 and the other is 0/1, this column shows "3" -
the number unfilled)

**Comment by rossant** [comment]
@nsteinme if I write some documentation about how to add new "proxy" views, would you want to try doing this?

**Comment by rossant** [comment]
you can already find examples [here](https://github.com/cortex-lab/alyx/blob/master/alyx/subjects/admin.py#L878-L947)

**Comment by nsteinme** [comment]
Hey Cyrille, in principle I would want to try this. However I discussed
with Kenneth recently that I have to change my priorities to focus less on
alyx development (I know, it has already almost all been on you, but even
so). However I think we'll have a meeting this week or next with some sort
of "alyx super users" group, i.e. anyone in the lab who is interested in
contributing to development, and I will see if we can find someone to
volunteer to work on this and other things. I'll keep you posted about
that. Thanks -

**Comment by rossant** [comment]
no problem

**Comment by nsteinme** [comment]
Hey Cyrille I removed "priority low" from this - it's not exactly priority high but it would help us check the accuracy of data more easily so if it's something that's easy enough to implement in the short term, it would be helpful for feeling confident about going off the sheets.

**Comment by nsteinme** [comment]
Also, I'm compiling a list of things to bring up for tomorrow's meeting, I can include this issue on that list, as something that someone else might be able to work on, if you prefer.

**Comment by rossant** [comment]
I think it would be good if someone else learnt how to add custom views. If no one is interested I can certainly do it.
