### ISSUE TITLE
Set up a cron job on rod to download the backups from cone to zserver everyday

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#254]

**Comment by rossant** [comment]
@nsteinme @nippoo @kdharris101 Currently the backups are saved every day on the EC2 instance. The idea is to create another cron on our server (rod) to download the backups from EC2 onto zserver. The question is how to handle this?

1. Download the entire backup folder on zserver and overwrite it every day
2. Download the entire backup folder on zserver and give it a unique name every day, like `backup-2017-04-27.gz`. Every one of these snapshots will contain the user-friendly dump of *all* previous days. It's a quadratic growth but it shouldn't be a problem.

**Comment by nippoo** [comment]
3) download just that day's folder, ie `scp cone:/backups/$DATE/ /mnt/zserver/$DATE/` and make sure it's run after the backup job

**Comment by rossant** [comment]
@nippoo how to use scp in cron? With private keys it prompts a passphrase so it doesn't work. We could use a key without passphrase but I guess it's not secure?

**Comment by rossant** [comment]
https://serverfault.com/a/318481
@nippoo is this an adequate strategy?

**Comment by rossant** [comment]
It looks like it worked, closing.

**Comment by nippoo** [comment]
Yeah. I was literally going to suggest that! Make it a user with no write privileges and ideally an scponly shell so even if it gets compromised you shouldn't be able to login to bash.
