### ISSUE TITLE
permissions for changing responsible user of a mouse? 

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#256]
Is it possible to set a permission specifically for changing the responsible user field of a subject? Charu would like this to only be possible for her, or more ideally it should only be possible for the responsible_user to change their own mice to have another resp_user - no one else can change it for you. Does it make sense? Not sure if this is possible.

**Comment by rossant** [comment]
That should be doable. When saving a subject, there is a test. If the responsible user changes, raise an exception unless the logged user is Charu or the old responsible user is the logged user?

**Comment by nsteinme** [comment]
Yep, sounds correct.

On Apr 28, 2017 8:55 AM, "Cyrille Rossant" <notifications@github.com> wrote:

That should be doable. When saving a subject, there is a test. If the
responsible user changes, raise an exception unless the logged user is
Charu or the old responsible user is the logged user?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cortex-lab/alyx/issues/256#issuecomment-297933306>, or mute
the thread

**Comment by nsteinme** [comment]
Also might be worth introducing, if there isn't already, the concept of
"stock manager" user - that's settable in settings, and determine whose
mice show up for the "stock" filter, who gets emails about subject
requests, and who has this permission.

**Comment by rossant** [comment]
To be clear, which one of these options you want:

1) any user (including Charu) can only change the responsible user on their own mice
2) any user (excluding the stock managers) can only change the responsible user on their own mice, but the stock managers have no restriction and can change the responsible user from any user A to any user B

**Comment by rossant** [comment]
done (1 is done, if you want 2 I'll do it in the stock managers request)

**Comment by nsteinme** [comment]
I'm not sure this works? After updating to the latest github code on cone, I was still able to "claim" a mouse from Charu.

**Comment by rossant** [comment]
It might be fixed now that the stock managers bug has been fixed?

**Comment by rossant** [comment]
@nsteinme is this fixed?

**Comment by nsteinme** [comment]
Yes I think so -
