### ISSUE TITLE
use historical z-score for historical weight thresholds

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#257]
Not sure how much this would take to implement, but for the weight plot, when showing the orange and red curves (and coloring the plot), it should ideally compute for each date what the weight thresholds would have been at that date. In other words, for the last water restr that preceded that date, which will have a different subj_zscore than the current water restr. The reason is that for some mice, if their zscore goes up when they are put back on water restr, then it colors the plot all red and makes it look like the mouse was too light, when really it was doing fine to the best of our knowledge at that time. Does it make sense?

**Comment by rossant** [comment]
Are you saying this was a bug? I might have just fixed it. For example, one plot was as follows previously (black=period of water restriction):

![image](https://cloud.githubusercontent.com/assets/1942359/26204049/db10df5a-3bdd-11e7-8c3a-184cb30a03a3.png)

With the upcoming changes, it looks like this:

![image](https://cloud.githubusercontent.com/assets/1942359/26204045/d5fc1aa2-3bdd-11e7-875c-cfc28e0be19b.png)

Is this correct?

**Comment by nsteinme** [comment]
Yes! I think that's correct. @laurax452 could you check this? 

Minor additional request, is it difficult to skip plotting the lines when the subject isn't on water restriction? Perhaps ideal would be for the orange and red lines to go away entirely during non-restricted periods, and for any weighings during that time to be represented as points (like circles maybe) rather than as a connected line. @k1o0 @laurax452 thoughts?

**Comment by rossant** [comment]
could you give me good examples of mice where the plot should be sensible, to test the new version (i.e. orange and red lines should be visible, there might be expected periods of under-the-limit weight, etc.)
