### ISSUE TITLE
Remove mother/father fields from Litter?

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#26]
At the moment, a Litter has a mother and a father. Also, subjects have a litter. So it's theoretically possible that we have data inconsistency in the database where a litter has a mother, but the mother's litter is unassigned or is another litter...

I think it would be simpler if a litter had *read-only* fields mother and father which would be the oldest female/male subject among all subjects belonging to the litter?

**Comment by rossant** [comment]
OK please explain me what a litter is :)

**Comment by rossant** [comment]
Ahh never mind I found the appropriate translation I get it :)

**Comment by nsteinme** [comment]
haha, ok. A set of siblings that were born together. Your son is a "litter of size one", if you'd had twins they'd both be members of the litter, you and your wife are the parents of your current litter and any future ones :)

**Comment by rossant** [comment]
thanks :)
