### ISSUE TITLE
Stock manager user

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#261]
settable in settings, and determine whose mice show up for the "stock" filter, who gets emails about subject requests, and who has this permission.

**Comment by rossant** [comment]
Should be as simple as:

```python
class StockManager(Model):
    user = OneToOneRelation(User)
```

**Comment by nippoo** [comment]
Wouldn't this be easier with a `manages_stock` boolean in the User table? Would probably need to subclass `auth.user` though

**Comment by rossant** [comment]
Yes that's another possibility but it seems that subclassing auth.user is quite tricky.
