### ISSUE TITLE
alyx_ro does not work on alyx_dev for SQL access? 

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#265]
I get 'FATAL: no pg_hba.conf entry for host "128.40.198.136", user "alyx_ro", database "alyx_dev", SSL off' using the same connection code that does work for database "alyx". I checked alyx-dev/alyx/alyx/settings_secret and I think I do have the correct port number (it is the same for alyx and alyx_dev), not sure whether any other connection settings should be different.

**Comment by rossant** [comment]
Ah, I had to do a bunch of magic incantations with psql permissions on the alyx database for it to work. Eventually it worked. The same thing needs to be done on alyx_dev. If you connect with the ubuntu user and do sudo su postgres and then psql, you should be able to use the up arrow to find out what I have done... Basically you have to do `\connect alyx_dev` and then run the various GRANT and ALTER commands. @nippoo should know better... I can't try myself until tomorrow.

**Comment by nsteinme** [comment]
Ok, I tried this quickly without success, here are all the commands I could
find in the history:

alyx_dev=# ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES
TO alyx_ro;
ALTER DEFAULT PRIVILEGES
alyx_dev=# GRANT CONNECT ON DATABASE alyx_dev to alyx_ro;
GRANT
alyx_dev=# GRANT USAGE ON SCHEMA public to alyx_ro;
GRANT
alyx_dev=# GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO alyx_ro;
GRANT
alyx_dev=# GRANT SELECT ON ALL TABLES IN SCHEMA public TO alyx_ro;
GRANT

I still get the same error trying to connect though.

**Comment by rossant** [comment]
@nippoo any ideas?

**Comment by nippoo** [comment]
fixed! needed to add / modify that line in pg_hba.conf to allow access to other IPs for that database on that user.
