### ISSUE TITLE
no longer get an email when a new animal gets assigned from a mouse request

### ISSUE THREAD

**Issue by petersaj** [cortex-lab/alyx#267]

**Comment by nsteinme** [comment]
Could you add your email address and then try again? Go to the home page,
show the "IT Admin" section, and click users. Then edit yourself to have an
email address.

**Comment by petersaj** [comment]
I added an email address tried assigning it to someone else and
re-assigning about a half hour ago, haven't received yet

**Comment by nsteinme** [comment]
Was that with a new subject request? I'm not sure how it works, maybe you
only get one email for a given subject request, ever. We can re-think how
it should work, if it isn't working in the best way yet.

**Comment by petersaj** [comment]
I assigned to charu and had charu re-fill the request with the mouse, still
didn't get the email

**Comment by nsteinme** [comment]
Ok, I will test this.

**Comment by nsteinme** [comment]
K, we think this is working after all now. Closing -
