### ISSUE TITLE
accept other versions of ISO 8601 for date/time

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#27]
Matlab likes this version of ISO8601:
`'yyyymmddTHHMMSS'        20000301T154517 `
(looks like it is valid, on wikipedia)

Could we accept this? And/or, could you update the date/time error message? Currently it is:
```
Datetime has wrong format. Use one of these formats instead:
YYYY-MM-DDThh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z].
```

Would be great if, for helping future users, it said:
`In matlab, use datestr(myDate, 30)`
(if you can accept the format at the top of this issue, or)
`In matlab, use datestr(myDate, 'yyyy-mm-ddTHH:MM:SS')`
(if you want to stick with current formats)

**Comment by rossant** [comment]
This is for the REST API right?

**Comment by nsteinme** [comment]
Yep
