### ISSUE TITLE
import issue with ai32.pv

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#273]
For some reason the mice with birth date march 22 of this line correctly got assigned BP_001, but the ones with birthdate Feb 26 did not, though in the google sheet it appears to be indicated in the same way. Compare [here ](http://alyx.cortexlab.net/admin/subjects/subject/?line__id__exact=2ca12818-f9ca-4522-a555-51e95ee5bbdf&responsible_user=stock ) and [here](https://docs.google.com/spreadsheets/d/1tG-5Pc-569J4g6h9_lX2PCgrfKNgtOY2Fahk9FHSNoU/edit#gid=2050791825).

**Comment by nsteinme** [comment]
also some of the hidden rows do have death dates but still appear on alyx as alive. I am assuming you did total_reset -R yesterday, but maybe you didn't and that's just the problem.

**Comment by rossant** [comment]
Is this fixed?

**Comment by rossant** [comment]
@nsteinme

**Comment by nsteinme** [comment]
No, it isn't actually. Also the "stock" filter appears to be broken, guess I will make a separate issue for that. 

Here's screenshots of the problem:
![image](https://cloud.githubusercontent.com/assets/7590975/26035213/ca814938-38c0-11e7-8939-f2008cea3109.png)

![image](https://cloud.githubusercontent.com/assets/7590975/26035220/e25a09fa-38c0-11e7-8f37-be96851ba102.png)

You see in the sheet that BP num is 1 for all four of those mice, but in the alyx admin view only two of them, the ones from litter 5, got that breeding pair.

**Comment by nsteinme** [comment]
Looking at the CtTa line, it appears that the issue is more generally that only the LAST litter belonging to a breeding pair gets added to that breeding pair. This suggests that for instance each addition of a litter to a BP may be overwriting the last, rather than appending.

**Comment by rossant** [comment]
Thanks for the diagnosis, very helpful. Should be fixed now, let me know.

**Comment by rossant** [comment]
closing, feel free to reopen if there are further problems
