### ISSUE TITLE
problem with users? crash on adding surgery

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#274]
Created and tried to add a surgery, got this crash message. So far as I can tell the surgery was not created. 

![image](https://cloud.githubusercontent.com/assets/7590975/25782229/a34976ba-333e-11e7-8647-5e0d56b7cd28.png)

**Comment by nsteinme** [comment]
"nick" will have been the user both in the "Users" field, and also as the logged-in user in this admin interface instance. I guess it is probably the Users field that had the problem.

**Comment by rossant** [comment]
Should be fixed, try again? (already updated alyx on cone)

**Comment by nsteinme** [comment]
thanks, works!
