### ISSUE TITLE
Block access outside of UCL

### ISSUE THREAD

**Issue by kdharris101** [cortex-lab/alyx#275]
@rossant 

For security, can we restrict access to Alyx to UCL IP addresses? 

I guess we don't want to do this for access to cone as a whole, since it also runs the neuropix wiki. But can we do it for Alyx? A hack of the database would be a disaster.

**Comment by rossant** [comment]
Yes, I think we can set up IP restrictions in apache2 just for alyx. Can someone give me the range of IP addresses to allow? I should also add my own (static) IP.

**Comment by rossant** [comment]
https://httpd.apache.org/docs/2.4/en/mod/mod_authz_host.html

**Comment by kdharris101** [comment]
Does this page have the required information?

https://www.ucl.ac.uk/isd/services/get-connected/wired/about/ip-addresses

**Comment by rossant** [comment]
Yes, thanks!

@nippoo I've tried to add `Require ip` directives but it doesn't appear to work (I can still access alyx from outside UCL). Even doing `Require all denied` in various places doesn't seem to have any effect, even after restarting apache2! Let me know if you have any ideas...

**Comment by nippoo** [comment]
Hmmm

I can't SSH from here but something like this? Must be inside the <Directory> blocks

   AllowOverride None
   Order allow,deny
   allow from 192.168.0.0/24

**Comment by nippoo** [comment]
Must be inside the `<Directory xxx>` blocks

**Comment by rossant** [comment]
thanks @nippoo ! that worked.
