### ISSUE TITLE
error about changing responsible user should not occur when creating a subject

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#277]
I don't think people will commonly be creating subjects, but they should be able to do it - currently it gives an error because they try to set the resp user to themselves. This check should only happen on updates, not creations. 

![image](https://cloud.githubusercontent.com/assets/7590975/25824447/661dcb02-3437-11e7-97a5-e94e509096ff.png)

**Comment by nsteinme** [comment]
@mkrumin

**Comment by rossant** [comment]
fixed

**Comment by mkrumin** [comment]
I am reopening this issue, because currently anybody can change the responsible user for any animal. Feels related to the fix. I think for existing animals only a small subset of people (currently only Charu?) should be able to change the responsible user.

**Comment by rossant** [comment]
will be fixed in the next update (currently planned on Monday morning)
