### ISSUE TITLE
Returning animals back to my name

### ISSUE THREAD

**Issue by charureddy** [cortex-lab/alyx#281]
Hi Cyrille,

I've noticed this issue - Someone makes a subject request, and I assign a stock animal to them. When they transfer the animal back to my name, the animal seems to return back to subject request from that person. This really confuses me because it makes me think that I never transferred the animal to this person in the first place. 

Charu.

**Comment by nsteinme** [comment]
Just had a brief chat with Charu - to be clear, the confusing part is that the subjectrequest now appears open again, even though they don't want another mouse. What should happen is that, if a user gives the mouse back to charu, and they do not want another one, then they should delete the subjectrequest or reduce the number of mice they are requesting. The problem now is, Charu didn't hear about the subject coming back to her, so she doesn't know that the now-open subject request is the same as the old one. So we suggest the following: any time a subject changes responsible user, an email goes to the new responsible user (even if there is no associated subject request). Does it make any sense?

**Comment by rossant** [comment]
So to be clear: the only requested change on my end here is to send an email to the new responsible user whenever a subject's responsible user changes? If so this should be done but it is untested (I haven't updated the repo yet).

**Comment by nsteinme** [comment]
yep, thanks

**Comment by rossant** [comment]
closing, feel free to reopen if there are further problems
