### ISSUE TITLE
Only specific superusers can delete things?

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#286]
Charu, @nsteinme, @rossant ?

**Comment by nsteinme** [comment]
Did you just ask yourself what you think about this? :) 

I think it's good to be able to delete things in general - lots of things might be deleted accurately like water administrations, subject requests, weighings, even surgeries if you make an error in the record somehow. But I think we should just identify things that people shouldn't delete and take that permission away from them. I think it's: 
- subjects 
- lines
- litters
- breeding pairs
- all the "data that changes rarely" and "other", especially sessions and experimental data (we want it to be impossible to maliciously delete experiments). 

Is it possible to copy permissions from one user to another? If so then Matteo, Kenneth, and Charu can go through and make these decisions once for some user, then can copy them over to the other users.

**Comment by rossant** [comment]
I proposed a list of users who could be allowed to delete stuff and I included myself in ;)

Yes please just tell me here the list of models that *can* be deleted by anyone and I'll do it. All other models won't be deletable by anyone except a few select users (Charu etc.).

**Comment by nsteinme** [comment]
Yes, that's a better way. Ok, users CAN delete: surgeries, water administrations, water restrictions, weighings, subject requests. I think that's it, at least for now. @kdharris101 ?

**Comment by kdharris101** [comment]
Sounds good.

**Comment by rossant** [comment]
done
