### ISSUE TITLE
sort subject dropdown in 'add water administration' as in other pages

### ISSUE THREAD

**Issue by petersaj** [cortex-lab/alyx#291]

**Comment by rossant** [comment]
done

**Comment by petersaj** [comment]
sorry I meant sorted like in the other ones with the user's mice listed first instead of all mice alphabetically

**Comment by rossant** [comment]
I think it was @nsteinme who wanted to see the mice in water restriction first

**Comment by nsteinme** [comment]
Btw andy the code at alyx.cortexlab.net may not be updated - try
alyx-dev.cortexlab.net/admin (your password will be 123) to check newest
features. Could you check it there and see whether it's still not what
you're asking?

**Comment by petersaj** [comment]
actually on that one it's worse - maybe they're sorted by alphabetical
user? my animals are way low down on that list in the 'add water
administration', whereas in the regular alyx they're under a bunch of
armin's mice

**Comment by nsteinme** [comment]
Ok, so which of these two should it be:

1) First your mice that are on water restriction alphabetically, then the
rest of your mice alphabetically, then the rest of anyone's mice that are
on water restriction alphabetically, then all the rest of the living mice
alph.
2) First your mice that are on water restriction alph., then anyone else's
mice that are on water rest. alph., then the rest of your mice alph., then
all the rest of the living mice alph.

Or something else? Sorry to be pedantic but I imagine there is confusion
about what exactly you're asking for. It is clear, right, that whereas a
weighing is a sensible thing to do for any mouse, a water administration is
only sensible to do for a water restricted mouse?

**Comment by petersaj** [comment]
in my experience working with alyx, my favorite thing for 'add water
restriction' would be listing all your water restricted mice in
alphabetical order, then everyone else's water restricted mice in
alphabetical order

makes sense to me that you shouldn't be able to administer water to
non-water restricted mice, and it makes it easier to see your own mice
first, and if your mice are listed in alphabetical order it'd make it
easier to parse since they're not jumping around in order when you do other
things on alyx

**Comment by rossant** [comment]
@nsteinme are you ok with @petersaj's suggestion?

**Comment by nsteinme** [comment]
Yes absolutely! I think it's the same as my #2, except excluding all the
non water restricted mice at the end (I don't think it is too critical
whether they are there or not).
