### ISSUE TITLE
death dates not importing properly? 

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#292]
It looks like some (or maybe all) death dates have not been imported from the transgenic sheets properly. For instance in the Camk2a-tTa line, subjects CtTa_0035, 36, and 38 all have death dates from a month ago. But they are all alive in alyx. This is an important thing to get right!

@charureddy @laurax452

**Comment by rossant** [comment]
I think this should be fixed now. I was importing "death date" but the column name was "Death date". You can test locally to be sure. It will be fixed on the server the next time we do total_reset (not now!).

**Comment by nsteinme** [comment]
Could you do a total_reset on alyx-dev to check? Also is it not
case-insensitive? I might have had it uppercase in some and lower case in
others?? Sorry I didn't think hard about that. Probably all column names
should be case insensitive...

**Comment by rossant** [comment]
I don't know if we can have it case-insensitive, the way it works is that you ask for a column name and it returns it. If the case is wrong then it assumes the column doesn't exist. It looks like it's almost always correctly capitalized though no? 
It's currently reimporting alyx-dev.

**Comment by nsteinme** [comment]
uh, ok. I will try to check all the cases tomorrow to make sure then.
Thanks -
