### ISSUE TITLE
potential privacy issue

### ISSUE THREAD

**Issue by mkrumin** [cortex-lab/alyx#295]
Currently, this page: http://alyx.cortexlab.net/users is accessible without logging in, even from outside UCL, which I guess is not intentional?

**Comment by rossant** [comment]
yes, I think it will be dealt with #275

**Comment by nippoo** [comment]
It was an intentional choice to make this API page unauthenticated. So potentially you could login and select your mouse in one single dialog box. This was in response to an @nsteinme suggestion ages ago. But it's not being used right now it seems...
