### ISSUE TITLE
default subject Source should be "Cruciform BSU" 

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#296]
when importing and creating new subjects. This Source was known as "in-house" previously, but we've renamed it on the current alyx. 

I will put both this and the protocol issue to high priority since it would be good to have them before final import (friday?). I guess that there will be some way to fields of many subjects at once though, after things are live, yes? I guess ultimately I could go into cone and psql and issue some SQL update command or something. 

Btw both this default and default protocol number could be settings somewhere if we are thinking about how to make alyx generic for other labs.

**Comment by rossant** [comment]
Yes you can issue SQL udpates at any time. I would just suggest to do a full psql backup before any significant update, and also first trying the SQL commands locally and/or on alyx-dev. Maybe we should write down a checklist on the cortexlab wiki to avoid any problem.

**Comment by rossant** [comment]
This is done
