### ISSUE TITLE
Notes implementation on alyx

### ISSUE THREAD

**Issue by petersaj** [cortex-lab/alyx#299]
From our discussion yesterday, here's how we envisioned the user experience of taking notes on alyx: 

- within each object (not sure nomenclature - most commonly this would be a 'subject' or 'session') there is an 'enter note' field

- a note can be typed into that box, and on pressing enter it will be saved with a timestamp and all previous notes will be displayed in list form. something like:

> 10/5/2017 13:01:04 - mouse is doing well at the task
> 10/5/2017 13:01:06 - mouse is doing poorly at the task
> enter note: [                 ]

- this has the benefit of being able to go back and add notes to old sessions, e.g. when analyzing retinotopy the day after the experiment, you can go back to that session:

> 10/5/2017 13:01:04 - I have a good feeling about this retinotopy
> 11/5/2017 10:00:00 - this retinotopy didn't work

- it also has the benefit that there can be general comments about a mouse not tied to any particular session, e.g. in the 'subject' instance, you can write 

> 11/5/2017 13:01:04 - tail fell off, from this point forward there is no tail

- being able to hit 'enter' to save each note individually would be particularly useful because then the user wouldn't have to scroll down and hit 'save' for each note

- there was a brief discussion about notes as tables but I don't know how those things work so not sure what that would entail or what would be best

**Comment by nsteinme** [comment]
Seconding all this, sounds great! Except your mouse's tail problem, that doesn't sound great at all...

If there is a notes table, how bad would it be to have the foreign key be to an _arbitrary_ other table? That way it could be a note about a subject or a session or anything else (even another note) and you could just filter based on whichever object you're looking for. Dunno, I'm sure it's bad practice for some reason. In any case as Andy says, the main target of notes will be Subject and Session.

**Comment by rossant** [comment]
The following models already have a "notes" field which may be obsolete after this issue is done:

Supplier, Appliance, Subject, SubjectRequest, Littern BreedingPair, Source

Should we get rid of this field in these models?

**Comment by nsteinme** [comment]
Maybe keep it for Subject because it appears prominently in the Subject
list, where we won't try to display all the many notes that might be made
about the subject. Could change the name of the field from "notes" to
"summary" or "description" or something?

Should also stay for Subject request, since this text goes in the email
that's made right on creating the SR, could rename it here to "request
details" or something.

I think for the other ones it would also make sense to change them to
"description" - you can imagine this as being different from "notes" you
might then also make later.

I think in the end I'm suggesting to keep all of those fields but rename
them all to "description" (this can also work for SubjReq).

**Comment by rossant** [comment]
I'm starting to implement this. There is a new Note model that is linked to any instance of any model. It's possible to do that with django, it's called *generic foreign key*. There are drawbacks but it seems to work. Then we can add all notes associated to a given object, e.g. a subject, like with other types of relationships. Here's what it looks like at the moment:

![image](https://user-images.githubusercontent.com/1942359/27286534-d0591dd4-5500-11e7-93c3-8d164afdb6f8.png)

You can click on "Add another note" to add many notes at once. Then you need to press one of the "Save" buttons to save your notes. It's not exactly what you want but it's a start. If you really want to improve this, I can try to implement the "enter" shortcut but it's not very easy (need to write some Javascript).

**Comment by nsteinme** [comment]
Looking great! Maybe after the note is created it can become the
non-editable version of the inline?

I will add a feature request here that's probably not best to try to
implement immediately, but if it helps to plan: it would be really useful
to be able to also have images as notes. Particularly if you can do things
like drag and drop the image in, or copy/paste it, and view a thumbnail of
it in the list of notes and click on the thumbnail to get a larger version.
I realize that's probably substantially more complicated but it'll be super
useful to, e.g., have a photo of the mouse's implant in a Subject note, or
a graph of the behavioral performance in a Session note, etc. It's a way to
get a lot closer to using this like a "lab notebook", where you'd typically
tape images in. Anyway just a thought for now.

**Comment by rossant** [comment]
> Looking great! Maybe after the note is created it can become the
> non-editable version of the inline?

Yes, but it will make things even more complicated if we want to have "asynchronous form validation" without refreshing the page. If the current workflow is fine, then we can do this though.
