### ISSUE TITLE
Add some unit tests

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/alyx#3]
... there aren't any for the API, which should be tested with real data

**Comment by rossant** [comment]
See https://github.com/django/django/blob/master/tests/modeladmin/tests.py to test the admin interface

**Comment by rossant** [comment]
Done! There is now a minimum automated testing procedure that just opens all list/change/add pages and check that no error occurs. It uses a subset of our data, anonymized (all names, descriptions, notes removed etc.). Next step is to add more fine-grained unit tests and increase the test coverage. I've opened a new issue.
