### ISSUE TITLE
determine water requirements

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#30]
Ok, this one is slightly complicated. However it's great because it's a bit of a "killer app" - people could immediately want to stop using the spreadsheets for this functionality if it works well here. You can see what we're going for in the spreadsheet I'll send you. The reason people would immediately start using the database for this is that the weight is already logged via software, but then they have to type it into the spreadsheet again. Since I wrote this thing to send it straight to alyx, they will be able to skip that step. 

The amount of water a mouse needs to get each day is determined by a formula. The formula is complicated, will get to it in a second, but it depends on the mouse's weight. So is it possible to auto-calculate this number, given the formula, either on query, or any time one of the input fields changes? 

Inputs to formula: 
startWeight and startDate- weight of mouse at some starting date, when it was on free water
todaysWeight and todaysDate
meanRefWeight and stdevRefWeight at both startAge and todaysAge (these come from a lookup table, and also depend on gender)

formula
```
mouseZscore = (startWeight-meanRefWeightStart)/stdevRefWeightStart
expectedTodaysWeight = meanRefWeightToday + mouseZscore*stdevRefWeightToday
minimumTodaysWeight = 0.7*expectedTodaysWeight; % won't use this here actually
thresholdTodaysWeight = 0.8*expectedTodaysWeight
if todaysWeight<thresholdTodaysWeight
    requiredWater = todaysWeight*0.05
else
    requiredWater = todaysWeight*0.04
end

```

Ok, and actually, it's slightly more complicated than that, too. So best would be if you make a demo implementation of the formula and I'll write the code for the real thing in place of your demo.

This requires: 
1) The ability to auto-compute a field based on some formula. It is possible, right? 
2) Subject needs to get fields "referenceWeight" and "referenceWeightDate". Also, the minor further complication that I didn't put in -  also need a field "implantWeight". 
3) You make a demo implementation of the formula that shows how to access fields of a subject from the function. 
4) Eventually, what are the possibilities for showing a graph in the admin interface?

**Comment by rossant** [comment]
Sure no problem. (1) is possible. (2) could you explain what these three fields are? (3) OK (4) should be do-able

**Comment by rossant** [comment]
@nsteinme never mind I get it. For the reference weight/date, shall it be a foreign key to a `Weighing` instead?

**Comment by nsteinme** [comment]
Let's make implantWeight a field of Subject, units are grams, this is the weight of anything you attached to the subject. 

Actually reference weight/date don't need to be fields at all. We will know the date that the subject was put on water restriction because that will be logged in Other Regulated Procedures table, and the reference weight/date is the subject's last weighing before put on water restriction. So it will be a weight that's in Weighing table, but we can just look it up on the fly.

**Comment by rossant** [comment]
OK, see https://github.com/cortex-lab/alyx/blob/master/alyx/subjects/models.py#L139
Feel free to propose a pull request with the formula
it's still rather untested but once I get the formula I can properly test and debug
