### ISSUE TITLE
"project" table

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#300]
One thing that will be difficult in the current implementation will be finding the sessions you're interested in, in order to view the notes about those sessions. I propose a "Project" table, each row of which has:
- project name (like "pupil correlation by ultrasound")
- list of any users associated (for filtering)
- extended description field, perhaps
- start time/end time

Then there's a many-to-many relationship between Projects and Sessions. So when you run a session, you can put it in any number of projects, and when you go to that project, you'll see those sessions listed there. Optionally expand all notes about all sessions in that project, for example. 

@kdharris101 @petersaj ?

**Comment by petersaj** [comment]
aren't these things already searchable by other terms? for example if I wanted experiments with widefield imaging and sparse noise stimuli and pupil videos on female mice over 6 weeks old from the last two years, it pops those all up?

**Comment by nsteinme** [comment]
You can do an SQL query for those things and get those sessions in matlab.
You could then copy and paste the session URL into the browser to see that
one session's notes, or do a further SQL query about it. So in that sense,
this suggestion is a convenience.

However there might be sessions that you want to link together under a
project heading wouldn't all be returned by any one search, e.g. Mario had
done some 2p imaging with GCAMP-expressing PV neurons then I did some
electrophysiology with ChR2-expressing PV neurons. The mice, lines, rig,
users, etc were all different between the two sets of experiments but we
could still put them under the same project.

**Comment by petersaj** [comment]
it might be nice to have the former be a feature of the website too if
that's possible, search for sessions with given parameters and get a list

**Comment by nsteinme** [comment]
These would be filters on the sessions page. You could make a list of what
filters there should be and make a new issue for it?

**Comment by kdharris101** [comment]
Good idea Nick.

I do worry a bit about an explosion of tables. And an alternative would be to have free-text Tags associated to any session (just text). 

But this is better really.

**Comment by petersaj** [comment]
ok - maybe I'll wait until the planned sessions extensions are made so we
can play around with it and see what other things we want
