### ISSUE TITLE
debug messages for import

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#304]
I should have thought of this earlier, but would it be possible to quickly include messages for the following:
- if a column is requested from a sheet, but isn't found
- if the value in a column cannot be parsed so that it is discarded and not imported
- if any subject from the procedure log doesn't match an existing subject from the transgenic sheets (please output the subject's name, date of surgery, and value in the "nickname in transgenic sheets" column, i.e. the value that didn't match anything)

The first one of these would have picked up the "death date" problem. The second two will help find any smaller problems (maybe the second one is already implemented, anyway). Between them all, if they all pass, the hope is that it means that all information from the sheets does actually get into the database in some form, even if there might still be typos or errors here and there - they wouldn't be the fault of the importer.

Putting this as high priority - if we can get it today it'll give higher confidence that we can "go live" tonight.

**Comment by rossant** [comment]
OK I'll do that today

**Comment by rossant** [comment]
OK done I think, please have a look. There are many error messages and I'm not sure why.

**Comment by nsteinme** [comment]
Great, this looks good. You could suppress "no death date" and "no wean
date" for individual rows - it's not a problem if individual subjects don't
have a wean date or death date - only a problem if they whole column is not
found by the import script.

I do have two specific questions about the results - guess I will email you
about these since it involves subject data.

**Comment by rossant** [comment]
done
