### ISSUE TITLE
A field for 'END TIME' New Surgeries

### ISSUE THREAD

**Issue by ichun0** [cortex-lab/alyx#307]
It will be useful to have an 'END TIME' field when entering New Surgeries. Currently, there is only the field 'START TIME'. Thanks!

**Comment by nsteinme** [comment]
Are you sure you're looking in the right place? This is what I see at http://alyx.cortexlab.net/admin/actions/surgery/add/: 
![image](https://cloud.githubusercontent.com/assets/7590975/26032636/41844d86-3890-11e7-82af-ded712fdef8c.png)

**Comment by ichun0** [comment]
Hmm, okay. This is then a bit confusing... So we actually have two ways to add new surgeries/sessions (?!) One is to go under the main page and select 'Add surgery', and the other (which is what I am doing now) is to just pick the corresponding 'Subject', and do everything there. The latter is more intuitive to me, sure I can use the former approach too.

**Comment by nsteinme** [comment]
Ah ok. The subject-page-method adds the same kind of object, but it's just
showing you a subset of the fields there. So if you do it that way and
click save, then you will get an entry under "past surgeries" for the one
you just created. If you click the orange "change" button next to that, you
will go the surgery's full page, where you can enter the other information
like end time. If End Time is the only other thing you'd want to enter, and
you would like it to be added to the view on the subject page, that can be
done too.

**Comment by ichun0** [comment]
Hmm, I still think it is good to include END TIME in the subject-page-method (instead of, say, location (if we want to stay concise) for surgeries (and possibly sessions). This way, if animal is behaving funny few days after surgery, for example, one can quickly check if it is due to, say, the length of surgery. But this is not on the top of the priority list.

**Comment by nsteinme** [comment]
sounds reasonable - will open new issue for it
