### ISSUE TITLE
Refactor models with BaseModel

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#31]
```python
class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    json = JSONField(null=True, blank=True, 
                     help_text="Structured data, formatted in a user-defined way")
```

**Comment by rossant** [comment]
@nsteinme @nippoo  Which models should have a JSON and UUID field?

Not all models have a JSON field at the moment. All actions have now, but subjects don't, for example.

It also seems that all models should have an UUID field?

In which case we can make all models derive from this BaseModel.

**Comment by rossant** [comment]
There should also be a `BaseAdmin` with a smaller textarea and also custom JSON fields (#5)

```python
class BaseAdmin(models.ModelAdmin):
    formfield_overrides = {
        models.TextField: {'widget': Textarea(
                           attrs={'rows': 5,
                                  'cols': 40})},
    }
```

**Comment by nsteinme** [comment]
What is the situation in which a JSON field is undesirable? Is there a
penalty or cost to having one? If not, or if the cost is low, I vote to
make everything have one.

Certainly Subjects should, e.g. if I decide I want to keep track of coat
color, or whether it was a runt, or whatever else suddenly becomes relevant
that we aren't thinking about now.

**Comment by rossant** [comment]
I don't know if there's a penalty, I don't think so. @nippoo ?

**Comment by nippoo** [comment]
There isn't a massive penalty against JSON fields - I think everything should have them. I've planned to refactor everything with a BaseModel at some point - so this is a good shout! +1

`subjects.models.Species` and `subjects.models.Zygosity` don't have UUIDs at the moment, but to be honest that's something else to change since a laboratory mouse isn't _Mus musculus_ (we should just have a UUID for that as well... the idea was to make it easier to merge databases so you wouldn't have to manually match up species' UUIDs, but, eh.)

**Comment by rossant** [comment]
OK should be done, but upgrading the database was hard. I had to swipe it locally for some reason...

**Comment by nippoo** [comment]
Yep I ended up doing something along these lines when I refactored `BaseExperimentalData` a few months back:

`rm -r ./*/migrations/0*`

and in SQL:

`DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO alyx;
GRANT ALL ON SCHEMA public TO public;
`

Then `python manage.py makemigrations && python manage.py migrate`.

A bit hacky but that's the best way I've found of getting a clean slate for this kind of thing. Multi-app migrations tend to be really sketchy
