### ISSUE TITLE
breeding pair table needs "notes" field, import this from sheets

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#310]
There's a "notes" column in the breeding pair sheet, should import this into a Notes field of the Breeding Pair.

Could we also import columns "Father Genotype", "Mother Genotype", "Animal # male" and "Animal # female" into json fields with those names? Just in case Charu decides she wants to see this information in alyx later.

**Comment by rossant** [comment]
The notes were already being imported but the field didn't show up in the "change breeding pair" page -- that is fixed now.

I also added these four fields to the JSON.

**Comment by nsteinme** [comment]
aha, excellent, thanks!
