### ISSUE TITLE
new zygosities rule

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#312]
Here's are a couple new rules. The Ai148-G6f allele probably doesn't exist either. Is this a good way to establish new ones, or should I insert it somewhere and make a PR? The allele I can add manually via admin interface of course. 

```
('Ai148', 'Ai148-G6f', (('GFP,WT', '+/-'), 
                  ('GFP,-WT', '+/+'), 
                  ('-GFP', '-/-'))),

('Ai148.Vg', 'Ai148-G6f', (('eGFP', '+/-'), 
                           ('-eGFP', '-/-'))),

('Ai148.Vg', 'Vglut1-Cre', (('Cre', '+/-'), 
                             ('-Cre', '-/-'))),
```

**Comment by rossant** [comment]
Yes could you make a PR? The file is here: https://github.com/cortex-lab/alyx/blob/master/alyx/subjects/zygosities.py
