### ISSUE TITLE
viewing history information for water restricted subjects

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#319]
The Water Restrictions table is great for seeing today's requirements and stuff. @laurax452 has pointed out that it's often useful to see all the historical data. The historical minimum weight and actual weight are nicely represented in the chart on the subject's page, but there's no way to see all at the same time:
- date
- actual weight
- min weight
- amount of water given in total
- amount of hydrogel given in total
- min water required
- excess given (water+hydrogel-min)

@laurax452 , I'm trying to think, would it be more useful to see these things as a list/table of numbers, or as more plots like the weight plot? E.g. you could have four lines: water, hydrogel, total, and minimum. Maybe a combination, like those two plots for all history, and also a table of all the numbers just for the last week or two.

In any case we need some way to represent all of these things for the history of the subject, all at the same place.

**Comment by laurax452** [comment]
I would personally prefer it as a table of numbers as sometimes the axes can make it difficult to get accurate values from a plot especially as time continues. Also as we have to write the numbers down on the cage cards.
The weighings plot in 'subjects' is great but is completely isolated from the other information it would be ideal if this could be shown alongside water administration history.

Basically we require all the information that is currently shown on the water control spreadsheets in one place...Perhaps it could be a different link in the 'Common' area - called Subject History or Water Control or something that pulls all the information from water admin, water restriction and weighings together. It would be nice to have the add water administration button from this view, particularly for the weekend.
Either the Subject History from the matlab eGUI or the existing water control google spreadsheet could be used for inspiration as to what we'd like.

**Comment by laurax452** [comment]
Can I request that the priority level for this is increased? 
Non matlab users like Charu and BSU staff are still unable to view the history that Matlab users can see via the eGUI; this prevents them knowing the history of a mouse when there are welfare concerns without consulting a matlab user.

Ideally we would want the same view as the eGUI gives us in Alyx- same columns etc. including the ability to scroll through different water restricted subjects (drop down menu). Could be called Mouse Admin or Subject History.

This would be something that Charu, BSU staff etc. should be able to look at to give them an idea of the mouse welfare over time.

**Comment by nsteinme** [comment]
Laura, to help with this could you put a screenshot of what you see in the
matlab gui, so it's unambiguous what columns and views we're talking about?
Thanks -

**Comment by laurax452** [comment]
![egui subject history alk055](https://user-images.githubusercontent.com/27958601/28931620-95e2ed4c-786e-11e7-8201-0747d0842afb.jpg)

**Comment by rossant** [comment]
how is `weight pct` computed exactly?

**Comment by nsteinme** [comment]
measured_weight/expected_weight*100

**Comment by rossant** [comment]
Something like this would work?

![image](https://user-images.githubusercontent.com/1942359/29578258-ee59838c-876e-11e7-85ee-ddb29ac192b5.png)

**Comment by rossant** [comment]
This is live on alyx-dev.

It's probably not ideal but for now I added a link in the water section (*Water history*):

![image](https://user-images.githubusercontent.com/1942359/29578714-8e5cbf92-8770-11e7-83ad-d76d6ad536af.png)

**Comment by nsteinme** [comment]
I got an error trying to bring it up for weller and other mice, e.g.:
https://alyx-dev.cortexlab.net/admin-actions/water-history/b66a6e19-f07b-475e-9798-e6397c07054a/

Is there a way to add the link from the water restrictions list view, i.e.
if you click "water restrictions" on the home page then there's a link in
the row for each subject, or even that clicking the subject's name takes
you there?

**Comment by rossant** [comment]
OK, should be done.

**Comment by laurax452** [comment]
Okay, I've had a look and the tables look nice.
However, I really don't like the location of the information as it is hard to access (I know you highlighted it yourself and said this would be temporary).
Ideally it would be accessible from the main tab. Remember people like Charu/BSU staff would be the main users of this feature, so ideally we want it to be easy for them to move between subjects- as I said- selecting a mouse from a dropdown menu would be ideal- that then brings up this information- so they can scroll through all the restricted mice with ease (default should be all users restricted mice in the menu).

As for the data itself. I like the table- but it would be nice to have the plots as well- we want staff to see at a glance whether the mice are regularly dipping into 70%/80% weight percentages.

One thing that Charu brought up when I showed her this is that she's like to be able to see the whole history for the mouse. 
This includes multiple water restrictions... At the moment whenever you add the new restriction it loses all the  historical water restriction weight information- for example- JL015 was previously on water restriction. It was given free water for a few days (18/8/17-21/8/17) and put back on water restriction.... Now I can only see its weight as a percentage from the new water restriction point- I can't see the multiple dips the animal made in the past below the 80% line- although the past weighing and water administration information has been preserved- see below.

Hopefully it isn't too hard to make these changes? The information in the table itself is good. Thanks :)

![jl015](https://user-images.githubusercontent.com/27958601/29721566-9e1b4db2-89b5-11e7-8368-b816d556a2a5.png)

**Comment by rossant** [comment]
> Is there a way to add the link from the water restrictions list view, i.e.
> if you click "water restrictions" on the home page then there's a link in
> the row for each subject, or even that clicking the subject's name takes
> you there?

I've done this suggestion, is it not enough? I can look into making another view if needed.

> As for the data itself. I like the table- but it would be nice to have the plots as well- we want staff to see at a glance whether the mice are regularly dipping into 70%/80% weight percentages.

Putting the existing plot on the same page is fine?

> This includes multiple water restrictions... At the moment whenever you add the new restriction it loses all the historical water restriction weight information- for example- JL015 was previously on water restriction. It was given free water for a few days (18/8/17-21/8/17) and put back on water restriction.... Now I can only see its weight as a percentage from the new water restriction point- I can't see the multiple dips the animal made in the past below the 80% line- although the past weighing and water administration information has been preserved- see below.

To be clear, you want to fix in the table the 80% weight and weight pct columns, taking into account the past water restriction instead of the latest one?

**Comment by laurax452** [comment]
1. I can't access this that way from the normal alyx, although I saw Nick do it before- I think from the dev version. I can only access through the water history link you provided in that email: in the subject tab. It may be enough if this is put into main alyx (this was a Charu comment).

2. Yes, same page is fine.
3. No, I'd like it to use the restriction that is active at that date. I.e. For new water restrictions it uses the new weight percentages and for the past data (archived?) it uses whichever reference was active at the time- perhaps when a water restriction is ended the data can just be held (read only etc.) and not be altered by any future inputs. For instance in plot form it would show a sudden jump in the 70%/80% lines after a brief break in the line, when the new water restriction values are calculated...
(This issue also occurs with the eGUI, Nick.)

**Comment by rossant** [comment]
1. On alyx-dev, clicking on the subject name links to the table:

![image](https://user-images.githubusercontent.com/1942359/29723123-b9bd5872-89c3-11e7-90a4-fe6c9080c624.png)

It will be live on alyx on the next update timeframe (next Monday in principle).

2. OK

3. OK that's indeed what I had understand.

**Comment by rossant** [comment]
Let me know if it's fixed on alyx-dev! If so I'll probably merge this PR on alyx.

**Comment by laurax452** [comment]
Looks great :) Thanks
