### ISSUE TITLE
some reports improvements

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#322]
Reports system is great!!! They all worked, including email. Here are a few improvements:

- [x] water restrictions report would be improved if it contained also: yesterday's weight, expected weight and %, total water given and excess, and today's water required. Like this:

```
Mice on water restriction:
* Hench since 2017-04-20. Weight yesterday 27.2g (expected 30.0g, 90.7%). Yesterday given 1.02mL (min 0.96mL, excess 0.06mL). Today requires 0.97mL. 
``` 
Or a table format could be easier to read if we can get it to format nicely in an email. 

- [x] mice awaiting surgery should not include any mice that are defined as stock - this would prevent it from sending a list of 799 mice to Charu :) 

- [x] if we choose to send multiple ones daily, would be good to put them all in one email for each person.

- [x] we'll also want to send "actions" to Laura, even though she's not a stock manager... let's figure that out later though. 

- [x] Another report type: your actions yesterday. This would show the same kind of thing you see in the sidebar on the admin home page, like: 
- Created water administration: [string version of WA]
- Updated subject: [subject name] - changed responsible_user. 
 things like that. If it's possible I think this would be really helpful especially in these early days for people to get a clearer sense of what's happening with their data. Could rename existing "actions" report to "todo" if that makes this clearer, or call this new one "your_edits" or something, whatever. 

As far as rollout of this - I think sending the water restriction and surgery ones is great already (pending exclusion of stock on surgery). Let's hold off on actions though - I will be meeting with Charu on Thursday to try to get caught up on entering stock info, and we'll try to go through this and see which of these are actually outstanding versus just need to be ticked off, and go from there.

**Comment by charureddy** [comment]
"To be culled" list from actions report should only include mice with "to be culled" checked but without a death date - if they have a death date, they don't need to be culled anymore!

**Comment by rossant** [comment]
done
