### ISSUE TITLE
update zygosities should prioritize genotype tests over parentage

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#323]
I.e. if the one parent was supposed to be homozygous for Pv-Cre then it decides that the offspring should be heterozygous for it. But if you have done a genotype test on that offspring and got a different answer (like Cre-) then the genotype test is the one to trust. I guess in practice this means running the assignment by genotype tests second and overwriting any results from the hereditary calculation. Ideally it should warn or provide some message if there is such a conflict so we can either fix a broken formula or else ask why it is that this mouse has an unexpected genotype.

**Comment by rossant** [comment]
There are now detailled logging messages about zygosity changes.

In `./manage.py update_zygosities` you'll know see the list of changes, and any conflicting changes are reported as warnings with an orange color in the terminal. You can also do `./manage.py update_zygosities Moniz` to update zygosities of one or several subjects.

However, when a zygosity conflict arises when assigning a litter to a subject (i.e. zygosity was set from genotype test but when parents are assigned to the subject, another zygosity is set), the new zygosity is set nevertheless, which may not be the desirable behavior. What should happen exactly? You could get an error message, but then you'd be unable to assign the litter to the subject. Or it could discard the new zygosity, but I don't know how to display a warning to the user in this case.

**Comment by rossant** [comment]
Maybe we can have a special management command that reports all conflicting zygosities without changing anything, so that people can manually check out what's happening.

**Comment by nsteinme** [comment]
I think we're unlikely to have the case where a mouse has genotype tests
already but doesn't yet have a litter. But if we do, or in any other case,
I think the desired behavior is that genotype tests always take precedence
over zygosities derived from parents. So in that case you'd keep the
zygosities from genotype tests.

**Comment by rossant** [comment]
done
