### ISSUE TITLE
clicking "X total" in search results should bring up all or reflect true number

### ISSUE THREAD

**Issue by northerlywind** [cortex-lab/alyx#326]
Next to the search bar it shows how many results there are and how many total e.g. 4 results (891 total) The "___ total" is clickable but only returns all results for your mice/the default results for that page, not *all* results (e.g. if "891 total" is clicked for subjects, it just brings you to the page for your subjects (e.g. 4 subjects) not all 891.

So, the ___ total should either reflect the correct total for that page, OR clicking ___ total should really bring you to viewing *all* results (OR the total should not be clickable).

**Comment by rossant** [comment]
The problem is that this link refers to the default page, which is not the page showing all results. So I changed the link to "Clear search" to make this clearer.
