### ISSUE TITLE
Local copies of files

### ISSUE THREAD

**Issue by kdharris101** [cortex-lab/alyx#328]
Another question.

When you do a recording, there is usually a copy on the local machine, before it is added to zserver.

Do we want to register this local copy in the database too? 

I think we should only do so if it is guaranteed to stay there .

**Comment by rossant** [comment]
I would say no. When the program decides to save and register a file for good, it copies it somewhere on zserver and tells alyx about it.

**Comment by nsteinme** [comment]
Agreed with Cyrille, and with Kenneth since the local copies are not
guaranteed to stay there - the local hard drives have to be cleared every
once in a while.

**Comment by kdharris101** [comment]
Sounds like we have a consensus: local files are not registered.
