### ISSUE TITLE
store reduced date

### ISSUE THREAD

**Issue by charureddy** [cortex-lab/alyx#329]
We need to keep track of the date when a mouse was marked as reduced. Is it possible to keep track of when this checkbox was ticked? So that I could count how many mice were reduced in a certain date range? This is how the animal facility decides how much to charge us so we need to have this information.

**Comment by nsteinme** [comment]
I can write an sql query for this, even if it's in json presumably (perhaps easier if it's not, though) - just need some way to get the dates.

**Comment by rossant** [comment]
There's a very easy solution that doesn't require a schema change: just using the same system as what we're using when keeping track of nicknames or responsible users. When the checkbox is ticked, you'd see the following in the JSON:

```
{"history": {"reduced": [{"value": "False", "date_time": "2017-05-25T18:40:28.253452+00:00"}]}}
```

This means the checkbox was *not ticked* at that date, just before it was ticked. Would that work?

**Comment by nsteinme** [comment]
Maybe, how easy would it be to sql search over though? For the
nickname/resp_user that's kept more for human-readable reasons, but for
this I'd really like to be able to query it. I guess in the end just
pulling out all the json for 1000 mice (in the long run, not more than
100k), parsing it, and then querying it "myself" is not so bad though, so
if this seems like a good solution, then sounds fine.

**Comment by rossant** [comment]
Forget it, I just added a `reduced_date` field in `Subject` which is automatically filled when the reduced checkbox is ticked. Let me know if you need to make a custom view or something with this information.
