### ISSUE TITLE
add zygosities to "cull subjects" view

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#332]
Here: https://alyx.cortexlab.net/admin/subjects/cull%20subject/

Same column as in Subjects, with the string representation of zygosities. 

It might be helpful in both Subjects and Cull Subjects to save a little space by showing the line's autoname rather than long name - is that easy? If not it's ok, just would save a little column width on that one.

**Comment by nsteinme** [comment]
also for @charureddy

**Comment by rossant** [comment]
done
