### ISSUE TITLE
ability to set lines as inactive

### ISSUE THREAD

**Issue by charureddy** [cortex-lab/alyx#333]
We'd like the ability to set a line as inactive, which just means that it doesn't show up in the dropdown menus when you are selecting a line on any pages (e.g. on the subject create/edit page, or the subject list page). This can be a boolean checkbox field on the Line page to be set manually when a line is retired.

**Comment by nsteinme** [comment]
Also guess there should a filter on the lines list view that defaults to
showing only active lines but can be set to all.

This feature is useful for two reasons: 1) to reduce clutter on the
dropdown selections; 2) to make sure people aren't confused about which
line they want when there are lines with similar names that replaced old
ones.

**Comment by rossant** [comment]
done
