### ISSUE TITLE
rest api endpoint for a specific subject no longer returns water_requirement_total??

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#334]
using an endpoint like /subjects/PC006 used to return a field water_requirement_total. I also don't see this field using the browser version so I don't think it's a matlab problem. Where did this field go?

**Comment by rossant** [comment]
When refactoring I moved the water requirement logic out of Subject into another module. Please give me the list of fields you need in the end point.

**Comment by rossant** [comment]
Is there any error message by the way? I'm surprised it didn't crash, the tests should have caught this.

**Comment by laurax452** [comment]
Ah, ok. We need to be having a conversation whenever anything's going to change in the rest-api :) 

I hope this is the whole list: 
water_requirement_total
water_requirement_remaining 

Also need both of those at the /water-restricted-subjects endpoint.

**Comment by nsteinme** [comment]
whoops this computer was logged in as laura. I think there was no error because the endpoint does return successfully - it's just that my matlab code crashes when it doesn't find the data field it expects. Or more precisely, it doesn't crash but it doesn't work either :)

**Comment by rossant** [comment]
I think the right way to do this would be to add tests in the REST API testing suite that checks that all fields you need are there. A sort of contract-checking. If after some changes a field disappears, the test suite will crash and we'll know about the problem. 

Do you think you could go through e.g. https://github.com/cortex-lab/alyx/blob/master/alyx/subjects/tests_rest.py and propose a pull request? You know better than me what fields you need. You can also do the same in other apps like "actions" etc. Don't worry if you don't know python or if it doesn't pass, I can fix it. What I need is a list of expected fields on every endpoint.

**Comment by nsteinme** [comment]
That's a good idea, I'll do that. 

For water restriction related stuff, I think it's just these two plus the things in #302 when those are implemented. But we use some other ones too so I'll look into that.

**Comment by nsteinme** [comment]
If this is fixed could we update alyx with it tonight or tomorrow morning? People are going to be [reasonably] annoyed/put-off if the matlab stuff is failing yet again. If it's not likely to be fixed that's ok though, but let me know so I can send a warning email.

**Comment by rossant** [comment]
It should all be fixed now, let me know.
