### ISSUE TITLE
Dates in UK format please

### ISSUE THREAD

**Issue by charureddy** [cortex-lab/alyx#337]
Can we please have all the dates displayed in UK format?  DD/MM/YY Thanks.

**Comment by nsteinme** [comment]
Do you mean in places where it says "May 31, 2017" or in places where it
says "2017-05-31"?

The advantage of "2017-05-31" is that it is unambiguous for both american
and british readers, that is why it is the international standard format:
https://en.wikipedia.org/wiki/ISO_8601

**Comment by charureddy** [comment]
When editing a breeding pair or litter, the format changes to '2017-05-3'. It'll be great if we can stick with May 31, 2017' or DD/MM/YY through out.

**Comment by rossant** [comment]
done

**Comment by nippoo** [comment]
YYYY-MM-DD is also great because it makes sorting by date much easier - you can literally sort anything just like any other string or sequence of numbers in ascending or descending order.

**Comment by rossant** [comment]
Yes, I just changed the input format, not the display format which remains YYYY-MM-DD.
