### ISSUE TITLE
improvement to water-requirement endpoint

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#338]
New water-requirement is fantastic. I'm just slightly confused about how to interpret "water_given" and "hydrogel". For most mice on most days, there is both a non-hydrogel water_administration as well as a hydrogel water_administration, or even multiple of each of them. Two possibilities would be ideal:

1) Return two things: "water_given", the total of all non-hydrogel w_a's on that day; and "hydrogel_given", the total of all hydrogel w_a's on that day

or 

2) Return details of all the water_administrations, like happens when you query the Subject:
https://alyx-dev.cortexlab.net/subjects/Reichstein
"water_administrations": [
        {
            "date_time": "2017-05-05T00:00:00Z",
            "water_administered": 1.2,
            "hydrogel": true,
            "url": "https://alyx-dev.cortexlab.net/water-administrations/5afc9e53-a75f-430c-8fdc-04db97679fe2"
        },
        {
            "date_time": "2017-05-06T00:00:00Z",
            "water_administered": 1.16,
            "hydrogel": true,
            "url": "https://alyx-dev.cortexlab.net/water-administrations/06a1493f-1a96-4c66-9299-5648b3bb5319"
        },
        {
            "date_time": "2017-05-07T00:00:00Z",
            "water_administered": 1.23,
            "hydrogel": true,
            "url": "https://alyx-dev.cortexlab.net/water-administrations/319987e3-5976-49c7-9571-eae6df2daa21"
        },
        {
            "date_time": "2017-05-08T00:00:00Z",
            "water_administered": 0.03,
            "hydrogel": false,
            "url": "https://alyx-dev.cortexlab.net/water-administrations/0d5859be-e3cc-4408-a5f2-366004fa577c"
        },

Actually there is a third thing that would be ok: 
3) Skip both those fields altogether, since they can be computed from what's already returned at the /subjects endpoint. 

But number 1 above would be the most convenient to use.

**Comment by rossant** [comment]
done
