### ISSUE TITLE
no orange/red lines in water/weight plot for SF170215

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#341]
Don't know why they don't appear? Adding an implant weight did not resolve it. 

@sfailor @laurax452

**Comment by rossant** [comment]
Do the lines appear on other subjects?

**Comment by nsteinme** [comment]
Yes, see below. Based on the red line being mostly off the plot in Reichstein's screenshot below, I would guess that the problem is that the y-axis isn't scaled by default to include those two lines. But it should be, at least so you know whether the subject is above or below :) 

![image](https://cloud.githubusercontent.com/assets/7590975/26682440/62c0468e-46d8-11e7-8175-7caa7579b795.png)

![image](https://cloud.githubusercontent.com/assets/7590975/26682462/759eb5b0-46d8-11e7-99ea-34ca47896116.png)

**Comment by rossant** [comment]
should be fixed
