### ISSUE TITLE
Permission to change responsible user

### ISSUE THREAD

**Issue by charureddy** [cortex-lab/alyx#343]
Today Lauren was able to take a look at a stock animal (TetO.CtTA_0100) and change the responsible user from me to her. This action should be denied to all uses except stock manager (or else it'll be chaos with people taking any and every animal and stuffing up the stock numbers and allocations). 

Can we please check to ensure that users do not have access to change the responsible user for stock animals? The only way they can acquire a new animal is to make a subject request.

**Comment by rossant** [comment]
This check was only done in the "change subject" view, not on the "list subjects" view. From now on, the responsible_user column will only be editable to superusers and stock managers.
