### ISSUE TITLE
Add alive column in litter list view

### ISSUE THREAD

**Issue by mkrumin** [cortex-lab/alyx#345]
There is apparently something wrong with the calculation of the age of the animals

for example here:
https://alyx.cortexlab.net/admin/subjects/litter/b812b56f-b696-4dcd-b8b5-3b6a50cde099/change/?_changelist_filters=line__id__exact%3D6fc8ff15-493e-45c1-8c1d-7642cf26bc20

Animals are born on Feb-02-2017, and the age is calculated as 12 weeks (It should be 18 weeks today)

**Comment by mkrumin** [comment]
Oh, these animals are already dead. This is not clear from that view. Can we add a column 'Alive' next to the birth date in this view?
Thanks, Nick

**Comment by rossant** [comment]
How do you define whether a litter is dead or alive? What if some mice of the litter are alive and not the others?

**Comment by mkrumin** [comment]
What I meant is when you are 'inside' the litter, and see the list of animals, it would be useful to see for each animal if it is still alive. I think right next to the birth date?

**Comment by rossant** [comment]
done
