### ISSUE TITLE
bug in water_restriction report

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#348]
Below is the report I get for me today for water_restriction, which has a bug: "Weight yesterday" seems to give the reference weighing rather than actually yesterday's weight. This might be related to the fact that there was no weighing for these mice yesterday. So a good solution could be to instead give: "Most recent weighing: XXg (yesterday)" or "... (N days ago)". 

Ok and actually there is another bug: The amount given yesterday does not appear to be correct. I only see one water_admin for Hench yesterday and it was for 1.1mL not 1.3, so I don't know where that came from. Even if it was 1.3, 1.3-1.1 does not equal 0.1. Also let's please do two decimal places on water amounts (but one decimal place is fine on weights). 

So, checklist:

- [x] fix "weight yesterday"

- [x] fix water totals

- [x] round to two decimals for water amounts

```
(alyx) ubuntu@cone:/var/www/alyx/alyx$ python manage.py report water_restriction -U nick --no-email
12/06 15:59:46 [DEBUG] Making report water_restriction.
"Report on 2017-06-12" to be sent to <nick.steinmetz@gmail.com>.

Mice on water restriction:

* Hench since 2017-04-20.
Weight yesterday 32.1g (expected 32.1g, 100.0%).
Yesterday given 1.3mL (min 1.1mL, excess 0.1mL).
Today requires 1.1mL.

* Kendall since 2017-04-20.
Weight yesterday 27.8g (expected 27.8g, 100.0%).
Yesterday given 1.3mL (min 0.9mL, excess 0.5mL).
Today requires 1.0mL.

* Reichstein since 2017-05-04.
Weight yesterday 29.2g (expected 32.3g, 90.4%).
Yesterday given 1.2mL (min 1.0mL, excess 0.2mL).
Today requires 1.0mL.

* Theiler since 2017-05-04.
Weight yesterday 23.1g (expected 23.1g, 100.0%).
Yesterday given 1.0mL (min 0.9mL, excess 0.1mL).
Today requires 0.8mL.
```

**Comment by rossant** [comment]
OK, should be fixed, feel free to try on alyx-dev (already updated).

**Comment by nsteinme** [comment]
Thanks. Water given should be all hydrogel+water (total of all water_administrations) for the previous calendar day. I think it's just using the single most recent one instead.

**Comment by rossant** [comment]
OK, try again?

**Comment by nsteinme** [comment]
* Hench since 2017-04-20.
Weight 1 day(s) ago: 28.8g (expected 32.1g, 89.8%).
Given 59.95mL (min 1.11mL, excess 58.84mL).
Today requires 1.11mL.

I think now you are adding all water_admin's in the mouse's entire
history??

**Comment by rossant** [comment]
Whoops, try again :)

**Comment by nsteinme** [comment]
Looks good to me now!
