### ISSUE TITLE
improve past_changes report

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#349]
Right now past_changes is a bit cryptic, here's what I see for Julie, below. What does it mean exactly? I guess the first two are weighings, but what about the second two? Is there a way to make it more clear without necessarily having to implement specific messages for every kind of change, like maybe for instance, what if it was able to give you the row that you see in the list view? So if you add a surgery it would say: "Added surgery. Subject: Waksman, Date: June 10, 2017, Users: nick, Procedures: ..." I don't know, that's just an idea. Maybe including the type of object, and having slightly more useful "to_string" functions for them is all that's needed. In any case it has to be somehow a little more clear :) 

Another helpful think would be a hyperlink to the object that was changed, so you can quickly investigate if you weren't sure what it means? 

(alyx) ubuntu@cone:/var/www/alyx/alyx$ python manage.py report past_changes -U julie --no-email
12/06 16:17:21 [DEBUG] Making report past_changes.
"Report on 2017-06-12" to be sent to <>.

Your actions yesterday:

* Added "JL012 at 2017-06-11 13:58:29+01:00 (22.6 g)".
* Added "JL015 at 2017-06-11 13:58:30+01:00 (23.9 g)".
* Added "JL012 at 2017-06-11 13:58:19+01:00".
* Added "JL015 at 2017-06-11 13:58:21+01:00".

**Comment by rossant** [comment]
The text is [auto-generated by django](https://github.com/django/django/blob/master/django/contrib/admin/models.py#L90). As you say, it uses the representation of objects, for example [here](https://github.com/cortex-lab/alyx/blob/master/alyx/actions/models.py#L45) for weighings. It's just a matter of improving these representations then. What needs to be improved, Weighing, WaterAdministration, BaseAction (which includes surgeries), anything else...?

**Comment by nsteinme** [comment]
I guess one problem is that they don't identify what kind of action they are - for this past_changes report that information needs to be in there, though maybe it wouldn't need to be for the general case (i.e. for other situations when this __str__ method is employed)? 

Also, for this particular use case, the date is not necessary (though the time is fine to include - preferably without time zone, since that's silly and distracting). 

Anyway, I think besides the ones you listed, it should also report if they created a session or a water_restriction, so those should have something interpretable.

**Comment by rossant** [comment]
OK, feel free to try on alyx-dev (already updated) with --no-email and let me know if there is anything else to change.

**Comment by nsteinme** [comment]
Thanks, looks great. For some reason lots of yesterday's actions don't seem to show up though, not sure why? E.g. for Laura I get nothing at all:
```
(alyx) ubuntu@cone:/var/www/alyx-dev/alyx$ python manage.py report past_changes -U laura --no-email
13/06 14:25:40 [DEBUG] Making report past_changes.
"Report on 2017-06-13" to be sent to <rmhklfu@ucl.ac.uk>.

Your actions yesterday:

```
But on https://alyx-dev.cortexlab.net/water-administrations I can see:

```
{
        "subject": "ALK051",
        "date_time": "2017-06-12T13:14:35Z",
        "water_administered": 0.418,
        "hydrogel": false,
        "user": "laura",
        "url": "https://alyx-dev.cortexlab.net/water-administrations/c872a82c-ff00-4e76-8272-20646f975927"
    },
    {
        "subject": "ALK051",
        "date_time": "2017-06-12T13:14:45Z",
        "water_administered": 0.05,
        "hydrogel": true,
        "user": "laura",
        "url": "https://alyx-dev.cortexlab.net/water-administrations/b05a854b-0477-487e-9d60-b29aec775412"
    },
```

among many others. Maybe has to do whether things were done via rest api? Given that the user is known it seems like those should work/be logged somehow, no?

**Comment by rossant** [comment]
The LogEntry seems to work with the admin interface and not the REST API -- I've opened a new issue.
