### ISSUE TITLE
new filter for subjects view: Breeder

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#352]
It's confusing for people that mice which are breeders (they are a parent in a currently active breeding pair) are listed alongside the other subjects but there's no indication that they're breeders. So if there's a new filter on the subject view called "Breeder" with possible values Yes/No/All, and default state No, then this would solve it. Breeder is true when a subject is either Father, Mother1, or Mother2 in a Breeding Pair that has a start date but no end date (an active breeding pair). 

@charureddy

**Comment by charureddy** [comment]
Can we please prioritise this issue? Mistakes are being made when marking an animal to be culled or when selecting an animal for surgery, because stock/to cull view does not filter out those animals that are part of breeding pairs.

**Comment by rossant** [comment]
OK, can you try on alyx-dev and let me know if it works?

**Comment by nsteinme** [comment]
Looks like it is working to me!

**Comment by charureddy** [comment]
Perfect. Thanks!
