### ISSUE TITLE
Make LogEntry work with the REST API

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#354]
related to https://github.com/cortex-lab/alyx/issues/349#issuecomment-308116731

**Comment by rossant** [comment]
A few links:

https://stackoverflow.com/a/7905253/1595060
https://github.com/django/django/blob/c16aa69101a3722061be4a2ed435865557b99157/django/contrib/admin/options.py#L1447
https://github.com/django/django/blob/5a52d932ef4da8228d82673314341c2c86602248/django/contrib/admin/utils.py#L496
https://github.com/SujaySKumar/django-rest-framework-logger/blob/master/viewsets.py
https://github.com/SujaySKumar/django-rest-framework-logger/blob/master/serializers.py

**Comment by rossant** [comment]
Logging of water admin and weighing creation from REST API is now done (active in next update of alyx). Anything else?

**Comment by nsteinme** [comment]
Awesome :) I think that's good.
