### ISSUE TITLE
Migration script to import baseline data

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#36]
We should have CSV files containing what strains are in the lab, what alleles each line has, etc.

**Comment by nsteinme** [comment]
Specifically, these tables should get preserved across schema changes if at all possible - these are the "one-time-only" type of tables. 

- procedure types
- lab locations
- species
- sources
- alleles
- lines
- strains
- sequences

**Comment by rossant** [comment]
Should be done.
