### ISSUE TITLE
dataset-types in admin interface

### ISSUE THREAD

**Issue by kdharris101** [cortex-lab/alyx#364]
I couldn't find dataset-types in the admin interface.

I guess this is something we are going to want...

**Comment by nsteinme** [comment]
It is under "other" - here is a direct link: https://alyx.cortexlab.net/admin/data/datasettype/

**Comment by kdharris101** [comment]
Yes, it is there but there is no link from the homepage under other to datasettype

If we could put a new section of the homepage for all the models at https://github.com/cortex-lab/alyx/blob/master/alyx/data/models.py that would sort it out.

**Comment by rossant** [comment]
see https://github.com/cortex-lab/alyx/issues/366
