### ISSUE TITLE
Ambiguity of Sessions in drop-down menus

### ISSUE THREAD

**Issue by brykko** [cortex-lab/alyx#392]
When selecting a corresponding Session from a drop-down menu (e.g. adding an ExtracellularRecording, see screenshot below), Sessions are only labelled by their Subject, making it tricky to determine which one should be selected. Is it possible to show a more descriptive label for each session, e.g. including the date/time range?

![screenshot](https://user-images.githubusercontent.com/19981078/31598783-d301fab8-b24f-11e7-87ba-2a6c85e76bda.png)

**Comment by nsteinme** [comment]
Agreed, the session string should have date and time.

P.S. Rich - note that we imagined adding ephys models using the rest api,
in which you would query for the correct session on the basis of subject,
date, etc first. Also note that this particular model (extracellular
recording) is under active development at the moment and very much subject
to change...

**Comment by brykko** [comment]
Sounds good! OK, maybe I should wait for the ephys models to be more fully implemented before testing them out.

**Comment by oliche** [comment]
Np more Ephys models.
