### ISSUE TITLE
New end point(s) for session times and narrative

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx#400]
The experimenter GUI ('mc') has a comments box in each active experiment panel that should be synchronized with the subsession narrative field, i.e. when the user types something in the comments box it is written to Alyx via the 'putData' function.  Every experiment panel has a copy of the Alyx Instance that registered the subsession (which includes the subsession url).

The experiment server ('expServer') should be able to set the session end time while registering the files and the end of an experiment (currently the end time is left unset).

Finally mc also has an experiment log which shows the subject's previous session dates and comments from each session.  This could be retrieved from the database via an endpoint.

My apologies if this is too many requests for one issue...

**Comment by oliche** [comment]
1)The experimenter GUI ('mc') has a comments box in each active experiment panel that should be synchronized with the subsession narrative field, i.e. when the user types something in the comments box it is written to Alyx via the 'putData' function. Every experiment panel has a copy of the Alyx Instance that registered the subsession (which includes the subsession url).

2)The experiment server ('expServer') should be able to set the session end time while registering the files and the end of an experiment (currently the end time is left unset).

3)Finally mc also has an experiment log which shows the subject's previous session dates and comments from each session. This could be retrieved from the database via an endpoint.

**Comment by oliche** [comment]
1) https://alyx-dev.cortexlab.net/docs/#sessions-partial_update
2) https://alyx-dev.cortexlab.net/docs/#sessions-partial_update
3) related to #131 
Moved to #131
