### ISSUE TITLE
GET data using date/time wildcards

### ISSUE THREAD

**Issue by peterzh** [cortex-lab/alyx#401]
Currently I have a bunch of sessions registered on alyx, for example here is one entry
```           subject: 'Beadle'
             users: {0×1 cell}
          location: []
        procedures: "Behavior training/tasks"
              type: 'Base'
            number: []
    parent_session: []
         narrative: 'auto-generated session'
        start_time: '2018-01-08T13:16:23Z'
          end_time: []
               url: 'https://alyx-dev.cortexlab.net/sessions/d1ef95ba-128d-4559-9292-7bbb8cb92415'
```

From the MATLAB interface I would like to get sessions based on the subject, type, and start_time. So for the entry above I can obtain this via MATLAB using the command

```alyx.getData(alyxInstance, 'sessions?type=Base&subject=Beadle&start_time=2018-01-05T10:43:02Z')```

However in practice I would like to obtain this session by only specifying the date and not the time,
```alyx.getData(alyxInstance, ['sessions?type=Base&subject=Beadle&start_time=2018-01-05'])```
This currently does not work. Therefore are there any ways of requesting data from the database using some kind of time wildcard?

Thank you!

**Comment by rossant** [comment]
can you try `start_date=2018-01-05`?

**Comment by peterzh** [comment]
That doesn't work

**Comment by rossant** [comment]
Indeed I can see it doesn't work. It's weird because it should: [the code for this is there](https://github.com/cortex-lab/alyx/blob/master/alyx/actions/views.py#L92-L99). Working on it

**Comment by peterzh** [comment]
Thank you very much :)
