### ISSUE TITLE
Dataset admin interface

### ISSUE THREAD

**Issue by kdharris101** [cortex-lab/alyx#402]
Hi there,

Was just playing around with the datasets in the admin interface. On Alyx-dev I get errors, eg:

`
ProgrammingError at /admin/data/filerecord/
column data_filerecord.exists does not exist
LINE 1: ...epository_id", "data_filerecord"."relative_path", "data_file...
`

or 
`
ProgrammingError at /admin/data/filerecord/
column data_filerecord.exists does not exist
LINE 1: ...epository_id", "data_filerecord"."relative_path", "data_file...
`

On Alyx main, a feature request:

* It would be nice to be able to filter/search datasets by user/name/session, etc.

* Also when clicking on a dataset, it is very slow to get to the "change dataset" page. Also very slow when clicking "change selected session". The reason might be that the session dropdown box on the change dataset page is fill of loads of irrelevant entries

**Comment by rossant** [comment]
Thanks, alyx-dev had not been properly migrated. Should be fixed, could you try again?

What do you suggest to avoid filling the session dropdown box? I think django 2.0 has a way to propose a new type of dropdown box where it is not filled in advance, but autocompletes as you type. It might be worth upgrading at some point.

**Comment by kdharris101** [comment]
Thanks, works now!

Now there is no session link at all in the dataset page - and it is faster.

Maybe instead of a drop-down box we could just have a text field saying which session, with a button to link to an info page about the session. This would mean there is no option to change the session a dataset links to, but I think that is something people would want to do only rarely…

Upgrading to Django 2.0 does sound like a good idea providing nothing breaks!! Upgrading now is also probably a lot easier than upgrading in the future… but it it was slow because of the dropdown box listing every session, would this autocomplete box be any faster?

Finally: the “exists” checkbox on the Dataset page is unchecked for an entry<https://alyx-dev.cortexlab.net/admin/data/dataset/ffdbefde-be6f-42fc-80ea-5120bb5bf5b0/change/>, but I checked zserver and the file is there. I guess this is just because the database doesn’t list exists, rather than a problem with the Django?

Finally finally: did flatiron institute get back to you with details of the globus server? Or should I remind them again?

**Comment by rossant** [comment]
> Maybe instead of a drop-down box we could just have a text field saying which session, with a button to link to an info page about the session. This would mean there is no option to change the session a dataset links to, but I think that is something people would want to do only rarely…

Yes we could do that

> Upgrading to Django 2.0 does sound like a good idea providing nothing breaks!! Upgrading now is also probably a lot easier than upgrading in the future… 

Agreed

> but it it was slow because of the dropdown box listing every session, would this autocomplete box be any faster?

I think so because the list of sessions would load asynchronously, but that remains to be checked

> Finally: the “exists” checkbox on the Dataset page is unchecked for an entry<https://alyx-dev.cortexlab.net/admin/data/dataset/ffdbefde-be6f-42fc-80ea-5120bb5bf5b0/change/>, but I checked zserver and the file is there. I guess this is just because the database doesn’t list exists, rather than a problem with the Django?

All `exists` fields are set to False at the moment. We should think about a way to make sure the exists fields are synchronized to the file system. If some day a file is deleted, the corresponding `exists` should be set to False shortly afterwards I suppose?

> Finally finally: did flatiron institute get back to you with details of the globus server?

no

> Or should I remind them again?

yes please! 

I should also install globus on a cortexlab server, but I don't know which one, and ssh access should be set up for me — we can talk more on Thursday.
