### ISSUE TITLE
Implant weight field in Add water restriction 

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx#404]
Currently the implant weight field is on the subject page. This value should be filled in before a water restriction is started as otherwise the mouse's weight is over estimated.  People are forgetting to fill in this field so could we have it appear on the 'Add water restriction' page?

**Comment by rossant** [comment]
Yes, I think that's [possible](https://stackoverflow.com/questions/17948018/django-admin-add-custom-form-fields-that-are-not-part-of-the-model), I'll have a go

**Comment by rossant** [comment]
Done on the dev branch
