### ISSUE TITLE
Submitting newline characters to narrative field

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx#405]
The comments box in mc is a multi-line text box which now posts its contents to the session narrative in Alyx.  Currently the text is sanitized so that all returns are newline characters (ASCII \n).  When the comment string contains these characters Alyx returns a bad upload command error.  Is there are way of formatting returns/newlines that is compatible with the narrative field?

**Comment by rossant** [comment]
That's weird, could you post the exact error message, as well as the failing POST request if possible?

**Comment by k1o0** [comment]
```
K>> responseBody
responseBody =

    '{"detail":"JSON parse error - Invalid control character at: line 3 column 38 (char 60)"}'

K>> jsonData
jsonData =

    '{
     	"subject": "SS092",
     	"narrative": "This sentance has a...
     return."
     }
     '
```

**Comment by rossant** [comment]
Ah, thanks! So what you need to do, I think, is to escape newline characters in the JSON. So it should look like this instead:

```
K>> jsonData
jsonData =

    '{
     	"subject": "SS092",
     	"narrative": "This sentance has a...\nreturn."
     }
     '
```

**Comment by k1o0** [comment]
Unfortunately savejson can't deal with newline characters and it automatically escapes '\n'! 

```
K>> jsonData
jsonData =

    '{
     	"subject": "SS092",
     	"narrative": "This sentance has a...\\nreturn."
     }
     '

```
I'm not sure what the cleanest way around this would be?  Either something server-side or in alyx.putData something like this:
```
jsonData = savejson('', data);
jsonData  = strrep(jsonData, '\\n', '\n'); % un-escape escaped newlines
```
The second option is far from ideal...

**Comment by rossant** [comment]
I think having `\\n` would be fine, if we need to replace to `\n` maybe we can do it server-side.

**Comment by nsteinme** [comment]
basically we're going to want to display notes on the admin interface with
newlines properly as newlines. If that won't be too hard, then uploading
with the \\n certainly seems most straightforward from this side...

**Comment by rossant** [comment]
Yes I think that's doable, let's try it.
How complicated was it for you to get `\\n` ? out of curiosity what did you have to change in the code to escape the new lines?

**Comment by k1o0** [comment]
The textbox outputs a 2D padded character matrix so the following line joins them with a '\n', which is in turn sanitized by savejson:

```
>>str =

  2×17 char array

    'fdsahjk...       '
    'jfisoifefgfsafhds'

>>str = strJoin(deblank(num2cell(str, 2)), '\\n');
>>jsonStr = savejson('', str)

jsonStr =

    '"fdsahjk...\\njfisoifefgfsafhds"
     '
```

**Comment by rossant** [comment]
that might be a stupid question but what happens if you do 
`str = strJoin(deblank(num2cell(str, 2)), '\n');`
(single backslash) ?

**Comment by k1o0** [comment]
That's what I tried originally.  '\n' is an escape character in the strJoin function so it become a newline character, which then causes an 'Invalid control character' error in savejson.

**Comment by oliche** [comment]
Client code issue.
