### ISSUE TITLE
ImproperlyConfigured at /datasets

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx#406]
Just tried to visit this url https://alyx.cortexlab.net/datasets and am seeing and error:

Could not resolve URL for hyperlinked relationship using view name "dataformat-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
In template /var/www/alyx/alyx/lib/python3.5/site-packages/rest_framework/templates/rest_framework/horizontal/select.html, error at line 15

**Comment by rossant** [comment]
Indeed, thanks for the bug report. There is no bug on alyx-dev thought, so this should be fixed with the next update to the production server.
