### ISSUE TITLE
new endpoint: datasetQuery

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#407]
(could call it something else if you like)

Inputs:
- subject name
- date [optional]
- datasettype name [optional]
- experiment number [optional]

Returns: 
- Associated dataset(s) - uuid and type
- associated filerecord(s) - uuid, repository path, and relative path

If date, dataset type, or experiment number are not provided, then return all, i.e. treat it as a wildcard. 

see https://github.com/cortex-lab/alyx-matlab/blob/master/%2Balyx/expFilePath.m

**Comment by rossant** [comment]
In principle this could just be `/datasets?subject=...&...`, right? We would just need to return associated file records as well.

**Comment by nsteinme** [comment]
Sounds good to me, yes.

**Comment by nsteinme** [comment]
Hey @rossant  - @k1o0 and I have been working hard on getting all the files registered to alyx and getting all the rigs up to speed with this code. If this query endpoint were available, it would really help to make it easy to check (and monitor) whether things are working properly. 

The basic idea could be achieved in other ways - the main point is to be able to quickly and easily see what sessions/datasets exist. So one could imagine a nice, convenient admin interface view for this, like a tree view of a directory structure: see a list of subjects, click one drops down all the dates that this subject has data, click one drops down all the base sessions on that date, click one drops down all subsessions, click one drops down all the datasets associated, showing their type and file path. The current session view is not far from this, but e.g. you can't tell what kind of session each one is, and you can't see associated datasets without navigating away (so it's hard to find your place again if you navigate back) and when you see the datasets, you can't see associated file records. All of these things would be helpful to make sure it's all working properly... 

Do you think one of these things is possible in the near term? Thanks -

**Comment by rossant** [comment]
Yes I'll work on this in the coming days

**Comment by rossant** [comment]
I pushed an update on alyx-dev. For example, `/datasets?created_by=Morgane&date=2018-01-26&dataset_type=Parameters&experiment_number=1` should work. Could you try it and run the testing suite on alyx-dev?

**Comment by nsteinme** [comment]
@rossant thanks for working on this and sorry I haven't had time to test it. @k1o0 could you test it? and compare the speed to a matching query using SQL (i.e. using alyx.expFilePath)? Make sure to do the test with an SQL connection already opened (the timing both with and without opening the connection are relevant to compare).

**Comment by k1o0** [comment]
```
ans =

    'Mean time for SQL query: 17.88ms; API query: 59.15ms (1 record returned)'
```

**Comment by nsteinme** [comment]
Great, that's fast enough. We need a new version of alyx.expFilePath, then,
but keep the SQL version around as a demo reference for how people can make
SQL queries...

**Comment by k1o0** [comment]
Okay but note that dat.expFilePath has a different function to the one you wrote: namely it returns the location and file name of an experiment, real or otherwise.  It just constructs the correct filename and creates any relevant directories that do not currently exist.  Your function returns the paths for only real experiments, regardless of filename.

**Comment by nsteinme** [comment]
I think the function we desire is one that tells you where to find the
files that were generated in your experiment. I'm confused about what
you're describing, but can we make that function? Do we need any other
functionality? I don't think dat.expFilePath ever created directories, and
this function should not do so either.

**Comment by k1o0** [comment]
The purpose of dat.expFilePath (which is used heavily in the creation of new experiments) is to return the filename and path, based on the input, for a given data type, in the correct format (i.e. repo/subject/date/sequence/exp_ref_dataType.ext).  If that given folder structure doesn't exist, it creates it, but the purpose of that function is not to only existing data.  It both tells you where to save files and where previously saved files should be.  To avoid confusion, any functions intended to replace to dat package should behave in broadly the same way, otherwise perhaps it's best to rename alyx.expFilePath to something else?

**Comment by nsteinme** [comment]
I just looked again, and I still don't see any mkdir in dat.expFilePath or
functions that it calls. I think you will find that if you run
"dat.expFilePath('blah',
now, 13, 'block', 'master')" then it will return you a path but that path
will not exist. So I recommend we stick with alyx.expFilePath for clarity.
However, I really don't much care what we call it, if you really want to
call it something else, go for it. "getFilePath" could be a bit more
descriptive.

I think we should make a separate decision about how to decide on new file
paths when we have a file that we want to save - is that alyx's
responsibility to decide, or rigbox's? If rigbox, let's just keep
dat.expFilePath. If alyx, then we need to implement that functionality in
alyx and have a function like "alyx.suggestFilePath(subject, date, expNum,
datasetType)" or something. We need to at least keep the rigbox version
around for backup, as when alyx is inaccessible, so maybe it makes sense to
keep it there full time, anyway.

**Comment by k1o0** [comment]
Ah, yes you're right, I was assuming that mkPath did something other than what it actually does,..

**Comment by k1o0** [comment]
Here's the new expFilePath:
https://github.com/cortex-lab/alyx-matlab/blob/alyx-as-class/%40Alyx/expFilePath.m

The Alyx side of things is working superbly so I'll go ahead an close this.
