### ISSUE TITLE
Dataset formats broken

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx#410]
I tried adding a file format to format types and I seem to have broken it.  Unfortunately this needs fixing before any more files can be registered.

**Comment by rossant** [comment]
on alyx-dev?

**Comment by rossant** [comment]
I'm not sure what's going on, can I just try to reset alyx-dev to the latest backup? (last night)

**Comment by k1o0** [comment]
No, on Alyx...

**Comment by rossant** [comment]
what is the problem exactly?

**Comment by k1o0** [comment]
> ImproperlyConfigured at /data-formats
> 
> Could not resolve URL for hyperlinked relationship using view name "dataformat-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.

This occurred after I added 'm' as a data format using the API Web form.

**Comment by rossant** [comment]
OK I see it, working on it

**Comment by rossant** [comment]
OK I pushed a quick fix, it should work now.

For future reference, here was the fix:

```
diff --git a/alyx/data/serializers.py b/alyx/data/serializers.py
index 4f353f3..cdaa354 100644
--- a/alyx/data/serializers.py
+++ b/alyx/data/serializers.py
@@ -28,7 +28,7 @@ class DataRepositoryDetailSerializer(serializers.HyperlinkedModelSerializer):
         extra_kwargs = {'url': {'view_name': 'datarepository-detail', 'lookup_field': 'name'}}
 
 
-class DataFormatSerializer(serializers.HyperlinkedModelSerializer):
+class DataFormatSerializer(serializers.ModelSerializer):
     class Meta:
         model = DataFormat
         fields = ('__all__')
```

**Comment by rossant** [comment]
Also, there was a problem with alyx-dev, which seems to be fixed now.

**Comment by k1o0** [comment]
Fantastic.  Thanks!
