### ISSUE TITLE
Generic cage number in Subject/Profile

### ISSUE THREAD

**Issue by nbonacchi** [cortex-lab/alyx#415]
The Subject/Profile tab has a field for Lamis cage that only accepts numbers, as I understand it this is a UCL specific thing, can we add a generic cage number field that accepts letters also, i.e here at the CCU the cages have alphanumeric codes e.g. CMIF-1

**Comment by rossant** [comment]
This raises the more general issue of how to deal with lab-specific features, notably lab-specific model fields... As far as I know, 1 code base = 1 fixed set of fields? I'll have to think about it...

**Comment by nsteinme** [comment]
But in this case, it should be an easy change to implement and will not affect functionality with numerical cages, so we should go for it... right?

**Comment by rossant** [comment]
No problem for the data type but we'll have to rename those fields to remove all references to "LAMIS" (which is UCL-specific, right?)

**Comment by nsteinme** [comment]
"LAMIS" is a UCL term (or possibly UK home office), yes.

**Comment by nippoo** [comment]
LAMIS is just UCL!

This was originally going to be a JSON / HBase field (ways of having 1 code base != 1 fixed set of fields) but there's probably value in having a general "cage label" field...

**Comment by oliche** [comment]
From the subjects.models
`cage = models.CharField(max_length=64, null=True, blank=True)`
