### ISSUE TITLE
Automated email discrepancy

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx#417]
Sylvia got the following email today at 7.00am:

> Mice on water restriction:
> 
> [...]
> 
> * SS093 since 2018-04-06.
> Weight 4 day(s) ago: 31.5g (expected 31.5g, 100.0%).
> Given 0.00mL (min 1.21mL, excess -1.21mL).
> Today requires 1.21mL.

At the same time I got the following email:

> Your actions yesterday:
> 
> [...]
> * 17:31 - Added <Water 1.27g for SS093> 

The database indeed shows that SS093 received 1.27g yesterday, so Sylvia's email is incorrect.  Also perhaps we could make the email less ambiguous by having it say 'Yesterday given...' instead of just 'Given'?

**Comment by rossant** [comment]
It seems to be because a weighing is missing for this subject. The report uses the last weighing as a reference date.

**Comment by rossant** [comment]
this should be fixed with the clearer message -- feel free to reopen if not
