### ISSUE TITLE
updating alyx - settings.py file overwritten by git pull

### ISSUE THREAD

**Issue by nbonacchi** [cortex-lab/alyx#420]
As far as I understand the only lab dependent files of Alyx are **settings.py** and **settings_secret.py** 
while settings_secret_template.py is used to create settings_secret.py for the settings.py file no such mechanism exists. This means that every time a user git pulls changes the settings.py file will be overritten.
It would be useful to **.gitignore** both the **settings_secret.py** and the **settings.py** files.
Alyx could use a settings_template.py file in the absence of settings.py. 
This would remove the need to backup the file before updating Alyx.

Alternatively an **update.py** file could be created that would take care of everything for the user, including migrations et al.

**Comment by nippoo** [comment]
Ooh - good point! Originally the settings.py didn't contain anything lab-specific, hence not featuring in the .gitignore, but now there's definitely some lab-specific content in there.

Best would probably be to refactor it into `settings.py` and `settings_user.py` (rename the `settings_secret.py` or keep it as a separate file). It's definitely useful to have a settings file that can be updated if new dependencies are added/removed etc, and keep that separate from the user-configurable settings.

**Comment by rossant** [comment]
done
