### ISSUE TITLE
Create subject through REST API

### ISSUE THREAD

**Issue by oliche** [cortex-lab/alyx#428]
Do we want to support subject creation through the API ?
If yes, I stumbled upon the following issues:

```
from oneibl.one import ONE
myone = ONE() # need to instantiate the class
subject = {'nickname':'toto',
           'responsible_user':'olivier',
           'protocol_number': '1',
            'project':'<Project_test_IBL>'}
r = myone._alyxClient.post('/subjects', data=subject)
```

Results in response 400, debug Django gives:
> serializer.is_valid()
> False
> serializer.errors
> {'genotype': [ErrorDetail(string='This field is required.', code='required')]}

```
from oneibl.one import ONE
myone = ONE() # need to instantiate the class
subject = {'nickname':'toto',
           'responsible_user':'olivier',
           'protocol_number': '1',
            'project':'<Project_test_IBL>',
           'genotype': []}
r = myone._alyxClient.post('/subjects', data=subject)
```
Gives a response 500, with the more interesting: 

> TypeError: Got a `TypeError` when calling `Subject.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Subject.objects.create()`. You may need to make the field read-only, or override the SubjectListSerializer.create() method to handle this correctly.

In the subject/serializers.py, l 54
`    genotype = serializers.ListField(source='zygosity_strings')`
Commenting this line gets rid of the problem. However I won't push this to prod.

I don't think we want this field as read-only. Do we want to overload the create method ? 
But mainly, do we want to support subject creation through the API ?
In this case we could argue that this is not a bug but a feature ;-)

**Comment by rossant** [comment]
I see no reason to prevent subject creation via the API. Could we just make the genotype field optional? I don't think we want to set the genotype this way via the REST API, it should just be a read-only field that is not used when creating a new subject.
