### ISSUE TITLE
display of zygosities in subject view

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#433]
Small change: when displaying a string of the zygosities in subject view, only display zygosities that are for alleles associated with that line, not for every allele that the mouse has. 

Which alleles are associated with that line? Currently there's "line-sequence relationship" but no "line-allele relationship". So we need to make that.

**Comment by rossant** [comment]
does that explain one of the bugs Charu reported to me?

**Comment by nsteinme** [comment]
Yes: some mice in the DA line were assigned a "Drd -/-" zygosity from the parents. But the parent in question was a Drd mouse that had been moved to the DA line - so seeing this zygosity information of the offspring for the Drd allele was not relevant anymore (not that it was inaccurate - just not relevant). This zygosity information doesn't need to be removed from the database, just not displayed in the subject view.

**Comment by nsteinme** [comment]
tested this too, looks great. if it's easy to do, could you make a line-allele relationship for every current one that exists? i.e. for every mouse, for each allele it has, add that line-allele to that mouse's line unless already exists. Then we can just remove the offending ones rather than re-adding all the usual ones. but it'll just be a one-time thing to add them so if it's a pain to add automatically then no worries.

**Comment by rossant** [comment]
okay, done
