### ISSUE TITLE
new fields for Line

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#434]
Hi, we should have some new fields for Line to provide users with a bit more information. 

These are critical: 
- Source (which is a pointer to a row in the Sources table)
- Source ID (a text field - will probably usually be a number but could be a string too I guess. doesn't need to be coded as a number, I don't think)

I thought we had that information in the database before but it's an oversight that we didn't so far. 

These would also be nice: 
- Source link (a URL pointing to the page about the mouse at the supplier's website)
- Expression data link (a URL pointing to a page (usually from allen institute) with details about expression in this link)

Then, if you have these links, it would be nice if the Line view (https://alyx.cortexlab.net/admin/subjects/line/) showed all the things it currently shows plus: 
- Source (text that shows the source name and ID and is a link if Source link is not empty, e.g. like: [Jax 012569](https://www.jax.org/strain/012569))
- Expression data (text that just gives a link if one is provided. The link text can just be "Click here" or "Expression data" or whatever you think is most clear to a user)

I don't think this will cause any problems with migrations since it's just adding new fields, do you think?

**Comment by oliche** [comment]
Datajoint question, should source_identifier, source_url fields should go in the source table and be linked via the source table ?

**Comment by oliche** [comment]
Ok, so we plan on removing those fields from  the Line table and put them in the Allele table.
