### ISSUE TITLE
Duplicate mouse nickname

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#439]
I was able to use the same nickname for two animals (using the same user name). I think it will be confusing. Is it a good idea to enforce single nickname across the whole IBL ?

**Comment by rossant** [comment]
Yes, that's a bug! I think the combination (lab, nickname) should be unique, or even just nickname, although that might come with complications (@oliche)

**Comment by oliche** [comment]
I've enforced uniqueness of (lab, nickname) and (responsible_user, nickname).
On feature/devo branch, will be in the next pull request
