### ISSUE TITLE
Reference weight field

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx#450]
Since the introduction of the reference weight field in the water restrictions table the mice currently on free water show a reference weight of 0.0g.  I assume this is not actually the case, but it is confusing for the user.  Also when adding a new water restriction the reference weight is blank.  It is not clear whether it can be left blank in order to use the last free water weight or whether one must explicitly fill it in.  Is it possible to have this field pre-filled with the last free water weight (i.e. the weight that used to be automatically chosen by Alyx)?

[Edit] It seems there is no longer any automation of this step, so the user must navigate to the weighings, note the last free water weight recorded, then navigate back to add the reference weight.  Is there a way of defaulting to the previous system which worked for most use cases?

**Comment by k1o0** [comment]
To clarify, could we have the reference weight be a weighings entry? Otherwise it appears as though though the subject hasn't been weighed on the first day of water restriction.  This causes problems for some of our code as currently the end points don't indicate when the subject was put on water restriction so there's know way of knowing which is the first day of water restriction.

**Comment by oliche** [comment]
So on creating a Water Administration
1) get the weight the closest from the Water Administration start date
2) If the date of weighing is away by more than 1 week from start date, prompt the user for a weighing, or warn

**Comment by oliche** [comment]
Ok so the topic is getting popular so I'm consolidating in a single issue.
https://github.com/cortex-lab/alyx/issues/454
https://github.com/cortex-lab/alyx/issues/464
https://github.com/cortex-lab/alyx/issues/465

**Comment by oliche** [comment]
0c51771472357f14466d07ed03278e63f98b59de
