### ISSUE TITLE
Water plot: customizable thresholds and line styles

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#453]
IBL wants:
70% threshold red dashed
85% threshold
cc @GaelleChapuis

**Comment by GaelleChapuis** [comment]
Can we have the possibility to have the threshold adapted per lab?
We are trying to standardise across IBL labs, but some labs have specific restriction.

For example, 
- UCL lab: red threshold = 70%
- NYU lab: red threshold = 80%

**Comment by rossant** [comment]
sure that could be a per-lab setting

**Comment by GaelleChapuis** [comment]
Can we also add the legends of the line on the plot, indicating the threshold value?

**Comment by GaelleChapuis** [comment]
Continuing on that : How can someone check what is the formula used to compute the threshold?

**Comment by GaelleChapuis** [comment]
And again: There is currently no way to check what the percentage used for the threshold is.

As stated above, we could have cases where the orange line is at 80% for one lab, and 85% for another. Can we have the legend on the plot? For the moment we have it standradised across lab at 85%, but we need a way to check it visually.

For the red line > can we make it dashed? It is good practice to have it, but most protocol do not abide but the 70% rule.

Also: can it be marked onto the weight plot that the black line needs to stay **above** the orange line? For a lot of people, the reasons for having two lines on the plot served as visual tool to keep the black line between the orange and red line (which is wrong).

**Comment by rossant** [comment]
okay should be done
