### ISSUE TITLE
water administration/weight alerts by email

### ISSUE THREAD

**Issue by anne-urai** [cortex-lab/alyx#454]
If all users are required to list an email address, it would be great if
1. they got an alert when any of their animals went below 85% of reference weight (with the option of age-correction on/off depending on lab for IBL)
2. they got an alert if one of their mice on water restriction didn't receive water by e.g. 6pm

**Comment by oliche** [comment]
So this is done but it can't be turned on just yet: we need to agree on what constitutes the reference weight. In UCL this is done using a formula taking into account the sex, date of birth and a weight point in the past. Here Anne mentions just a reference weight.
Should we expect to have an IBL standard or is this going to be a per lab decision ? The implementation will depend on the answer to that question.

**Comment by oliche** [comment]
So after discussion with Gaëlle, this has to be lab specific : London uses the formula and Lisbon and NY 85% of the weight. This may be standardized in the future, but we have to be flexible in case ethical comittees differ among institutions.

**Comment by oliche** [comment]
see https://github.com/cortex-lab/alyx/issues/450
