### ISSUE TITLE
Use a time zone depending on the logged user

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#456]

**Comment by oliche** [comment]
Reminder of the user feedback:

> the sessions and water deliveries that are synced to alyx from rigbox seem to be in local time, whereas when I manually add a water delivery in the browser the ‘now’ setting takes server time by default (and warns me that i’m 5 hours behind). is this a design choice? as a user, it would make more sense if i could enter my timezone once

**Comment by oliche** [comment]
Water control takes this into account.
Session time is local time.

Next to solve are the boxes to create an object with a 'now' button that will put the current time of the server.

**Comment by oliche** [comment]
@rossant  It's seems to me a much larger issue than what it sounds. As of now everything is stored as naive date objects assuming local times. So if we use TZ support, sessions time will be rendered wrongly everywhere but for users in London (and most of the time for users in Lisbon).

This will go against a decision we made last Spring, but for this we will have to migrate to Timezone aware datetimes sooner or later, having everything UTC in the database and serialize/deserialize according to the lab local time. Migration for UCL will be straightforward, for IBL it shouldn't be too bad with lab inheritance. Serializers will be more time consuming. For internal queries, time-zone aware date objects allow to perform those local time queries against an UTC internal format. Again, for us to implement in Django filters.

Alternative is to sublass explecitely all forms using the widget, and modify the date_time/time fields with an UTC offset fetched from the current_user lab. This is hacky, time-consuming and not evolutive.

Another alternative is to override/fork the Django datetime widget that provides this now button and have it use the browser time. 

So far I've implemented a `misc.models.LabMember.tz()`  method that gets the user time-zone according to the (first if several) lab to which it belongs. May be useful or not...

Suggestions welcome...

**Comment by rossant** [comment]
Is the user request only to fix the "now" widget box in the admin interface?

**Comment by rossant** [comment]
> Is the user request only to fix the "now" widget box in the admin interface?

If this is the case, then I found a quick and easy solution:

* A couple of lines of JavaScript to disable the server timezone auto configuration (turns out this is a feature, django < 1.7 provided the behavior we want now)
* Django admin default value override to use, by default in the admin interface, the date time in the timezone of the logged user.

**Comment by oliche** [comment]
![53352316-91be8700-38f0-11e9-8c29-babd6b58be44](https://user-images.githubusercontent.com/15081095/53556657-2f59c680-3b3c-11e9-8a32-30e36bcefaee.jpg)

**Comment by rossant** [comment]
what's the status of this @oliche ?

**Comment by oliche** [comment]
Normally, this has been handled by this morning release !
I'll risk to jinx it and close the issue right now.
