### ISSUE TITLE
Ignore multiple weighing values for same subject and date

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#457]
scenario is: a wrong weighing is registered, a new corrected weighing is registered, and the old one is not deleted. Perhaps Alyx should always consider the *last* weighing per day

**Comment by anne-urai** [comment]
We often weigh the mouse before and after the task, so while weighings within <10 minutes or so could be considered duplicates, it would be nice to keep the pre- and post-task weight

**Comment by oliche** [comment]
Plus there was an issue with local time/server time that ended up in several weighings within a day that where from different days on the client side.
We keep support for several weighings per day .
