### ISSUE TITLE
Automatically end water restriction when mouse is dead

### ISSUE THREAD

**Issue by anne-urai** [cortex-lab/alyx#463]
I’m grabbing all subjects to plot for my ‘behavioral snapshots’ with `subjects 	= pd.DataFrame(one._alyxClient.get('/subjects?water_restricted=True'))`. could this return only alive animals? I think it make sense to not show dead ones as being water restricted

**Comment by oliche** [comment]
3bd066148c6d09c39fe105f07a55ee4d273ffa94
