### ISSUE TITLE
Reference weights aren't used

### ISSUE THREAD

**Issue by pipcoen** [cortex-lab/alyx#464]
When entering the "reference weight" when putting a mouse on water restriction, it appears this isn't actually the weight used as the reference weight. Instead, the last free water weight before the restriction seems to be used? To get the system to use the right weight, I have to add an "weighing" for that day. The "reference weight" entered when adding a water restriction doesn't seem to be used in the calculation at all?

**Comment by oliche** [comment]
See https://github.com/cortex-lab/alyx/issues/450
