### ISSUE TITLE
Return ExpW as Carandini method even if not used to compute threshold - possible ?

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#465]
All IBL use the same reference weight (RefW) = the weight taken on the day when starting water restriction.

We know that different protocol allow for different measure of the expected weight (ExpW):

1.  Either using directing the reference weight : ExpW = RefW
2. or by adjusting the weight according to the age of the mouse : ExpW = f(RefW)*g(RefW)
where according to Matteo f(RefW) is a function describing whether the animal is chubby or skinny compared to the littermate from animal supplier (will be a constant),
and g(RefW) is the mean curve for weight from animal supplier)

Now, as said via email, we keep those expected weight (tailored per lab) to measure the threshold for water restriction (using 85% for the whole IBL).

However, when we want to compare the % weight loss (during analysis, on plots), we need to harmonise.

I think it is best to base the % weight loss on the ExpW computed via the Carandini method (#2 here), as it adjusts for the age of the animal.

Can Alyx return the value of ExpW_Carandini (expected weight measured as the Carandini method) even if this formula is not used to compute the expected weight for threshold (as is the case for most lab) ?
 (note that this would be a third variable, as we still must access RefW and ExpW as computed for the threshold)

**Comment by oliche** [comment]
see https://github.com/cortex-lab/alyx/issues/450
