### ISSUE TITLE
change password on IBL Alyx - is updated on UCL Alyx ?

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#469]
Probably a naive question:

If I change my password on the IBL Alyx, is it updated on the UCL Alyx?

**Comment by rossant** [comment]
No, not at the moment. There is no communication from IBL to UCL at this point.

**Comment by GaelleChapuis** [comment]
OK - and will that be implemented in the future?

**Comment by rossant** [comment]
I'm not sure it will, no.

**Comment by rossant** [comment]
Yes for the other way, I think (@oliche ?)
We should indeed clarify in the documentation that the sets of members are different, and say more precisely how UCL data is being imported into IBL alyx.

**Comment by oliche** [comment]
So fixtures are imported from UCL to IBL. Your password will get updated.
THe update takes place once a day though, it is not immediate.

**Comment by oliche** [comment]
We'll go over the import procedure in details Thursday if that's ok with you, and I"ll put in prod just after.
