### ISSUE TITLE
water-requirement endpoint query

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx#478]
The following query returns 114 records, including many whose dates fall outside the requested range:
https://alyx.cortexlab.net/water-requirement/ALK081?start_date=2018-11-27&end_date=2018-11-29

Before the update the Monday before last, this would return only those records which fell within that date range.  What's more, it doesn't return any existing records which have a future date.  This is a problem because we use this endpoint to determine whether to post water automatically for the weekend, and also to retrieve 'future' administrations so that the staff know how much to give over the weekend.

Could we do a merge as soon as this is fixed so that there's no confusion over the weekends?

**Comment by rossant** [comment]
I'll push a fix quickly

**Comment by rossant** [comment]
should be fixed on alyx-dev could you try and double-check? If it works I'll merge on alyx

**Comment by k1o0** [comment]
[Sorry, I replied but never clicked 'Comment'!]

Great! It's working now.  It would be good to have some kind of indication of whether a weight is carried over from the previous day.  Previously the weight field was zero or empty for the days where there was no weight record, whereas now it's difficult to determine whether the animal has a stable weight or simply wasn't weighed.

**Comment by rossant** [comment]
Right! that's a bug, I'll fix it
