### ISSUE TITLE
Enhancement: change Home > Subject > Subject into Home > Subject admin > Subject

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#479]
<img width="602" alt="capture d ecran 2018-11-28 a 11 10 49" src="https://user-images.githubusercontent.com/43007596/49148268-cd9c7d00-f2fe-11e8-9344-d3632f2b060c.png">
<img width="626" alt="capture d ecran 2018-11-28 a 11 11 08" src="https://user-images.githubusercontent.com/43007596/49148271-ce351380-f2fe-11e8-869f-f6955663d8c6.png">

**Comment by oliche** [comment]
I agree with this. Also while we are at it, it would be nice to have a bar on top at all times that links to:
Actions Admin | Data Admin | Subjects Admin | Misc Admin

**Comment by rossant** [comment]
I'll do it
