### ISSUE TITLE
Mouse death date vanished

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx#482]
Pip is quite sure that he marked 'PC029' as culled at least a month ago and says it has recently appeared as alive again.  The history shows that the 'end_time' field was changed on October 22nd.  I'm unsure if someone else marked it as alive again.  Is there any way to tell if this is a glitch or human error? 

Here's the subject: https://alyx.cortexlab.net/admin/subjects/subject/b31d094c-5a19-4806-b7dd-cdbf8fa1c9bd/change/?_changelist_filters=responsible_user%3Dall%26q%3DPC029

This seems similar to the issue we had a while ago when the water restriction was deleted for ALK077 over the weekend, which seemed unlikely to have been done by a user.

**Comment by rossant** [comment]
reopen if the problem reappears
