### ISSUE TITLE
Enhancement: Alyx home page : indicate link to main directories (admin)

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#486]
Currently,  the home page of Alyx shows Common, Data files, etc links , but not 'Main' links such as:
- Subject admin
- Action admin

Worth listing ?

**Comment by rossant** [comment]
It should be noted that the default presentation of django admin is:

SUBJECTS
Subject
Line
Litter
....

ACTIONS
Surgery
WaterAdministration
...

etc. Every application has its own panel, and every model is listed.

Some people requested to have the current organization with commonly used/rarely used pages.

There have been some requests to go back to the default presentation.

An common agreement should be reached to make most people happy.

**Comment by GaelleChapuis** [comment]
Note that I am writing the user guide using the nomenclature found at the top of the page, e.g. Home > Action admin > Culls
whilst on the web page it is visible differently, e.g. as Home > Other > Culls .
I used the first nomenclature, as it should not change afaik, but it makes it rather confusing to follow.
