### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#487]
Goal: have a more maintainable system to manage notification emails sent to users.

Proposition of new models (note: this is probably of no use to datajoint):

`misc/notifications.py`

```
class Notification:
    date_time
    type: foreign key to NotificationType
    title: string
    message: string
    users: many to many relation to LabMember
    status: no-send, to-send (default), sent

    def send_now()  # send the email and change the status to "sent"

class NotificationRule:
    # for each user and notification type, send the notifications for a given set of mice (none, all, mine, lab)
    user: foreign key to LabMember
    notification_type: enumeration (responsible_user_change, weight_control, water_control)
    subjects_scope: none, all, mine, lab
    (unique_together: user, notification_type)
```

Also: global function `send_pending_notifications()` to be run in hourly cron. This function sends all Notification instances that have a status equal to `to-send`, and that have a `date_time < now`

`create_notification(type)`

**Comment by GaelleChapuis** [comment]
@rossant it seems like #483 does not work properly (see message on slack).

**Comment by anne-urai** [comment]
To specify, as well as the alert email when weight is too low the user should get a warning if a mouse hasn't had its daily requirement of water 22 hours after the last water intake
