### ISSUE TITLE
Create schemas to store enrichment and housing conditions

### ISSUE THREAD

**Issue by oliche** [cortex-lab/alyx#498]
subjects.housing 
- subjects (FK)
- mice_per_cage (computed)
- cage_name (Char, free)
- cage_model (FK)
- enrichment (FK)
- food (FK)
- temperature range
- humidity range
- cage_cleaning_frequency
- start_datetime (nullable, if tracking changes only)
- end_datetime (nullable, if tracking changes only)

The above fields are populated by default from the lab new fields:
- cage_model (FK)
- enrichment (FK)
- food (FK)
- temperature range
- humidity range
- cage_cleaning_frequency

Admin interface:
drop down list in the subject table should reference housing instances by subject, and filter only within the current subject lab.

**Comment by k1o0** [comment]
At UCL we already need to change the cage id field when moving a mouse.  This schema would require the user to do two more things: add subjects to the cage and select the enrichment.  Everything else should be a lab default that doesn't change very often.  I think this would be fine for people to do.

**Comment by oliche** [comment]
Add light cycle as well

**Comment by GaelleChapuis** [comment]
could we add fields so we can input the % of fat and protein in the food?
