### ISSUE TITLE
Add string representation of subjects.Zygosity

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/alyx#50]
@nsteinme what is the standard?

ie `{allele}-{zygosity}` or something.

**Comment by nsteinme** [comment]
If allele = 'Ai95' and zygosity = 'heterozygous' then 'Ai95 +/-' etc.

**Comment by nippoo** [comment]
If allele = 'Ai95' and zygosity = "Absent" then ?
If allele = 'Ai95' and zygosity = "Heterozygous" then?
If allele = 'Ai95' and zygosity = "Homozygous" then?
If allele = 'Ai95' and zygosity = "Present" then?

**Comment by nsteinme** [comment]
-/-
+/-
+/+
+
