### ISSUE TITLE
Some field labels in red in Change Subject page

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#500]
I am going through the wiki IBL instruction on how to create a mouse:
https://wiki.internationalbrainlab.org/index.php/Alyx_Experimenter_checklist#1.29_Create_a_new_Subject_and_enter_some_stuff

Mandatory Immediately

    sex
    birth date
    lab

Mandatory

    cage
    ear mark
    strain

I have been able to create a subject onto Alyx without having to fill in all of the above, see:
https://dev.alyx.internationalbrainlab.org/admin/subjects/subject/ > TestGC_2019-01-23

Can we make the fields mandatory upon saving? Or mark those above with a red asterix for visualisation?

**Comment by GaelleChapuis** [comment]
It was decided not to do mandatory fields - can certain fields be in bold / red colour ?

**Comment by rossant** [comment]
yes I think that's doable with CSS. Which fields should be in bold/red?

**Comment by rossant** [comment]
OK, done, except for lab which is already mandatory therefore it is already in black.

**Comment by GaelleChapuis** [comment]
Great - I will get back to you as we might end up not needing the field ' Litter' after all.

**Comment by GaelleChapuis** [comment]
So litter does **not** need to be in red. Please reverse.

**Comment by rossant** [comment]
ok, done
