### ISSUE TITLE
Project "not part of IBL" - best practice?

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#501]
I think there should be the choice for a mouse to be part of a "non-IBL project" as part of the drop down menu (listed as a standard string name for all mice). 

Instead, we can surely decide that one has to write another project name once the mouse quits IBL, but that name will become arbitrary (for example 'my new awesome project that I do on the side').

What is best practice?

**Comment by rossant** [comment]
@oliche should we just create a "non IBL project"?

**Comment by GaelleChapuis** [comment]
Will this project then NOT be associated to a server?

Related to https://github.com/cortex-lab/alyx/issues/505, how to deal with a project that is not IBL-related, but that needs uploading onto FlatIron (in the case of a post doc personal project for example)?

**Comment by rossant** [comment]
yes, or associated to local data repositories, not flatiron

to answer your question, you can create another non-IBL project associated to flatiron so that the data is uploaded

**Comment by oliche** [comment]
Best practice is to leave this field to administrators as it has implications on the data management pipeline
