### ISSUE TITLE
Change 'Project' into 'Data Repository'

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#505]
Can we change the naming of 'Project' into something else that reflects the function better (such as 'server' or 'data repository')?

**Comment by rossant** [comment]
Project is not a data repository (which already exists, `DataRepository`). It really is a research project that is associated to IBL or not.

**Comment by GaelleChapuis** [comment]
So is it simply that a project is _associated_ with a repository?
https://alyx.internationalbrainlab.org/admin/subjects/project/

Then, if one selects the wrong project name for its institution (or writes down another project name), data will not be uploaded onto the main sever.

Does this also mean that when creating a new project, one has to ask admin to associate it to the right data repository? Or should one keep on using the same project name (but e.g. the task name will be different)?

**Comment by rossant** [comment]
That's right, a project is associated to one or several data repositories. Currently we essentially use this to know which data to upload to flatiron (only those mice associated to a project associated to the flatiron DataRepository, i.e. a special IBL project).
