### ISSUE TITLE
Sucrose/Water definition in water administration

### ISSUE THREAD

**Issue by laurax452** [cortex-lab/alyx#506]
We still have hydrogel and water columns in MC/alyx but no longer use hydrogel.
Can we change this to sucrose/training water and supplemental water.
I think most people train with sucrose (10%) but some people may use water in individual rigs.
It is useful to know what a mouse received from the task and how much we had to give afterwards.

**Comment by oliche** [comment]
Those water types are attached to past data and should not be removed.

The water types of incoming water administrations, attached to a session or not, is configurable from the client side. If you need a new water type (ie. Sucrose 3.45% for example) you can create it from the admin interface (top right actions, then water-types)

For rigbox sessions, check with the support group where to change the water type. 
For iblrig, in the task settings file, under water reward type.
For general rest query, just label the `water_type` field of your data structure
To define a default value when none is provided, go to the current water restriction of your mice and set the water type from there.

**Comment by jaib1** [comment]
I think Laura is specifically talking about the columns in the  "Subject history" figure (i.e. adding a 'Water 10% Sucrose') column to 'histTable' in the 'viewSubjectHistory' method for 'AlyxPanel'. It may be nice to add columns specific to the water type delivered to the animal, rather than just 'water' and 'hydrogel' columns appearing for all animals. @k1o0 
![subjecthistorytable](https://user-images.githubusercontent.com/14895866/51984434-39cc6600-2493-11e9-933a-436e6cb5101f.PNG)

**Comment by k1o0** [comment]
Then this issue is in the wrong repo, I'll move it

**Comment by k1o0** [comment]
Sorry I moved this too hastily.  I stand corrected, this is an Alyx issue.  Seeing as hydrogel is not widely used any more and what the experimenter really wants to see in this view is the water that was given during a session and the water that was given as a supplement, I propose the following change:

Replace these lines:
https://github.com/cortex-lab/alyx/blob/f6f87091bc68f2414a1eede857d9a2187cc1030e/alyx/actions/water_control.py#L365-L377
https://github.com/cortex-lab/alyx/blob/f6f87091bc68f2414a1eede857d9a2187cc1030e/alyx/actions/water_control.py#L392-L403

With something along these lines:
```python
    def given_water(self, date=None, session=None):
        """Return the amount of water given at a specified date."""
        date = date or self.today()
        # Filter by presence of session or otherwise
        return

    def given_water_reward(self, date=None):
        """Amount of water reward given during a session at the specified date."""
        return self.given_water(date=date, session=True)

    def given_water_supplement(self, date=None):
        """Amount of water reward given as a supplement at the specified date."""
        return self.given_water(date=date, session=False)

    _columns = ('date', 'weight', 'weighing_at',
                'reference_weight',
                'expected_weight',
                'min_weight',
                'percentage_weight',
                'given_water_reward',
                'given_water_supplement',
                'given_water_total',
                'expected_water',
                'excess_water',
                'is_water_restricted',
                )
```

This would affect the water-requirement endpoint and water-history page
I suppose the given_water_liquid et al. can remain although I can't imagine anyone would want to use them...

**Comment by oliche** [comment]
@k1o0 So this is on a different branch here 7df6e42922a3f4345c03478e39f80391f3f0573f

The endpoint `water-requirement` will be affected as such:
```        {
            "date": "2019-01-18",
            "weight": 25.0,
            "weighing_at": null,
            "reference_weight": 0.0,
            "expected_weight": 0.0,
            "min_weight": 0.0,
            "percentage_weight": 0.0,
            "given_water_reward": 0,
            "given_water_supplement": 0,
            "given_water_total": 0,
            "expected_water": 1.0,
            "excess_water": -1.0,
            "is_water_restricted": false
        },```
If we split by water type, it's quite unpractical as there is a variable number of columns.
Let me know if we should merge this next Monday.

**Comment by k1o0** [comment]
Looks good.  Yes I think people only really need to see how much was earned in the task.  Individual trainers should know the type of water is given.

**Comment by laurax452** [comment]
The table in the subject history alyx GUI panel has now completely disappeared. Is this something to do with the changes made? Or perhaps a new issue?

I can't read code to know what your answers mean Olivier. It would be good if you could explain the effect of the code in writing as well.

It is important for me as a trainer that I can see the raw data contained in that table in alyx GUI, including how much water/sucrose was given in the task and how much additional water was given.
The alyx GUI was created to help trainers know how the mouse's health/weight is, how much excess we are giving as standard to keep the mouse at that weight and how much the mouse is attaining in the task etc. Without having to go into each animals water history page on Alyx which can take a while.

**Comment by k1o0** [comment]
Yes, I made some changes to reflect the renaming of fields in Alyx.  These changes were made on the dev branch, which is the branch used by the training computers.  For now, you can use the browser admin interface by clicking the 'Launch webpage for Subject' button.  Once the master branch of Alyx is updated there will be 'reward' and 'supplement' column on the water history instead of water and hydrogel.  These columns will indicate the amount of reward given in the task and liquid as supplement, respectively.

**Comment by k1o0** [comment]
There's an Alyx error on the water-history page for LEW015 that may be related to this:
https://alyx.cortexlab.net/admin-actions/water-history/e9a016b0-26c6-434d-b8c1-dd68b4284100

**Comment by laurax452** [comment]
Hi,
Yeah I realised afterwards that this seems to be a new issue with LEW015 only. I was going to start a new issue for this problem, do you know the cause? Do you want me to start a new issue for it?
Lovely job on the new subject history table btw. Just what I wanted :)

**Comment by rossant** [comment]
> There's an Alyx error on the water-history page for LEW015 that may be related to this:
> https://alyx.cortexlab.net/admin-actions/water-history/e9a016b0-26c6-434d-b8c1-dd68b4284100

should be fixed now
