### ISSUE TITLE
Viewing all mice even when selecting 'me' as responsible user

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#510]
On https://alyx.internationalbrainlab.org/admin/subjects/subject/?

Screenshot:
<img width="1217" alt="screenshot 2019-01-31 at 10 49 53" src="https://user-images.githubusercontent.com/43007596/52049655-45c53000-2546-11e9-8fb9-5b21ce22f9cd.png">

**Comment by rossant** [comment]
Do you have any mouse? If not this is a new behavior to avoid a useless empty view by default and save 1 click for those who don't have mice (mostly useful to me and @oliche :) )

**Comment by GaelleChapuis** [comment]
Ah ok - No I don't have any mice, so this is normal then !
