### ISSUE TITLE
Question: why +Add surgery shows all fields but not +Add session

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#512]
It might not be a very relevant question, but I was wondering why there is this discrepancy:

+add subject does not list any fields (see grey line):
<img width="1324" alt="screenshot 2019-01-31 at 15 49 57" src="https://user-images.githubusercontent.com/43007596/52066235-0b708880-2570-11e9-929b-718216b351a9.png">

+add surgery lists a bunch of possibilities (including behavioural training)
<img width="946" alt="screenshot 2019-01-31 at 15 49 29" src="https://user-images.githubusercontent.com/43007596/52066261-188d7780-2570-11e9-9265-7d75ffec6944.png">

tested on:
https://dev.alyx.internationalbrainlab.org/admin/subjects/adverse%20effect/f43eaca5-cc3f-4bbf-bc64-01dbae31bd8f/change/

**Comment by oliche** [comment]
This is a bunch of parameters in the administration interface that lead to this behaviour, it's expected behaviour with code parameters. 
I'm closing this, do not hesitate to re-open if you think this should have a different behaviour.
