### ISSUE TITLE
add endpoint for all water restrictions (start time, end time, reference weight)

### ISSUE THREAD

**Issue by anne-urai** [cortex-lab/alyx#524]
in #datajoint, `action.WaterRestriction` returns a history of all water restrictions (start times, reference weight and end times). How can I get the same list from the Alyx rest API? `one.alyx.get('/subjects/%s' %mousename)` only returns `last_water_restriction` and `reference_weight`, without info about previous restrictions and dates.

**Comment by oliche** [comment]
Fixed in 566374f293f4e2f685c70c11eee0a4fa8a033e16

**Comment by anne-urai** [comment]
pulled the latest version of ibllib develop, but this doesn't seem to be available
```
    restr = one.alyx.rest('water-restriction', 'list', subject=mousename)
  File "/Users/urai/Documents/code/ibllib/python/oneibl/webclient.py", line 306, in rest
    'endpoints are \n       ' + '\n       '.join(av))
ValueError: REST endpoint "water-restriction" does not exist. Available endpoints are 
```

Do I need to go onto the alyx dev branch?

**Comment by oliche** [comment]
We rebase the dev branch onto master on Mondays so all the changes in there (https://github.com/cortex-lab/alyx/projects/2) are pushed to prod Monday morning.
