### ISSUE TITLE
LearningStatus table and FK in subject

### ISSUE THREAD

**Issue by oliche** [cortex-lab/alyx#535]
There is consensus that a training status field is needed in the subject table.
However possible values are not set, thus we'll do a Training Status table and a link to subject so that we can create new statuses.

For init fixtures will start with:

- null
- Untrainable
- Recording ready
Feedback welcome
https://github.com/int-brain-lab/iblrig/issues/158

Computing this status requires access to data, so this rule out doing this within Alyx. Need to have a patchable field in the subject REST endpoint to programmatically update this value.

**Comment by GaelleChapuis** [comment]
Rather than marking "ready for ephys", we should rather indicate "trainingChoiceWorld" (or any protocol for that matter) **Completed**.

So I would say:
* null
* "xxx protocol" completed (then it is up to the user to know which protocol needs to be set after)
* Untrainable

Note on Untrainable. : this is currently happening only after 40 days in trainingChoiceWorld

**Comment by anne-urai** [comment]
Agree with the above - this could even be extended towards earlier in training, showing eg 'habituation World completed'

**Comment by GaelleChapuis** [comment]
Yes, @anne-urai this was the idea :) !

So far we have the following protocols:

- habituation World
- trainingChoiceWorld
- biasedChoiceWorld
- ephysChoiceWorld (@nicco naming?) + passive stimulation 

If it is too complex to have the name of the protocol appearing, Protocol Completed could be used instead as fixture.

**Comment by GaelleChapuis** [comment]
Also: I seems like the training status should be computed in DJ, and propagated to Alyx to which pyBpod can connect and warn the user if a change needs to be done.

**Comment by oliche** [comment]
Done via Datajoint
