### ISSUE TITLE
water administration in batches

### ISSUE THREAD

**Issue by anne-urai** [cortex-lab/alyx#537]
when giving adlib water to a cage, this now has to be entered per mouse separately. it would be great to have a batch option where adlib can be selected, and multiple mice entered at once

**Comment by anne-urai** [comment]
it would also be great to do adlib water administration for multiple days, so that on friday afternoon it can easily be indicated that animals get a bottle for the whole weekend

**Comment by oliche** [comment]
This is not the kind of logic that we want within the database, as it may not generalize very well. This is typically a client code feature, here is an example of automatic mouse watering script that you may want to adapt to your needs:
https://github.com/int-brain-lab/ibllib/blob/master/python/oneibl/examples/rest_water_administrations_week-end.py
