### ISSUE TITLE
Changes to water-requirement endpoint records

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx#546]
There's recently been a change to the behaviour of the water-requirement endpoint that's causing problems for us.

The `weighing_at` field appears to be empty regardless of the whether there has been a weight for that day.  I noticed this on Friday when testing my weekend water script using alyx-dev.  At the time it was still working on the main database. 

Today I noticed that my tests are failing when using the IBL test database: I posted numerous weights for the subject 'algernon', however the endpoint returns a single record with the `weight` field being 0:

```
water-requirement/algernon?start_date=2019-05-07&end_date=2019-05-07

{
    "subject": "algernon",
    "implant_weight": 0.9,
    "records": [
        {
            "date": "2019-05-07",
            "weight": 0,
            "weighing_at": null,
            "reference_weight": 22.0,
            "expected_weight": 31.772727272727273,
            "min_weight": 25.41818181818182,
            "percentage_weight": -2.9151943462897525,
            "given_water_reward": 0,
            "given_water_supplement": 0.1576,
            "given_water_total": 0.1576,
            "expected_water": -0.045000000000000005,
            "excess_water": 0.2026,
            "is_water_restricted": true
        }
    ]
}
```

Today Laura noticed that the view subject history panel (which uses the same endpoint) no longer shows weights (see issue https://github.com/cortex-lab/Rigbox/issues/151).  I haven't properly looked into this yet but it's likely to be related...

**Comment by rossant** [comment]
A change to the water control was pushed today, I'm looking into it

**Comment by rossant** [comment]
I just pushed a fix on cortexlab alyx. Could you test it?
If it works we'll update IBL alyx too
cc @oliche

**Comment by k1o0** [comment]
Yep they seem to be back in order on the cortex-lab Alyx

**Comment by k1o0** [comment]
I spoke too soon, getting errors for a couple of mice now: water-requirement/AL019 & AL016

**Comment by rossant** [comment]
okay, try again?

**Comment by k1o0** [comment]
I queried about 15 mice and they all looked good

**Comment by k1o0** [comment]
Was the test database updated?  It now returns no records for test subject 'algernon', despite there being numerous weighings etc. posted.
