### ISSUE TITLE
Broken date search queries for sessions endpoint

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx#550]
Some of the [documented date filters](https://alyx.readthedocs.io/en/latest/api.html#id2) don't appear to work.  Example: `GET /sessions?end_date=2019-01-28` on the test database returns all sessions, regardless of session end time.  I think only `date_range` works?

**Comment by oliche** [comment]
Yes I think the idea was to use `/sessions?date_range=2019-01-28,2019-01-28` for this kind of queris
Anyway the documentation should not point to non-working queries.

@rossant should fix the doc or add the filters ? Both are easy.

**Comment by rossant** [comment]
A single way of doing it should be sufficient, okay @k1o0 ? If so we should just fix the doc

**Comment by k1o0** [comment]
Okay, I'll delete those options from the alyx-matlab API
