### ISSUE TITLE
Security problem: some schemes (e.g weighings) can be edited by all users 

### ISSUE THREAD

**Issue by alejandropan** [cortex-lab/alyx#551]
I have noticed that we all have editing permissions for weighing data (For example, I can change the water logs for any  IBL mouse).  This could be a real problem now that we are writing code to automatically input metadata into alyx (e.g. add 1 ml on weekends, end water restrictions etc). It seems to me far to easy to accidentally write something that would for example change all the water administrations to 1ml or some other catastrophic error like that. This is specially a problem on less noticeable examples, where it could take months to detect the accidental change. Is there any way in which could limit the editing capabilities of non-admin users?

**Comment by oliche** [comment]
@rossant for the admin interface, overload the  `has_change_permission` method in the `BaseAdmin` class. It's on a custom branch; 7d86398b22820f7f88b47bae280e49a3fdd44eb4

I wonder if this should this be extended to other apps, and how to do this for the action REST endpoints.

**Comment by rossant** [comment]
Yes that's good, I think you can do the same for REST with https://www.django-rest-framework.org/api-guide/permissions/#custom-permissions

**Comment by oliche** [comment]
Released today.
