### ISSUE TITLE
Problem with water restriction on Alyx

### ISSUE THREAD

**Issue by neurvanna** [cortex-lab/alyx#556]
I am trying to change a water restriction on Alyx, but getting the following error

KeyError at /admin/actions/waterrestriction/25b3368a-b7f4-4daf-9bce-82883ce34382/change/
'reference_weight'
Request Method:    GET
Request URL:    https://alyx.cortexlab.net/admin/actions/waterrestriction/25b3368a-b7f4-4daf-9bce-82883ce34382/change/
Django Version:    2.1.2
Exception Type:    KeyError
Exception Value:    
'reference_weight'
Exception Location:    /var/www/alyx/alyx/actions/admin.py in get_form, line 265
Python Executable:    /var/www/alyx/alyx/bin/python
Python Version:    3.5.2
Python Path:    
['/var/www/alyx/alyx',
'/var/www/alyx/alyx/lib/python35.zip',
'/var/www/alyx/alyx/lib/python3.5',
'/var/www/alyx/alyx/lib/python3.5/plat-x86_64-linux-gnu',
'/var/www/alyx/alyx/lib/python3.5/lib-dynload',
'/usr/lib/python3.5',
'/usr/lib/python3.5/plat-x86_64-linux-gnu',
'/var/www/alyx/alyx/lib/python3.5/site-packages']
Server time:    Fri, 21 Jun 2019 17:42:42 +0100

**Comment by oliche** [comment]
@rossant this has to do with

**Comment by kevin-j-miller** [comment]
I'm experiencing what I think is the same error, also while trying to end a water restriction:


Request Method:  GET
Request Method: https://alyx.cortexlab.net/admin/actions/waterrestriction/34889c87-2700-47de-97f1-e4c960733a3f/change/
Django Version: 2.1.2
Exception Type: KeyError
Exception Value: 'reference_weight'
Exception Location: /var/www/alyx/alyx/actions/admin.py in get_form, line 265
Python Executable: /var/www/alyx/alyx/bin/python
Python Version: 3.5.2
Python Path: ['/var/www/alyx/alyx',  '/var/www/alyx/alyx/lib/python35.zip',  '/var/www/alyx/alyx/lib/python3.5',  '/var/www/alyx/alyx/lib/python3.5/plat-x86_64-linux-gnu',  '/var/www/alyx/alyx/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/var/www/alyx/alyx/lib/python3.5/site-packages']
Server Time: Fri, 28 Jun 2019 15:53:36 +0100

**Comment by oliche** [comment]
Bug related to #551, fixed on dev 0388dcd42aac6589f0eeacf4bf3dc6068d038028.
Note that you won't have write permissions if you are not the user that created the water administration.
