### ISSUE TITLE
monthly email for checklist

### ISSUE THREAD

**Issue by anne-urai** [cortex-lab/alyx#558]
on the 1st Monday of each month, send the user a reminder to go through the following checklist:
- water calibration, check tubing
- screen luminance measurement (and gamma calibration?)
- camera positioning, focus and exposure
- temperature and fan functioning
- distance mouse - screen

**Comment by k1o0** [comment]
A while ago in the data architecture working group we discussed email alerts and decided that Alyx emails should only be used for notifications directly related to animal welfare.  Other notification systems are better suited for these sorts of reminders but I can bring it up in the next meeting if you like?

**Comment by anne-urai** [comment]
That does make sense - perhaps we could consider something in pybpod or even on Slack

**Comment by rossant** [comment]
I'd tend to agree with @k1o0 , closing for now
