### ISSUE TITLE
Reasons for culling an animal

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#561]
List to be selected upon culling an animal (only the part that is not in bracket, part in bracket + extra details will have to be written in culling notes) :

-regular experiment end
-time limit reached (age, protocol, etc)
-benign experimental impediments (cataract, bone regrowth, mouse didn't learn task, etc)
-infection/illness (known or indeterminate)
-issue during surgery
-acute injury (headplate loss, indeterminate, etc)
-underweight
-other  (for unlikely events)

**Comment by nsteinme** [comment]
new schema looks great - can there also be a dropdown from the 'cull subjects' view to select these things there?

**Comment by rossant** [comment]
done
