### ISSUE TITLE
indicate alive with green checkmark, dead with red cross

### ISSUE THREAD

**Issue by anne-urai** [cortex-lab/alyx#569]
The current visual indication of alive/dead is a bit confusing - all the mice that are alive and well have a red cross, whereas the dead ones have a green checkmark. Should the column header be ‘Dead’ instead? Or can the checkmarks be switched around?
![Screen Shot 2019-07-31 at 12 03 13](https://user-images.githubusercontent.com/6636245/62228510-c9dc6100-b38b-11e9-986d-5a753eb7d68f.png)

**Comment by rossant** [comment]
There is a bug with this since the update, will fix soon
