### ISSUE TITLE
A few minor schema changes

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/alyx#57]
- Remove subjects.models.Strain - replace with string
- Add hydrogel NullBooleanField to WaterAdministered

@nsteinme are these OK?

**Comment by nsteinme** [comment]
Hydrogel flag is fine but I don't agree about the Strain - we should keep it - it's helpful to have a description (which as you can see I did use for the strains I made this morning), plus this way it is easier to standardize the options people use for it, no? With a string they could just write anything? We don't want them to just write anything for the strain.
