### ISSUE TITLE
KS014, KS015, KS016 wrong type of water

### ISSUE THREAD

**Issue by karolinasocha** [cortex-lab/alyx#573]
There is a mistake with the type of delivered water for mice: KS014, KS015, KS016. It should be Sucrose 10% instead of 15% on the 27th of July. How can I correct this?

**Comment by rossant** [comment]
You can edit these objects as follows:

- go here: https://alyx.cortexlab.net/admin/actions/wateradministration/?q=KS014&responsible_user=all
- find the water administration to change
- click on the number (water administered column)
- change it
- press Save
- repeat with other water administrations to change
