### ISSUE TITLE
Session narrative template

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#591]
We would like to have session narratives that are pre-defined (but still keeping the ability to add personal notes). For example, 

Headbar implantation - Template in Alyx
```
== General ==

Start time (hh:mm):   ___:___  
End time (hh:mm):    ___:___  

[etc]

== Notes ==
<write your notes here>

```

**Comment by rossant** [comment]
done in dev

**Comment by GaelleChapuis** [comment]
Sorry, re-opening this as I had written a shortened template (with etc), the long version (to be put in Alyx) is :

```
== General ==

Start time (hh:mm):   ___:___  
End time (hh:mm):    ___:___  

Bregma-Lambda :   _______  (mm)

== Drugs == (copy paste as many times as needed; select IV, SC or IP)
__________________( IV / SC / IP ) Admin. time (hh:mm)  ___:___

== Coordinates ==  (copy paste as many times as needed; select B or L)
(B / L) - Region: AP:  _______  ML:  ______  (mm)
 Region: _____________________________

== Notes ==
<write your notes here>
```

**Comment by GaelleChapuis** [comment]
And for consistency: could we change the name "Headplate implant" to "Headbar implant"?
(and is it a pain to re-patch previous datasets?)

**Comment by rossant** [comment]
one can easily change it here : https://dev.alyx.internationalbrainlab.org/admin/actions/proceduretype/7df34087-64a2-4846-a6ff-0a8390b3c0a4/change/  
but I guess the fixtures should also be changed @oliche

**Comment by rossant** [comment]
I've changed the narrative template on dev and main IBL alyx, and same on cortexlab (for future reference, this is stored in `settings_lab.py` at the moment)
