### ISSUE TITLE
Write link to flatiron data folder onto session page

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#592]
The session list is very useful in quickly checking what sessions have been recorded so far, and what datasets are uploaded onto flatiron.

Would it be possible to add into the session page (e.g. https://alyx.internationalbrainlab.org/admin/actions/session/0702d4af-1a11-4748-8ba8-5c2f2b95b203/change/?_changelist_filters=q%3Dcertification ) the link to the flatiron folder?

**Comment by rossant** [comment]
done in dev
