### ISSUE TITLE
Add project field as searchable information in certain alyx pages

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#595]
A number of pages would benefit from having the project field listed and searchable, so as to easily identify weather data is missing for mice in a specific project.

Those pages are:
- [x] cull https://alyx.internationalbrainlab.org/admin/actions/cull/?o=4.-1&p=2&q=
- [x] session https://alyx.internationalbrainlab.org/admin/actions/session/
- [x] surgeries https://alyx.internationalbrainlab.org/admin/actions/surgery/?responsible_user=all
- [x] water admin https://alyx.internationalbrainlab.org/admin/actions/wateradministration/?responsible_user=all
- [x] water restriction https://alyx.internationalbrainlab.org/admin/actions/waterrestriction/?responsible_user=all
- [x] weighings https://alyx.internationalbrainlab.org/admin/actions/weighing/?responsible_user=all

**Comment by rossant** [comment]
done in dev
