### ISSUE TITLE
Flatiron link listed on session page not found

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#604]
The session page displays a link to the flatiron repository. As far as I saw, independently of which lab the experiment has been conducted in, all sessions appear as belonging to the cortexlab and thus links are not found.

For example, to replicate:

This session page:  (Dan lab, certification protocol, mouse ID cer-5)
https://alyx.internationalbrainlab.org/admin/actions/session/06e6c248-e039-4191-ae3e-fe241a8d651d/change/?_changelist_filters=q%3Dcertification

Shows this link : http://ibl.flatironinstitute.org/cortexlab/Subjects/cer-5/2019-10-25/001/  > Not found

**Comment by rossant** [comment]
Thanks, this bug should now be fixed in the dev branch, and will be pulled later on the server

**Comment by rossant** [comment]
**Note**: next time alyx is updated on any server, one will have to edit `settings_lab.py` and replace the hard-coded `cortexlab` in the `SESSION_REPO_URL` variable by `{lab}`.

cc @oliche
