### ISSUE TITLE
filtering for projects doesn't work in admin interface

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#609]
I go to the 'sessions' view (http://alyx.steinmetzlab.net/admin/actions/session/), and under "by project" filter I select any project. There are many sessions for each of the projects, but nevertheless any selection here just returns 0 sessions.

**Comment by oliche** [comment]
We need to update your Alyx I think

**Comment by nsteinme** [comment]
I've just updated but this is still true. 
E.g. here's an image showing that I have a session with a certain project: 
![image](https://user-images.githubusercontent.com/7590975/73988746-7d547e00-48f8-11ea-976d-d2f1f831fb7a.png)
and here's showing that when I just change the filter to go for that project, I get nothing. 
![image](https://user-images.githubusercontent.com/7590975/73988779-8fceb780-48f8-11ea-8f93-f853cc0cd9d9.png)
Happy to know if I'm using this incorrectly or something?

**Comment by rossant** [comment]
Looks like a bug. Does the search box at the top work, if you type "widefieldopto"?

**Comment by nsteinme** [comment]
Good point, yes it does work to do that search, so that's a fine workaround
for now. By the way could we make it also able to do a search of the
"narrative" field? This would enable me to also have a workaround for the
other project feature request I had made, which is the ability to select
two or more projects for a single session (I could search the narrative for
appropriate terms instead). Also is there a narrative search from the
restAPI? Or a json search maybe?

thanks -

**Comment by nsteinme** [comment]
fwiw the behavior seems even more confusing now: there's a column "project" which identified the project of each session, but when filtering by project it actually seems to filter by the project of the *subject* not the project of the *sessions*.

**Comment by oliche** [comment]
Should we add both like this ?

![2020-03-11T07:33:56_screen](https://user-images.githubusercontent.com/15081095/76393093-c0c46100-636a-11ea-937a-9c039d8f9d6b.png)

**Comment by nsteinme** [comment]
Sure - no objection to that! I haven't personally been using 'subject
project' to sort sessions, but maybe I would.
