### ISSUE TITLE
"lab member" permissions not working properly? 

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#610]
I have a user who was a "lab member", and under "groups"->"lab member" I see that this group should have permission to "change session". But, in the admin interface she only sees a view of the session without any editable boxes. Changing her permissions to superuser and going back to the same page shows the correctly editable boxes. Did I misunderstand the permissions, or is this a bug?

**Comment by rossant** [comment]
Is this a session of an animal she owns, or an animal currently under water restriction?

**Comment by nsteinme** [comment]
No and no. Does she need to own the animal to edit the session?

**Comment by rossant** [comment]
There was a recent policy change as requested by Charu and others from cortexlab: you can only change your own mice or mice currently under water restrictions.

**Comment by nsteinme** [comment]
Ok, that's fine. Thanks for the update!
