### ISSUE TITLE
Allow entry of multiple users per subject

### ISSUE THREAD

**Issue by GaelleChapuis** [cortex-lab/alyx#613]
Currently : only 1 user is allowed per mouse ; if 2 or more users work on the same subject, it becomes cumbersome to change back and forth the responsible user.

Note: Would we lose track of who did a particular experiment?

**Comment by anne-urai** [comment]
100% agree. If users could be linked by lab, then a whole lab could be the responsible user for a mouse. One person would still be responsible for each action (training, surgery, etc) but the mouse would show up in both user's Alyx profiles.

**Comment by rossant** [comment]
I believe this would be a major change in the codebase that could create many bugs. Best would be to find a solution where there is only 1 responsible user per subject, but the permissions allowed for users in the same lab are good for everyone.
@anne-urai lately the permission policy has been driven by Charu's need from cortexlab so far, who apparently doesn't want someone to change someone else's mouse, unless the mouse is under water restriction. It would be best if we could find a single permission policy that could make everyone happy, both in cortexlab and IBL.

**Comment by oliche** [comment]
#615
