### ISSUE TITLE
how to load-init-fixtures.sh ?

### ISSUE THREAD

**Issue by luiztauffer** [cortex-lab/alyx#633]
Hi,
I'm able to run a local alyx server, access it through admin page and even remotely using python requests.
However, after `$ python alyx/manage.py runserver` the current terminal gets "busy" with the server and I can't enter the following steps: 
```
# An then initialize fixtures (ie. load default objects in the database)
cd scripts
./load-init-fixtures.sh
```

Detaching from the the server terminal and running `./load-init-fixtures.sh` I get a sequence of identical errors:
```
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
```

it's weird because django is installed in my current environment.
Can you help me? What am I doing wrong?

**Comment by oliche** [comment]
Hi there,
The scripts begins with
```
#!/usr/bin/env bash
cd ../alyx
source ../alyxvenv/bin/activate
```

I suspect you named your environment differently. The solution is to activate your environment and in the same way that you ran `runserver`, run the remaining of the script:

```
./manage.py loaddata ./actions/fixtures/actions.proceduretype.json
./manage.py loaddata ./actions/fixtures/actions.watertype.json
./manage.py loaddata ./actions/fixtures/actions.cullreason.json

./manage.py loaddata ./data/fixtures/data.datarepositorytype.json
./manage.py loaddata ./data/fixtures/data.dataformat.json
./manage.py loaddata ./data/fixtures/data.datasettype.json

./manage.py loaddata ./misc/fixtures/misc.cagetype.json
./manage.py loaddata ./misc/fixtures/misc.enrichment.json
./manage.py loaddata ./misc/fixtures/misc.food.json

./manage.py loaddata ./subjects/fixtures/subjects.source.json

./manage.py loaddata ./experiments/fixtures/experiments.coordinatesystem.json
./manage.py loaddata ./experiments/fixtures/experiments.probemodel.json
./manage.py loaddata ./experiments/fixtures/experiments.brainregion.json
```

**Comment by luiztauffer** [comment]
hi @oliche 
of course, it makes sense now, I was running it inside a conda environment. Thanks!

I managed to run the commands and get the `Installed N object(s) from 1 fixture(s)` messages. No new objects are added to the database though. I tried running the commands before `runserver` and after it (with the & operand). 
any suggestions?

**Comment by oliche** [comment]
Hello,
How do you check that objects have been added to the database ?
The best way is for example to go on the admin interface (connect to your url in a web browser and log in) and check for example the dataset types (or the other kind of fixtures). You should have objects in there.
Another way is through the django prompt.
```
from {app}.models import {Table}
{Table}.objects.all().count()
```
Let me know if you still have issues !
