### ISSUE TITLE
drop down menu for selecting animals on 'add breeding pair' page not working

### ISSUE THREAD

**Issue by charureddy** [cortex-lab/alyx#644]
On the breeding pair page, when adding new breeding pair, we were able to select the father and mother from the drop down list (by typing in the first 3 letters of line). The drop down menu is not working and there are only a few options available now.

![image](https://user-images.githubusercontent.com/28573276/89296463-48807400-d65a-11ea-8bff-85665c3f9c20.png)

**Comment by rossant** [comment]
Thanks for the bug report. Should be fixed now, do you confirm?

**Comment by charureddy** [comment]
Yes! Thanks Cyrille.
