### ISSUE TITLE
KeyError at /var/www/localhost/htdocs/alyx/lukelab/alyx/subjects/admin.py in __init__, line 785

### ISSUE THREAD

**Issue by mauricev** [cortex-lab/alyx#646]
For whatever odd reason, some of my users are experiencing this key error when trying to edit a breeding pair. As admin, I am not seeing it. 

I'm attaching the full traceback.
[Alyx_Error_200803.pdf](https://github.com/cortex-lab/alyx/files/5045850/Alyx_Error_200803.pdf)

**Comment by rossant** [comment]
Is alyx up to date with the master branch?

**Comment by mauricev** [comment]
Just updated it yesterday.

**Comment by mauricev** [comment]
Just confirmed that the md5sum of admin.py, which is b7f1f4e81edbe32b7f46edcfed2c908e, is the same as in my copy.

**Comment by rossant** [comment]
What is strange is that the error mentioned line 785 does not seem to match that file https://github.com/cortex-lab/alyx/blob/master/alyx/subjects/admin.py#L785
Have you done `sudo service apache2 reload`  after updating the git repo?

**Comment by mauricev** [comment]
Sorry, the user had resent the original error. I am attaching the current incarnation.

**Comment by mauricev** [comment]
Looks like it didn't get attached via email, so attaching directly here
[Alyx_Error_200808.pdf](https://github.com/cortex-lab/alyx/files/5046759/Alyx_Error_200808.pdf)

**Comment by rossant** [comment]
Thanks. Not sure what causes the issue but I pushed a tentative work-around to the master branch. Let met know if that fixed it

**Comment by mauricev** [comment]
The user reports this is fixed for breeding pairs. Thank you. The user reports this bug also afflicts litters. Please see attached.
[Alyx_Error_200809.pdf](https://github.com/cortex-lab/alyx/files/5048328/Alyx_Error_200809.pdf)

**Comment by rossant** [comment]
Another fix pushed, let me know!

**Comment by mauricev** [comment]
This has been fixed. Thanks!
