### ISSUE TITLE
Subjects added through entering the animals as a member of a litter cannot have their record edited

### ISSUE THREAD

**Issue by mauricev** [cortex-lab/alyx#649]
My user reports the following

a) I do this step through the add litter page
	b) The default person responsible is set to Diego and I have no option to change this as I set the litter. I checked to see whether this is because Diego created the breeding pair or animals but there is no option under breeding pair to specify a person responsible, and I believe both the breeding pairs and animals were entered were created by me.
	c) The record with the breeding pair is updated to reflect the additional litter (good!)
	d) The subject record generated from the add litter option is not editable (bad!)
		i)	See print screen with AlyxError_Subject-from-litter_200818.PDF, most fields cannot be edited
		ii)	Compare to AlyxError_Subject-from-new_200818.PDF
[AlyxError_Subject-from-litter_200818.pdf](https://github.com/cortex-lab/alyx/files/5099109/AlyxError_Subject-from-litter_200818.pdf)
[AlyxError_Subject-from-new_200818.pdf](https://github.com/cortex-lab/alyx/files/5099110/AlyxError_Subject-from-new_200818.pdf)

**Comment by claire-rbblab** [comment]
@mauricev @rossant UPDATE: I am no longer having this issue. Thank you.
