### ISSUE TITLE
Subjects added outside of the add-litter option w/ indicating animal is from a certain litter under the "Profile" section.

### ISSUE THREAD

**Issue by mauricev** [cortex-lab/alyx#650]
a) Got an error message that seems to be the same Django message occurring with the Litter and Breeding pairs pages
	b) Here you have to duplicate some information that is stored elsewhere like date of birth. I double checked the litter that I was trying to add to and I do not think that the error was coming from conflicting info (like two different dates of birth). It would be better if I didn't need to enter the same information twice to avoid any possible conflicts.
	c) I was hoping that I could use this option to add subjects to litters in the same way that I could add litters to breeding pairs above (point 1c, AlexError_SubjectAdd_w_Litter.PDF)
[AlyxError_SubjectAdd-w-Litter_200818.pdf](https://github.com/cortex-lab/alyx/files/5099125/AlyxError_SubjectAdd-w-Litter_200818.pdf)

**Comment by claire-rbblab** [comment]
@mauricev @rossant I am nolonger getting this error. Thank you.
