### ISSUE TITLE
Dead animals in drop-down menus

### ISSUE THREAD

**Issue by BexTerry** [cortex-lab/alyx#663]
![image](https://user-images.githubusercontent.com/55093069/94671801-41997900-030c-11eb-9b5e-8158a7ae6c79.png)
In the Add Weighing and Add Water Restriction pages (and when selecting animals in breeding cages), the drop down menu lists every animal that ever existed
Can we have it so only live animals appear in these menus?

**Comment by rossant** [comment]
should be fixed in next release
