### ISSUE TITLE
REST endpoint for surgeries?

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#668]
There's currently no way to query the rest api for surgeries - could we have an endpoint for that?

**Comment by rossant** [comment]
Yep https://github.com/cortex-lab/alyx/pull/667
reviewing it now

**Comment by oliche** [comment]
After update, this will get the surgeries through the endpoint using ONE:

```
from oneibl.one import ONE
one = ONE()
surgeries = one.alyx.rest('surgeries', 'list')
subjects = one.alyx.rest('subjects', 'list')
```
