### ISSUE TITLE
Personal project on Alyx and added option

### ISSUE THREAD

**Issue by Marsataheri** [cortex-lab/alyx#696]
I'd like to add my personal project (https://github.com/int-brain-lab/project_registration/issues/72) to the database, so I can assign my first batch of mice to this project. Can one of the admins please help create this project on Alyx?

Also, in about 1-1.5 months, after AAV injections, I will begin i.p. administration of either CNO or saline, on alternating days. Can Alyx be extended to include such an option for entry of drug(s) administered? Otherwise, should I include this information in the 'Notes' section? If so, with DataJoint, can I query what's written in the notes?

**Comment by k1o0** [comment]
At the moment there are just notes and narrative fields, however you can search these with ONE so if you keep your notes consistent, e.g. `SUBSTANCE: xxx yyml` then you can easily search for specific terms in the notes with a REST query.  You can add multiple notes to a given surgery/procedure.  Notes don't appear to be ingested in DataJoint, however the narrative field is.
