### ISSUE TITLE
Add API filtering

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/alyx#70]
e.g. `/subjects/?alive=True`

**Comment by nsteinme** [comment]
I think you meant `/subjects?alive=True`...

Here are the specific filters I'd like to do most urgently for the matlab "mc" interface:
- subjects by Alive
- subjects by responsible_user (I see this is already possible using the resp user's id number, which I can do)
- sessions by Subject
- sessions by Date

(I do get that I can do all of this currently simply by asking for everything and doing the filtering myself).

**Comment by nsteinme** [comment]
@nippoo

**Comment by nsteinme** [comment]
@nippoo this one
