### ISSUE TITLE
Breeding cage ID not saving

### ISSUE THREAD

**Issue by BexTerry** [cortex-lab/alyx#735]
I think this might be an issue with the change allowing letters and numbers in the breeding cage ID
Since that update, I cannot change the cage ID that was imported with the mouse from it's stock cage.
(Ideally we don't want the cage ID autofilling when making a new cage anyway)

![image](https://user-images.githubusercontent.com/55093069/163971517-df74a5fe-a06a-40f3-a187-8c05642ede13.png)
![image](https://user-images.githubusercontent.com/55093069/163971654-59634c89-f8e6-4125-b132-8c9a41480fc4.png)

Whatever I type and save as the cage ID reverts to blank when I click on the cage, but on the Breeding Pair page the cage ID is not updated, remaining what it used to be.
This is the case with all breeding cages.

**Comment by k1o0** [comment]
Appears to be fixed
