### ISSUE TITLE
export of database

### ISSUE THREAD

**Issue by jofrony** [cortex-lab/alyx#767]
Hi,

I have question about the database. Do you have an export function if we decided to move our database to another system?

**Comment by k1o0** [comment]
Hello, sorry for taking so long to respond! We have documentation on how to make backups [here](https://docs.google.com/document/d/1cx3XLZiZRh3lUzhhR_p65BggEqTKpXHUDkUDagvf9Kc/edit?tab=t.0#heading=h.dibimc48a9xl). Will we add a link to this document in our getting started guide.

Thanks for taking the time to open an issue. We will try to be more responsive going forward.
