### ISSUE TITLE
Problem with login into database after creation

### ISSUE THREAD

**Issue by jofrony** [cortex-lab/alyx#770]
Hi,

We follow the instructions at https://github.com/cortex-lab/alyx/blob/master/docs/gettingstarted.md.

    ...
    $ Enter a database name [alyxlocal]:
    $ Enter a postgres username [alyxlocaluser]:
    $ Enter a postgres password:
    ...

We set up a postgres username and password but when we tried to enter them at http://localhost:8000/admin, we could not log in.
We get the following error message: "Please enter the correct username and password for a staff account...]

Maybe we misunderstood the instructions?

Thank you!

**Comment by oliche** [comment]
Hello,

Yes, maybe this is not explicit. I realize it is not obvious. The password you've entered above is a postgres password that is used only by django to connect to the database. It is never entered manually unless you perform maintenance at the psql prompt.

The admin interface default password is admin/admin, and the next instruction is to change it !
> Then go to http://localhost:8000/admin, connect as admin:admin and change your password.

Iv'e rephrased on this commit: 637f52aea816ee65c75ee977cf4e756becdb37ca
