### ISSUE TITLE
Setting up an IBL behavior rig with a local Alyx database

### ISSUE THREAD

**Issue by RuyG-O** [cortex-lab/alyx#787]
We have recently assembled an IBL behavior rig in our Lab and started collecting training data with it. We are now trying to establish locally the data architecture described in the IBL publications. We have managed to set up a local Alyx database that runs on a Linux server in the same local network as the IBL rig acquisition computer. We are using this local Alyx database to store the metadata for our experiments (subjects, weighings, water restrictions, etc.), and acquiring behavior data with the IBL rig. However, we have not yet managed to link the experimental data files with the corresponding metadata stored in Alyx. When we finish running a training session, the following message is printed in the terminal and a session is created in Alyx:

![Screenshot1](https://user-images.githubusercontent.com/126488527/236315035-a6c1a226-607f-44fc-a1b6-657079203b9c.png)

However, the experimental data files don't get registered to the sessions:

![Screenshot2](https://user-images.githubusercontent.com/126488527/236315080-c7135e95-b76b-47cf-93ed-92537eac3789.png)

We used the ONE.setup() method to define as base_url the local IP address on which our local Alyx runs, and the local Alyx  username and password.

In our settings_lab.py file we changed

  ```
  SESSION_REPO_URL = \
      "http://ibl.flatironinstitute.org/{lab}/Subjects/{subject}/{date}/{number:03d}/"
  ```

to

  ```
  SESSION_REPO_URL = \
      "<URL for the data folder in the acquisition computer>/Subjects/{subject}/{date}/{number:03d}/"
  ```

Could you please let us know how to coreectly set up Alyx and ONE to work with a local server / data repository? 

Many thanks for the help and for developing this tool!

**Comment by k1o0** [comment]
Resolved over personal communication and improvements to instructions.
