### ISSUE TITLE
Maybe rename "Experiment" to "Session" and remove Surgery altogether?

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/alyx#79]
This is a @nsteinme Idea™. I'm not sure if this is more or less confusing but it does make `Surgery` redundant... and it's plausible that people might want to do recordings during a surgery, for example.

@kdharris101 thoughts?

**Comment by kdharris101** [comment]
Let’s talk about it.

**Comment by rossant** [comment]
What was the conclusion?

**Comment by nsteinme** [comment]
I think that we do want to collapse them, but for it to work we might want
to bring back the idea of a "tags" field that autocompletes when you are
entering something. Do you remember that? Is it possible?

**Comment by nsteinme** [comment]
@rossant @nippoo Let's do at least re-name Experiment to Session. Hold off on collapsing them for now.

**Comment by rossant** [comment]
done in PR
