### ISSUE TITLE
add subjects to litters from the litter page

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#8]

**Comment by nsteinme** [comment]
Here should fill in automatically the birth date, cage, line, user, etc for the subjects based on properties of the litter. Only things the user should specify are gender, earmark, and zygosities.

**Comment by rossant** [comment]
Partially done. To do: fill in automatically stuff based on the properties of the litter.

**Comment by rossant** [comment]
Initially, I tried to autofill the input boxes but it looks like it's not easily doable with django... Much easier is to *hide* the autofilled fields. You can just specify gender, earmark, and zygosities (I haven't done that last one yet, it's tricky because it's a many to many field). The hidden fields are filled in automatically. You can then change them by going to the Change Subject page.

**Comment by nsteinme** [comment]
Can I clarify: what you mean is that the field will be autofilled when the
subject is created, but you can't auto-fill it in the display when you're
creating a subject? There's no way to specify a default option (one that
changes depending on the line)? What about creating the new subject,
autofilling the fields, and then taking the user straight to the Change
Subject page for that subject?

By hiding, you mean you would hide the fields that *will be* autofilled
later after the subject is created? This is an ok solution - we can go with
it and then see how often it turns out that you wanted to change one of
those things after all (hopefully not).

**Comment by rossant** [comment]
I think you understood correctly. Look here:

![image](https://cloud.githubusercontent.com/assets/1942359/22737142/05ed0ea8-ee02-11e6-96d1-eb3c36529489.png)

This is the "Change Litter" page. The first two lines are the existing subjects in the litter (mother and father). The third line is an empty one with, if you fill it, a new subject. I'll have to add the genotype. When you click "Save", that new subject is created, and most parameters are just copied from the mother (cage, species, strain, source, responsible_user, line). The birth date is the litter's birth date. I don't know how to autofill the nickname exactly.

Once the subject is created, you can go to the Change Subject page and change all fields.

Actually, I just checked and we *can* show certain autofilled fields. If you don't fill them in the form, they will be autofilled automatically when you save, but you're not going to see the autofilled values until you've clicked on "Save". If you fill them in the form, these values will be used instead.

**Comment by rossant** [comment]
It's going to be visually clearer if we hide certain autofilled fields that are very unlikely to change. If I put all fields it's quite cluttered:

![image](https://cloud.githubusercontent.com/assets/1942359/22737828/2e1f8dbc-ee05-11e6-8526-035dc23d375e.png)

**Comment by nsteinme** [comment]
Looks beautiful! Let's go with the first version - where nearly everything is hidden - for now and we can see how it goes, un-hide if necessary. Let's also include "notes" in un-hidden, since sometimes they'll write things like "runt" or whatever. 

For the name autofill, you should take the "auto_name" from the line (let's say it is XYZ), look through the database of subjects for the last one with a name of the form "XYZ_0013", and give it the name with incremented number (XYZ_0014). The exact name here isn't at all critical - it doesn't matter if a number gets skipped somehow or whatever. It's just so there's something by default there. Maybe another way to imagine it is to have a "counter" field in the Line, that keeps track of the total number of mice that have been given autonames in that line. Anyway, I don't know. Does something along these lines (uh) seem do-able?

**Comment by rossant** [comment]
OK it's all done.

Last thing: how to specify the genotype? It's a manytomany field and we can't add this in an inline. A solution could be to specify it via a string instead, like `"GFP+; ROSA-WT+; AI95+/-"`?

**Comment by rossant** [comment]
Closing in favor of #28
