### ISSUE TITLE
Refactor all ExpMetadata to be polymorphic models

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/alyx#81]
The current situation will be a huge performance hit when trying to render the `ExpMetadataSummaryAPIView`. It'll have to do one SQL `JOIN` per model - potentially dozens and dozens.

Instead there should be a BaseExpMetadata model `exp_metadata` table with `start_date_time`, `end_date_time`, `json`, `polymorphic_ctype` column and individual tables for extra fields.

Related: #80

**Comment by nsteinme** [comment]
The other option is to have different endpoints for each exp-metadata type,
no? Maybe we should consider that.

**Comment by nippoo** [comment]
Yep, could do. But you'll still have this issue if you want to list everything within an `Experiment` (it's just displaying the `ExpMetadataSummaryAPIView`. Having a separate endpoint is fine but then there's no good way of finding all the models that are associated with one experiment.
