### ISSUE TITLE
Cannot login to admin console

### ISSUE THREAD

**Issue by neuromantic99** [cortex-lab/alyx#834]
Hi,

I have installed alyx on macos as per the installation instructions, system check identifies no issues.

However after running `python alyx/manage.py runserver` I cannot log in as admin on localhost:8000

Username: admin 
Password: admin

Gives the error message: Please enter the correct username and password for a staff account.

Any help would be much appreciated!

**Comment by k1o0** [comment]
Hello,

Sorry for the slow response. You may need to create a new superuser in order to access the admin interface. You can do this with the following: `python manage.py createsuperuser`. Django will prompt you for a new username and password with which you can log in.

**Comment by k1o0** [comment]
Closing due to lack of response. Feel free to reopen if you have more questions.
