### ISSUE TITLE
Subject auto-name not working

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#84]
I made a new litter and added four subjects to it, which got names Ai95-0001, -0002, -0003, and -0004. That would be ok, except mice Ai95-0001 and Ai95-0002 had already existed - so this should have started from 3 and given me 3, 4, 5, and 6. Witness SubjectInline on the Litter page:

![image](https://cloud.githubusercontent.com/assets/7590975/23166737/b0cb23d2-f839-11e6-8113-15edd282d513.png)

which shows that mouse Ai95-0002 has a mother named Ai95-0002. The subject view also now shows two mice with the same name: 

![image](https://cloud.githubusercontent.com/assets/7590975/23166761/c82ade5a-f839-11e6-9bc1-a6ced63e9648.png)

**Comment by nsteinme** [comment]
Actually I note that maybe this is a hyphen/underscore thing - did you switch at some point from making autonames with hyphens to making them with underscores?

**Comment by rossant** [comment]
No it should always have been underscore

**Comment by nsteinme** [comment]
Hm, ok, well I think it just happened because somehow those first two got hyphens in their names. It looks like they are reliably created with underscores now. I'll close this and let you know if I see it again.
