### ISSUE TITLE
creating a subject from in the inline on a litter's page, should autofill cage from the litter's cage

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#85]
E.g. I just tried it and go this, where the new subject's cage was autofilled to be _0003 but the litter was in cage _0001.

![image](https://cloud.githubusercontent.com/assets/7590975/23170281/838d7fc0-f846-11e6-9544-723e46068116.png)

**Comment by rossant** [comment]
Should be fixed.
