### ISSUE TITLE
way to auto-save forms? or warn on navigating away from page with un-saved actions? 

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#90]
Maybe a way to save whenever you navigate away from a page, unless you specifically navigate away using a cancel button? 

I know this might be a tricky one, but Charu says it is a lot more button presses than using google spreadsheet right now because of all the saving you have to do, and was quite negative about the experience because of this...

**Comment by rossant** [comment]
Why are there many saving to do, not just one?

**Comment by nsteinme** [comment]
Once per action, lots of different actions - like on multiple mice,
multiple lines.

**Comment by rossant** [comment]
I don't think there is a way to autosave. I think it would be better to understand why there is a need to go on so many different pages at once. Maybe we could create a new page adapted to that specific workflow, which would regroup all actions that need to be done at once?

**Comment by nsteinme** [comment]
Yeah, agreed. What's the possibility of designing totally customized views,
i.e. that don't depend on the limitations of the admin interface? I don't
think we're quite at the point of needing to do that yet - let's keep
working on molding the admin to get closer and closer for now - but I'm
just wondering whether it is a thing we can/should be thinking about as
another possibility.

**Comment by rossant** [comment]
Yes that's possible I think, right @nippoo ?

**Comment by nsteinme** [comment]
I think Max is out of town for another couple weeks.... :/

**Comment by nsteinme** [comment]
Maybe we should think about making a desktop app for this instead? I know I
could make one in matlab easily - I'm guessing you'd find it easy in python
too. It could be more straightforward than working with web protocols?
Anyway, still just brainstorming here, let's still keep to the admin
interface for now.

**Comment by rossant** [comment]
I agree, the first step is to go from 0 to 1, have something that *works*. I think the admin interface is good enough to get started and to have a "fallback" interface when something breaks. Later on, we can always do web apps and MATLAB GUIs and desktop apps and whatever. We can use either django/python or the REST API.

**Comment by rossant** [comment]
closing for now
