### ISSUE TITLE
subject requests

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#93]
Here's how subject requests should work. First, subject requests should have a list of foreign keys to Subjects, which are the subjects that have fulfilled the request. Then whenever a subject is changed to have responsible user X, it should check whether X has any outstanding subject requests for that line. If so, add that subject to the list of fulfilling subjects. When the length of that list is equal to the number of subjects requested, this request is marked as resolved.

**Comment by rossant** [comment]
Do you mean that subject should have a new optional `subject_request` field? Then in each subject request page, you will see the list of subjects that have been added to the subject request. There will also be a read-only field in subject request with the number of remaining subjects, and whether the request is resolved.

**Comment by nsteinme** [comment]
That could work - I was imagining that it might infer which SubjectRequest the Subject should go to, given the Line and the User that the subject was changed to. But your solution sounds like an equally clear way to do it, let's go for it. Will that be a dropdown? If so, it should autofill with only the SubjectRequests that are for the Line of the Subject, and that are still unfilled.

**Comment by rossant** [comment]
Ah, I guess it could be done automatically too. I'll try that.

**Comment by rossant** [comment]
So I suggest to change "status" from a regular field to a read-only field which depends on the number of subjects from that line for the current user. If it reaches the requested count, the request is closed. We can also have a read-only field `remaining` with the number of remaining subjects.

**Comment by nsteinme** [comment]
I don't think this quite works. Imagine I put in a request for three mice,
it gets fulfilled, and I'm doing my experiments with those mice, great. But
then I want three more so I make a new request. It shows up as already
fulfilled in your proposal since I do have three from that line. I can't
change the request number to six, because if one of my original three dies
or if I give it to another user, I still want those three new ones (not
four new ones). Conceptually, the right thing is to have specific subjects
be assigned to fulfill the request. One way could be to have the subject
get a field called "request_fulfilling" or something, where you set that
subject to be fulfilling that request - when there are 3 such subjects, the
request is closed.

**Comment by rossant** [comment]
I see. You mean that for a given pair (user, line) you could have several requests? It's not desirable to reuse he same request and change it as you go? If not then we have to assign subjects to requests indeed.

**Comment by nsteinme** [comment]
I think it seems a bit more logical to have separate requests each time you
want more mice. It'll fit the way we plan experiments more closely. It's
the way we do it now, anyway.

**Comment by rossant** [comment]
Should be done

**Comment by nsteinme** [comment]
Not quite? check out this request: http://alyx.cortexlab.net/admin/subjects/subjectrequest/205bfcbf-ed1e-4751-905c-93e2caa2c018/change/

It lists eight subjects as being part of this request, but if you go to them, they don't have a subject request selected. I think it's currently listing any subject of that line belonging to that user, rather than those that specifically have a foreign key to the subject request in question.

**Comment by rossant** [comment]
OK, update and try again?

**Comment by nsteinme** [comment]
Great, that works. One more small thing - i'll make another issue for it -
