### ISSUE TITLE
add zygosities string to the Subject list

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#94]
I.e. on this page - http://alyx.cortexlab.net/admin/subjects/subject/ - it should show also "Zygosities" and give the string version, like "Ai95 +/-; Vglut1-Cre +/-".

**Comment by nsteinme** [comment]
Also here, is it possible for the Cage name to become a link to that cage? If so, can we also add columns for Litter and Line and make them all three links to edit those entries?

**Comment by nsteinme** [comment]
I think that's here, maybe: https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display_links

**Comment by rossant** [comment]
Done
