### ISSUE TITLE
New API endpoint with raw SQL queries

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#99]

**Comment by rossant** [comment]
@nsteinme  Actually I'm wondering: why would you need this if you are able to connect directly to the database and execute SQL queries? (I think you're using MATLAB for that?)

**Comment by nsteinme** [comment]
Yes we made this issue before it was possible to do that. We'll discuss
with max - I think he may prefer everything going through the rest api. We
can wait on this for now, then.

**Comment by rossant** [comment]
probably better not to do this for now -- connecting directly via postgres to the database (read-only) might be the simplest option
